// misconceptions.ts — L25: Type-safe Error Handling
export const misconceptions = [
  { id: 1, concept: "result-vs-throw", misconception: "Result<T,E> ersetzt vollständig throw — man soll nie mehr werfen.", correction: "throw bleibt richtig für: Bugs/Invariant-Verletzungen, Initialisierungsfehler (fehlende Env-Vars), und als Wrapper-Grenze für externe Systeme. Result ist für ERWARTETE Fehler.", example: "throw new Error('DB_URL fehlt') // Richtig — App kann nicht starten\nreturn err({ type: 'USER_NOT_FOUND' }) // Richtig — erwarteter Fall" },
  { id: 2, concept: "ok-boolean-widening", misconception: "{ ok: true, value: user } erzeugt automatisch einen Discriminated Union.", correction: "TypeScript inferiert `ok: boolean` (nicht `ok: true`) — zu breit für narrowing. Entweder `ok: true as const` oder Helper-Funktion `ok()` verwenden.", example: "const r = { ok: true, value: 42 }; // ok: boolean — KEIN Narrowing!\nconst r2 = { ok: true as const, value: 42 }; // ok: true — Narrowing ✅" },
  { id: 3, concept: "option-is-result", misconception: "Option<T> und Result<T, E> sind das Gleiche — nur unterschiedliche Namen.", correction: "Option = 'vielleicht ein Wert' (null = normaler Zustand). Result = 'Operation die scheitern kann' (error = Fehler mit Details). findUser → Option. createUser → Result.", example: "findUser('id'): User | null // Option — null = normal\ncreateUser(data): Result<User, ValidationError> // Result — Err = Fehler" },
  { id: 4, concept: "assertnever-runtime-only", misconception: "assertNever ist nur für Runtime-Sicherheit — kein Compile-Time-Effekt.", correction: "assertNever ist primär für Compile-Time-Exhaustivität. Der `never`-Parameter erzwingt dass alle Union-Varianten behandelt wurden — zur Compile-Zeit. Zur Laufzeit sollte assertNever NIE aufgerufen werden (wenn Code korrekt ist).", example: "switch(err.type) { case 'X': ... default: return assertNever(err) }\n// Wenn 'Y' zu ApiError hinzukommt → COMPILE-ERROR in der default-Zeile" },
  { id: 5, concept: "map-vs-flatmap", misconception: "mapResult und flatMapResult sind identisch — nur unterschiedliche Namen.", correction: "map: fn gibt U zurück → Result<U, E>. flatMap: fn gibt Result<U, E> zurück → Result<U, E> (nicht Result<Result<U,E>,E>). Wenn fn selbst fehlschlagen kann → flatMap.", example: "mapResult(r, v => v.length) // fn gibt number — Map ✅\nflatMapResult(r, v => parseEmail(v)) // fn gibt Result — FlatMap ✅" },
  { id: 6, concept: "strictnullchecks-optional", misconception: "strictNullChecks ist optional und nur für große Projekte nötig.", correction: "strictNullChecks ist das wichtigste TypeScript-Setting. Es macht null/undefined zu echten Typen die behandelt werden müssen. Ohne es ist jede string-Variable implizit auch null/undefined — kein Schutz vor Null-Reference-Exceptions.", example: "// Ohne strictNullChecks:\nconst name: string = null; // Kein Fehler! Crash später.\n// Mit strictNullChecks:\nconst name: string | null = null; // Explizit, sicher" },
  { id: 7, concept: "satisfies-vs-annotation", misconception: "satisfies Record<K,V> und `: Record<K,V>` sind identisch.", correction: "satisfies: prüft Vollständigkeit UND behält spezifische Typen (Literal-Typen). Annotation `: Record<K,V>`: prüft Vollständigkeit ABER verliert spezifische Typen (alle Values werden zu V).", example: "const x = { A: 'hello' } satisfies Record<Status, string>;\n// x.A hat Typ 'hello' (literal!)\nconst y: Record<Status, string> = { A: 'hello' };\n// y.A hat Typ 'string' (breiter)" },
  { id: 8, concept: "catch-variable-type", misconception: "In try/catch hat der error immer Typ Error — ich kann error.message direkt verwenden.", correction: "Mit strict: true hat error Typ `unknown`. Du musst `instanceOf Error` prüfen bevor du auf .message zugreifst. Nicht jeder throw wirft ein Error-Objekt — throw 'string' ist gültiges JS.", example: "try { ... } catch (error) {\n  error.message // ❌ COMPILE-ERROR: error ist 'unknown'\n  if (error instanceof Error) {\n    error.message // ✅ Narrowing auf Error\n  }\n}" }
];
