/**
 * Lektion 16 — Tracing-Exercises: Mapped Types
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  {
    id: "16-mapped-type-iteration",
    title: "Mapped Type Iteration ueber Keys",
    description: "Verfolge wie ein Mapped Type Schritt fuer Schritt ueber die Keys iteriert.",
    code: [
      "interface User {",
      "  id: number;",
      "  name: string;",
      "  email: string;",
      "}",
      "",
      "type Nullable<T> = { [K in keyof T]: T[K] | null };",
      "",
      "type NullableUser = Nullable<User>;",
    ],
    steps: [
      {
        lineIndex: 6,
        question: "Was ist keyof User?",
        expectedAnswer: "'id' | 'name' | 'email'",
        variables: { "keyof User": "'id' | 'name' | 'email'" },
        explanation: "keyof gibt die Union aller Property-Namen zurueck.",
      },
      {
        lineIndex: 8,
        question: "Was passiert fuer K = 'id'?",
        expectedAnswer: "id: number | null",
        variables: { "K": "'id'", "T[K]": "number", "T[K] | null": "number | null" },
        explanation: "Fuer K='id' ist T[K] = User['id'] = number. | null wird hinzugefuegt.",
      },
      {
        lineIndex: 8,
        question: "Was passiert fuer K = 'name'?",
        expectedAnswer: "name: string | null",
        variables: { "K": "'name'", "T[K]": "string", "T[K] | null": "string | null" },
        explanation: "Fuer K='name' ist T[K] = string. | null wird hinzugefuegt.",
      },
      {
        lineIndex: 8,
        question: "Was ist das vollstaendige Ergebnis NullableUser?",
        expectedAnswer: "{ id: number | null; name: string | null; email: string | null; }",
        variables: { "NullableUser": "{ id: number | null; name: string | null; email: string | null; }" },
        explanation: "Der Mapped Type hat ueber alle 3 Keys iteriert und jedem | null hinzugefuegt.",
      },
    ],
    concept: "mapped-type-iteration",
    difficulty: 1,
  },
  {
    id: "16-key-remapping-flow",
    title: "Key Remapping mit Filterung",
    description: "Verfolge wie Key Remapping Keys umbenennt und filtert.",
    code: [
      "type StringKeysOnly<T> = {",
      "  [K in keyof T as T[K] extends string ? K : never]: T[K];",
      "};",
      "",
      "interface Product {",
      "  id: number;",
      "  name: string;",
      "  price: number;",
      "  description: string;",
      "}",
      "",
      "type StringProps = StringKeysOnly<Product>;",
    ],
    steps: [
      {
        lineIndex: 11,
        question: "Was passiert fuer K = 'id'? (id: number)",
        expectedAnswer: "number extends string? Nein -> never -> Key wird entfernt",
        variables: { "K": "'id'", "T[K]": "number", "number extends string": "false", "Remapped Key": "never" },
        explanation: "number extends string ist false. never als Key = Key wird entfernt.",
      },
      {
        lineIndex: 11,
        question: "Was passiert fuer K = 'name'? (name: string)",
        expectedAnswer: "string extends string? Ja -> K bleibt -> name: string",
        variables: { "K": "'name'", "T[K]": "string", "string extends string": "true", "Remapped Key": "'name'" },
        explanation: "string extends string ist true. K bleibt erhalten.",
      },
      {
        lineIndex: 11,
        question: "Was passiert fuer K = 'price'? (price: number)",
        expectedAnswer: "number extends string? Nein -> never -> Key wird entfernt",
        variables: { "K": "'price'", "T[K]": "number", "Remapped Key": "never" },
        explanation: "Wie bei 'id': number ist kein string, Key wird entfernt.",
      },
      {
        lineIndex: 11,
        question: "Was ist das Endergebnis StringProps?",
        expectedAnswer: "{ name: string; description: string; }",
        variables: { "StringProps": "{ name: string; description: string; }" },
        explanation: "Nur name und description haben string-Typ. id und price wurden herausgefiltert.",
      },
    ],
    concept: "key-remapping-filtering",
    difficulty: 2,
  },
  {
    id: "16-modifier-effects",
    title: "Modifier-Effekte auf Properties",
    description: "Verfolge wie verschiedene Modifier die Properties veraendern.",
    code: [
      "interface Original {",
      "  readonly host: string;",
      "  port?: number;",
      "  readonly debug?: boolean;",
      "}",
      "",
      "type A = { -readonly [K in keyof Original]: Original[K] };",
      "type B = { [K in keyof Original]-?: Original[K] };",
      "type C = { -readonly [K in keyof Original]-?: Original[K] };",
    ],
    steps: [
      {
        lineIndex: 6,
        question: "Was ist Typ A? (-readonly)",
        expectedAnswer: "{ host: string; port?: number; debug?: boolean; }",
        variables: { "A": "{ host: string; port?: number; debug?: boolean; }" },
        explanation: "-readonly entfernt readonly. host und debug verlieren readonly. Optional (?) bleibt erhalten.",
      },
      {
        lineIndex: 7,
        question: "Was ist Typ B? (-?)",
        expectedAnswer: "{ readonly host: string; port: number; readonly debug: boolean; }",
        variables: { "B": "{ readonly host: string; port: number; readonly debug: boolean; }" },
        explanation: "-? entfernt optional. port und debug werden Pflicht. Readonly bleibt erhalten.",
      },
      {
        lineIndex: 8,
        question: "Was ist Typ C? (-readonly und -?)",
        expectedAnswer: "{ host: string; port: number; debug: boolean; }",
        variables: { "C": "{ host: string; port: number; debug: boolean; }" },
        explanation: "Beide Modifier werden entfernt. Alles ist beschreibbar und Pflicht.",
      },
    ],
    concept: "modifier-combinations",
    difficulty: 2,
  },
  {
    id: "16-conditional-mapped",
    title: "Conditional innerhalb Mapped Type",
    description: "Verfolge wie Conditionals pro Property unterschiedlich wirken.",
    code: [
      "type Serialize<T> = {",
      "  [K in keyof T]: T[K] extends Date ? string",
      "    : T[K] extends boolean ? 'true' | 'false'",
      "    : T[K];",
      "};",
      "",
      "interface Event {",
      "  name: string;",
      "  date: Date;",
      "  active: boolean;",
      "  count: number;",
      "}",
      "",
      "type SerializedEvent = Serialize<Event>;",
    ],
    steps: [
      {
        lineIndex: 13,
        question: "Was wird aus 'name: string'?",
        expectedAnswer: "name: string (unveraendert — kein Conditional trifft zu)",
        variables: { "K": "'name'", "T[K]": "string", "Result": "string" },
        explanation: "string extends Date? Nein. string extends boolean? Nein. -> T[K] = string bleibt.",
      },
      {
        lineIndex: 13,
        question: "Was wird aus 'date: Date'?",
        expectedAnswer: "date: string (Date extends Date -> string)",
        variables: { "K": "'date'", "T[K]": "Date", "Result": "string" },
        explanation: "Date extends Date ist true -> erster Branch: string.",
      },
      {
        lineIndex: 13,
        question: "Was wird aus 'active: boolean'?",
        expectedAnswer: "active: 'true' | 'false'",
        variables: { "K": "'active'", "T[K]": "boolean", "Result": "'true' | 'false'" },
        explanation: "boolean extends Date? Nein. boolean extends boolean? Ja -> 'true' | 'false'.",
      },
      {
        lineIndex: 13,
        question: "Was ist das vollstaendige Ergebnis?",
        expectedAnswer: "{ name: string; date: string; active: 'true' | 'false'; count: number; }",
        variables: { "SerializedEvent": "{ name: string; date: string; active: 'true' | 'false'; count: number; }" },
        explanation: "Jede Property wird individuell durch den Conditional Type transformiert.",
      },
    ],
    concept: "conditional-per-property",
    difficulty: 3,
  },
];
