/**
 * Lesson 14 — Parson's Problems: Generic Patterns
 */

import type { ParsonsProblem } from "../tools/parsons-engine.ts";

export const parsonsProblems: ParsonsProblem[] = [
  {
    id: "L14-P1",
    title: "Generic Stack with Iterator",
    description: "Arrange the lines into a type-safe Stack class with iterator support.",
    correctOrder: [
      "class Stack<T> {",
      "  private items: T[] = [];",
      "",
      "  push(item: T): void {",
      "    this.items.push(item);",
      "  }",
      "",
      "  pop(): T | undefined {",
      "    return this.items.pop();",
      "  }",
      "",
      "  *[Symbol.iterator](): Iterator<T> {",
      "    for (let i = this.items.length - 1; i >= 0; i--) {",
      "      yield this.items[i];",
      "    }",
      "  }",
      "}",
    ],
    distractors: [
      "  pop(): T {",
      "  *[Symbol.iterator](): Iterator<unknown> {",
    ],
    hint: "pop() returns T | undefined (not T) and the iterator returns T (not unknown).",
    concept: "generic-stack-iterator",
    difficulty: 3,
  },

  {
    id: "L14-P2",
    title: "pipe() with Overloads",
    description: "Arrange the lines into a type-safe pipe function with overloads.",
    correctOrder: [
      "function pipe<A, B>(v: A, f1: (a: A) => B): B;",
      "function pipe<A, B, C>(",
      "  v: A, f1: (a: A) => B, f2: (b: B) => C",
      "): C;",
      "function pipe(value: unknown, ...fns: Function[]): unknown {",
      "  return fns.reduce((v, fn) => fn(v), value);",
      "}",
    ],
    distractors: [
      "function pipe<T>(v: T, ...fns: ((v: T) => T)[]): T;",
      "  return fns.reduceRight((v, fn) => fn(v), value);",
    ],
    hint: "pipe needs separate type parameters (A, B, C) per step — not a single T. pipe uses reduce (not reduceRight — that would be compose).",
    concept: "pipe-overloads",
    difficulty: 4,
  },

  {
    id: "L14-P3",
    title: "TypedEventEmitter",
    description: "Arrange the lines into a type-safe Event Emitter.",
    correctOrder: [
      "class TypedEmitter<Events extends Record<string, unknown>> {",
      "  private listeners = new Map<string, Set<Function>>();",
      "",
      "  on<K extends keyof Events & string>(",
      "    event: K,",
      "    handler: (data: Events[K]) => void",
      "  ): void {",
      "    if (!this.listeners.has(event)) {",
      "      this.listeners.set(event, new Set());",
      "    }",
      "    this.listeners.get(event)!.add(handler);",
      "  }",
      "",
      "  emit<K extends keyof Events & string>(event: K, data: Events[K]): void {",
      "    this.listeners.get(event)?.forEach(h => h(data));",
      "  }",
      "}",
    ],
    distractors: [
      "  on(event: string, handler: Function): void {",
      "  emit(event: string, data: unknown): void {",
    ],
    hint: "The generic version uses K extends keyof Events (not plain string) and Events[K] (not unknown) for type-safe event payloads.",
    concept: "typed-event-emitter",
    difficulty: 4,
  },

  {
    id: "L14-P4",
    title: "DI Container with Token<T>",
    description: "Arrange the lines into a type-safe DI Container with Phantom Types.",
    correctOrder: [
      "class Token<T> {",
      "  constructor(public readonly name: string) {}",
      "}",
      "",
      "class Container {",
      "  private bindings = new Map<Token<unknown>, () => unknown>();",
      "",
      "  bind<T>(token: Token<T>, factory: () => T): void {",
      "    this.bindings.set(token, factory);",
      "  }",
      "",
      "  resolve<T>(token: Token<T>): T {",
      "    const factory = this.bindings.get(token);",
      "    if (!factory) throw new Error(`No binding: ${token.name}`);",
      "    return factory() as T;",
      "  }",
      "}",
    ],
    distractors: [
      "  bind(key: string, factory: () => unknown): void {",
      "  resolve(key: string): unknown {",
    ],
    hint: "Token<T> is the type-safe key — not a plain string. bind/resolve use Token<T> instead of string for automatic type inference.",
    concept: "di-container-phantom-types",
    difficulty: 4,
  },
];