/**
 * Lesson 14 — Tracing Exercises: Generic Patterns
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  {
    id: "14-builder-type-growth",
    title: "Builder Type Growth via Intersection",
    description: "Trace how the builder type grows with each set() call.",
    code: [
      "class Builder<T extends Record<string, unknown> = {}> {",
      "  constructor(private data: T = {} as T) {}",
      "  set<K extends string, V>(key: K, value: V): Builder<T & Record<K, V>> {",
      "    return new Builder({ ...this.data, [key]: value } as T & Record<K, V>);",
      "  }",
      "  build(): T { return { ...this.data }; }",
      "}",
      "",
      "const b1 = new Builder();",
      "const b2 = b1.set('name', 'Max');",
      "const b3 = b2.set('age', 30);",
      "const result = b3.build();",
    ],
    steps: [
      {
        lineIndex: 8,
        question: "What type does b1 have?",
        expectedAnswer: "Builder<{}>",
        variables: { "T": "{}", "b1": "Builder<{}>" },
        explanation: "Without a type argument the builder uses the default {} — an empty object.",
      },
      {
        lineIndex: 9,
        question: "What type does b2 have after set('name', 'Max')?",
        expectedAnswer: "Builder<{} & Record<'name', string>> = Builder<{ name: string }>",
        variables: { "K": "'name'", "V": "string", "T": "{} & Record<'name', string>" },
        explanation: "set() returns Builder<T & Record<K, V>>. The intersection extends the type with the 'name' field.",
      },
      {
        lineIndex: 10,
        question: "What type does b3 have after set('age', 30)?",
        expectedAnswer: "Builder<{ name: string } & Record<'age', number>> = Builder<{ name: string; age: number }>",
        variables: { "K": "'age'", "V": "number", "T": "{ name: string } & Record<'age', number>" },
        explanation: "Another intersection: the existing type is extended with 'age: number'.",
      },
      {
        lineIndex: 11,
        question: "What type does result have after build()?",
        expectedAnswer: "{ name: string; age: number }",
        variables: { "result": "{ name: 'Max', age: 30 } (type: { name: string; age: number })" },
        explanation: "build() returns T — all accumulated intersections are now a single object type.",
      },
    ],
    concept: "builder-type-growth",
    difficulty: 3,
  },

  {
    id: "14-pipe-type-chain",
    title: "pipe() Type Chain via Overloads",
    description: "Trace how pipe() transforms the type at each step.",
    code: [
      "function pipe<A, B>(v: A, f1: (a: A) => B): B;",
      "function pipe<A, B, C>(v: A, f1: (a: A) => B, f2: (b: B) => C): C;",
      "function pipe(value: unknown, ...fns: Function[]): unknown {",
      "  return fns.reduce((v, fn) => fn(v), value);",
      "}",
      "",
      "const result = pipe(",
      "  'hello world',",
      "  (s) => s.split(' '),",
      "  (arr) => arr.length,",
      ");",
    ],
    steps: [
      {
        lineIndex: 7,
        question: "What is A (the input type)?",
        expectedAnswer: "A = string",
        variables: { "A": "string", "value": "'hello world'" },
        explanation: "TypeScript infers A = string from the first argument 'hello world'.",
      },
      {
        lineIndex: 8,
        question: "What is B after the first function step?",
        expectedAnswer: "B = string[]",
        variables: { "A": "string", "B": "string[]", "f1": "(s: string) => string[]" },
        explanation: "s.split(' ') returns string[], so B = string[].",
      },
      {
        lineIndex: 9,
        question: "What is C after the second step? Which overload applies?",
        expectedAnswer: "C = number, Overload: pipe<string, string[], number>",
        variables: { "B": "string[]", "C": "number", "f2": "(arr: string[]) => number" },
        explanation: "arr.length returns number. The second overload pipe<A,B,C> applies because 2 functions were passed.",
      },
      {
        lineIndex: 6,
        question: "What type does result have?",
        expectedAnswer: "number (value: 2)",
        variables: { "result": "2 (type: number)" },
        explanation: "pipe returns C = number. 'hello world'.split(' ') = ['hello','world'], .length = 2.",
      },
    ],
    concept: "pipe-type-chain",
    difficulty: 3,
  },

  {
    id: "14-conditional-type-resolution",
    title: "Conditional Type Resolution Order",
    description: "Trace how TypeScript resolves conditional types step by step.",
    code: [
      "type Format<T> =",
      "  T extends string ? 'text' :",
      "  T extends number ? 'numeric' :",
      "  T extends boolean ? 'flag' :",
      "  'unknown';",
      "",
      "type A = Format<string>;",
      "type B = Format<42>;",
      "type C = Format<true>;",
      "type D = Format<string | number>;",
      "type E = Format<never>;",
    ],
    steps: [
      {
        lineIndex: 6,
        question: "What is Format<string>?",
        expectedAnswer: "'text'",
        variables: { "T": "string", "A": "'text'" },
        explanation: "string extends string is true — first branch applies: 'text'.",
      },
      {
        lineIndex: 7,
        question: "What is Format<42>?",
        expectedAnswer: "'numeric'",
        variables: { "T": "42", "B": "'numeric'" },
        explanation: "42 extends string is false, 42 extends number is true — second branch: 'numeric'.",
      },
      {
        lineIndex: 9,
        question: "What is Format<string | number>? (Note: Distributive!)",
        expectedAnswer: "'text' | 'numeric'",
        variables: { "T": "string | number", "D": "'text' | 'numeric'" },
        explanation: "Conditional types DISTRIBUTE over unions: Format<string> | Format<number> = 'text' | 'numeric'.",
      },
      {
        lineIndex: 10,
        question: "What is Format<never>?",
        expectedAnswer: "never",
        variables: { "T": "never", "E": "never" },
        explanation: "never is the empty union. Distribution over an empty union = never. This is an important special rule!",
      },
    ],
    concept: "conditional-type-distribution",
    difficulty: 4,
  },

  {
    id: "14-repository-type-flow",
    title: "Repository Pattern — Type Flow in CRUD",
    description: "Trace how Omit and Partial change the type across different CRUD operations.",
    code: [
      "interface User { id: string; name: string; email: string; role: 'admin' | 'user'; }",
      "",
      "interface Repository<T extends { id: string }> {",
      "  create(data: Omit<T, 'id'>): T;",
      "  update(id: string, data: Partial<Omit<T, 'id'>>): T;",
      "  findById(id: string): T | undefined;",
      "}",
      "",
      "declare const repo: Repository<User>;",
      "const newUser = repo.create({ name: 'Max', email: 'max@test.de', role: 'user' });",
      "const updated = repo.update('1', { email: 'new@test.de' });",
      "const found = repo.findById('1');",
    ],
    steps: [
      {
        lineIndex: 9,
        question: "What type does the parameter of create() have for Repository<User>?",
        expectedAnswer: "Omit<User, 'id'> = { name: string; email: string; role: 'admin' | 'user' }",
        variables: { "T": "User", "Omit<T, 'id'>": "{ name: string; email: string; role: 'admin' | 'user' }" },
        explanation: "Omit removes 'id' from User. The caller MUST provide name, email, and role, but CANNOT set an id.",
      },
      {
        lineIndex: 10,
        question: "What type does the data parameter of update() have?",
        expectedAnswer: "Partial<Omit<User, 'id'>> = { name?: string; email?: string; role?: 'admin' | 'user' }",
        variables: { "Partial<Omit<T, 'id'>>": "{ name?: string; email?: string; role?: 'admin' | 'user' }" },
        explanation: "First Omit (remove id), then Partial (all optional). Individual fields can be updated.",
      },
      {
        lineIndex: 10,
        question: "What type does updated have?",
        expectedAnswer: "User (complete User object)",
        variables: { "updated": "type: User — update returns the complete object" },
        explanation: "update() returns T = User — the complete object with all fields, not just the changed ones.",
      },
      {
        lineIndex: 11,
        question: "What type does found have?",
        expectedAnswer: "User | undefined",
        variables: { "found": "type: User | undefined — the user might not exist" },
        explanation: "findById can fail (no user with that id). undefined signals this case.",
      },
    ],
    concept: "repository-crud-types",
    difficulty: 2,
  },
];