/**
 * Lesson 20 — Completion Problems: Review Phase 2
 */
export interface CompletionProblem { id: string; title: string; description: string; template: string; solution: string; blanks: { placeholder: string; answer: string; hint: string }[]; concept: string; }

export const completionProblems: CompletionProblem[] = [
  { id: "20-cp-mapped", title: "Mapped Type (L16)", description: "Complete the Mapped Type.", template: "type MyPartial<T> = { [K in ______ T]______: T[K] };", solution: "type MyPartial<T> = { [K in keyof T]?: T[K] };", blanks: [{ placeholder: "______", answer: "keyof", hint: "Keys of T?" }, { placeholder: "______", answer: "?", hint: "Optional modifier?" }], concept: "Mapped Type Basics" },
  { id: "20-cp-conditional", title: "Conditional Type (L17)", description: "Complete the Promise extraction.", template: "type Unpack<T> = T extends Promise<______ U> ? U : T;", solution: "type Unpack<T> = T extends Promise<infer U> ? U : T;", blanks: [{ placeholder: "______", answer: "infer", hint: "Declare a type variable?" }], concept: "infer Pattern" },
  { id: "20-cp-template", title: "Template Literal (L18)", description: "Complete the event name.", template: "type EventName<K extends string> = `on${______<K>}`;", solution: "type EventName<K extends string> = `on${Capitalize<K>}`;", blanks: [{ placeholder: "______", answer: "Capitalize", hint: "First letter uppercase?" }], concept: "Template Literal + Capitalize" },
  { id: "20-cp-declare", title: "Declaration (L19)", description: "Complete the global augmentation.", template: "______ global { interface Window { version: string; } }\nexport {};", solution: "declare global { interface Window { version: string; } }\nexport {};", blanks: [{ placeholder: "______", answer: "declare", hint: "Keyword for external declaration?" }], concept: "Global Augmentation" },
  { id: "20-cp-discriminated", title: "Discriminated Union (L12)", description: "Complete the exhaustive check.", template: "type Shape = { kind: 'circle'; r: number } | { kind: 'rect'; w: number; h: number };\nfunction area(s: Shape): number {\n  switch (s.______) {\n    case 'circle': return Math.PI * s.r ** 2;\n    case 'rect': return s.w * s.h;\n  }\n}", solution: "type Shape = { kind: 'circle'; r: number } | { kind: 'rect'; w: number; h: number };\nfunction area(s: Shape): number {\n  switch (s.kind) {\n    case 'circle': return Math.PI * s.r ** 2;\n    case 'rect': return s.w * s.h;\n  }\n}", blanks: [{ placeholder: "______", answer: "kind", hint: "The discriminator field?" }], concept: "Discriminated Union" },
  { id: "20-cp-generic-constraint", title: "Generic Constraint (L13)", description: "Complete the constraint.", template: "function getLength<T ______ { length: number }>(x: T): number {\n  return x.length;\n}", solution: "function getLength<T extends { length: number }>(x: T): number {\n  return x.length;\n}", blanks: [{ placeholder: "______", answer: "extends", hint: "Keyword for type constraint?" }], concept: "Generic Constraints" },
];