/**
 * Lesson 20 — Debugging Challenges: Review Phase 2
 */
import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  { id: "L20-D1", title: "never in Value Instead of Key (L16)", buggyCode: "type RemoveStrings<T> = {\n  [K in keyof T]: T[K] extends string ? never : T[K];\n};\n// Properties remain with type never!", bugType: "logic-error", bugLine: 2, options: ["never in value makes the property unusable but doesn't remove it — as never in key needed", "extends string is wrong", "keyof T is wrong", "Conditional Type missing"], correctOption: 0, hints: ["never in value vs never in key — what is the difference?"], fixedCode: "type RemoveStrings<T> = {\n  [K in keyof T as T[K] extends string ? never : K]: T[K];\n};", explanation: "never in KEY Remapping removes the property. never as value leaves the property in existence.", concept: "never-key-vs-value", difficulty: 3 },
  { id: "L20-D2", title: "Distribution Surprises (L17)", buggyCode: "type ToArray<T> = T extends any ? T[] : never;\ntype Result = ToArray<string | number>;\n// Expected: (string | number)[]\n// Result: string[] | number[]", bugType: "logic-error", bugLine: 1, options: ["Distributive: each union member is processed individually. [T] extends [any] for non-distributive.", "extends any is wrong", "T[] is wrong", "never is wrong"], correctOption: 0, hints: ["What does distribution do with unions?"], fixedCode: "type ToArrayND<T> = [T] extends [any] ? T[] : never;\ntype Result = ToArrayND<string | number>;\n// (string | number)[]", explanation: "[T] extends [any] prevents distribution. The union is checked as a whole.", concept: "distributive-conditional", difficulty: 3 },
  { id: "L20-D3", title: "Augmentation Without export (L19)", buggyCode: "declare global {\n  interface Window { appVersion: string; }\n}\n// Doesn't work!", bugType: "logic-error", bugLine: 1, options: ["File is not a module — export {} at the end is missing", "declare global is wrong", "Window is read-only", "interface is wrong"], correctOption: 0, hints: ["Is the file a module or a script?"], fixedCode: "declare global {\n  interface Window { appVersion: string; }\n}\nexport {};", explanation: "declare global needs module context. export {} makes the file a module.", concept: "module-augmentation", difficulty: 2 },
  { id: "L20-D4", title: "Flatten Without Recursion (L17)", buggyCode: "type Flatten<T> = T extends (infer U)[] ? U : T;\ntype Result = Flatten<string[][]>; // string[] instead of string!", bugType: "logic-error", bugLine: 1, options: ["Without recursion only one level is unpacked — Flatten<U> instead of U", "infer is wrong", "(infer U)[] is wrong", "Conditional is wrong"], correctOption: 0, hints: ["What happens when U itself is an array?"], fixedCode: "type Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;", explanation: "Recursion: Flatten<U> calls itself until there are no more arrays.", concept: "recursive-types", difficulty: 2 },
  { id: "L20-D5", title: "DeepPartial Without Function-Guard (L16)", buggyCode: "type DeepPartial<T> = {\n  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];\n};\n// Functions break!", bugType: "logic-error", bugLine: 2, options: ["Functions are also object — Function-Check needed: T[K] extends Function ? T[K] : DeepPartial<T[K]>", "extends object is wrong", "Recursion is wrong", "? is wrong"], correctOption: 0, hints: ["Is Function a subtype of object?"], fixedCode: "type DeepPartial<T> = {\n  [K in keyof T]?: T[K] extends object\n    ? T[K] extends Function ? T[K] : DeepPartial<T[K]>\n    : T[K];\n};", explanation: "Function extends object is true. Without the guard, DeepPartial is applied to functions.", concept: "deep-recursive-guard", difficulty: 3 },
];