/**
 * Lesson 20 — Misconception Exercises: Review Phase 2
 */
export interface Misconception { id: string; title: string; code: string; commonBelief: string; reality: string; concept: string; difficulty: number; }

export const misconceptions: Misconception[] = [
  { id: "20-types-are-runtime", title: "TypeScript Types Exist at Runtime", code: `type User = { name: string; age: number };\nconst data = JSON.parse('{"name":"Max"}');\nif (data instanceof User) { ... } // Error!`, commonBelief: "You can use TypeScript types for runtime checks.", reality: "Types are COMPLETELY removed during compilation. For runtime checks you need typeof, instanceof (with classes), or validation libraries (Zod, Yup).", concept: "Type Erasure", difficulty: 2 },
  { id: "20-any-is-fine", title: "any Is Fine When You Need It Quickly", code: `function process(data: any) {\n  return data.name.toUpperCase(); // No error!\n}\nprocess(42); // Runtime: TypeError!`, commonBelief: "any is a quick solution you can fix later.", reality: "any disables ALL type checking. Errors are only discovered at runtime. unknown is the safe alternative — it forces a check before access.", concept: "any vs unknown", difficulty: 1 },
  { id: "20-generics-slow", title: "Generics Make Code Slower", code: `function identity<T>(x: T): T { return x; }\n// "Generic = Overhead?"`, commonBelief: "Generics add runtime overhead.", reality: "Generics only exist at compile time. In the generated JavaScript there is NO difference. identity<string>('hello') becomes identity('hello') — no overhead.", concept: "Generics = Zero-Cost", difficulty: 1 },
  { id: "20-mapped-runtime", title: "Mapped Types Generate Objects", code: `type Getters<T> = { [K in keyof T as \`get\${Capitalize<K>}\`]: () => T[K] };\n// "Now getName(), getAge() exist as functions"`, commonBelief: "Mapped types generate runtime code.", reality: "Mapped types describe the SHAPE of a type. They generate no code. The implementation (e.g. with an Object.keys loop) must be written separately.", concept: "Type-Level vs Runtime", difficulty: 2 },
  { id: "20-extends-equals", title: "extends Means Equality", code: `type Test = 'hello' extends string ? true : false; // true\n// But: string extends 'hello' → false!`, commonBelief: "T extends U checks whether T and U are equal.", reality: "extends checks a SUBTYPE relationship, not equality. 'hello' extends string (literal is a subtype of string). But string extends 'hello' is false (string is NOT a subtype of a literal). Asymmetric!", concept: "extends = Subtype", difficulty: 3 },
  { id: "20-interface-vs-type", title: "Interface and Type Are Interchangeable", code: `interface A { name: string; }\ntype B = { name: string; };\n// "A and B are identical"`, commonBelief: "interface and type are completely interchangeable.", reality: "Structurally they are compatible, but: interfaces support declaration merging (augmentation). Type aliases can be unions, tuples, and mapped types. For public APIs: interface. For internal types: type alias.", concept: "Interface vs Type Alias", difficulty: 2 },
  { id: "20-readonly-deep", title: "Readonly Makes Everything Deeply Immutable", code: `interface Config { db: { host: string } };\nconst cfg: Readonly<Config> = { db: { host: 'localhost' } };\ncfg.db.host = 'new'; // No error!`, commonBelief: "Readonly<T> makes nested objects readonly.", reality: "Readonly<T> is only one level deep. cfg.db is readonly, but cfg.db.host is not! For deep readonly you need DeepReadonly<T> — a recursive mapped type.", concept: "Shallow vs Deep Readonly", difficulty: 3 },
  { id: "20-never-empty", title: "never Is Like void or undefined", code: `type A = string & number; // never\nfunction fail(): never { throw new Error(); }`, commonBelief: "never is like void — it means 'return nothing'.", reality: "never is the type that has NO values — not even undefined. void means 'no return value', never means 'never occurs'. never is the empty union, the result of impossible types (string & number), and the return type of functions that never return.", concept: "never vs void", difficulty: 3 },
];