/**
 * Lesson 20 — Tracing Exercises: Review Phase 2
 */
import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  { id: "20-full-pipeline", title: "Mapped + Conditional + Template Literal Combined", description: "Trace how three concepts work together.", code: ["type EventMap<T> = {", "  [K in keyof T & string as `${K}Changed`]:", "    T[K] extends object ? { prev: T[K]; next: T[K] } : T[K];", "};", "", "interface User { name: string; settings: { theme: string } }", "type Events = EventMap<User>;"], steps: [{ lineIndex: 6, question: "What happens for K = 'name'?", expectedAnswer: "Key becomes 'nameChanged'. string extends object? No -> string", variables: { "K": "'name'", "Remapped": "'nameChanged'", "Value": "string" }, explanation: "Template Literal Key + Conditional Value: nameChanged: string." }, { lineIndex: 6, question: "What happens for K = 'settings'?", expectedAnswer: "Key becomes 'settingsChanged'. object extends object? Yes -> { prev: ..., next: ... }", variables: { "K": "'settings'", "Remapped": "'settingsChanged'", "Value": "{ prev: { theme: string }; next: { theme: string } }" }, explanation: "settings is an object -> the Conditional creates a prev/next wrapper." }, { lineIndex: 6, question: "What is the final result Events?", expectedAnswer: "{ nameChanged: string; settingsChanged: { prev: { theme: string }; next: { theme: string } } }", variables: { "Events": "{ nameChanged: string; settingsChanged: { prev: ...; next: ... } }" }, explanation: "All three concepts combined: Mapped iterates, Template Literal renames, Conditional transforms." }], concept: "triumvirate-combination", difficulty: 4 },
  { id: "20-type-narrowing-trace", title: "Type Narrowing in switch (L11-L12)", description: "Trace how TypeScript narrows the type in a switch.", code: ["type Action =", "  | { type: 'add'; item: string }", "  | { type: 'remove'; id: number }", "  | { type: 'clear' };", "", "function handle(action: Action) {", "  switch (action.type) {", "    case 'add': return action.item;", "    case 'remove': return action.id;", "    case 'clear': return null;", "  }", "}"], steps: [{ lineIndex: 7, question: "What type does action have in the 'add' case?", expectedAnswer: "{ type: 'add'; item: string }", variables: { "action": "{ type: 'add'; item: string }" }, explanation: "TypeScript narrows to the union member with type: 'add'. item is now string." }, { lineIndex: 8, question: "What type does action have in the 'remove' case?", expectedAnswer: "{ type: 'remove'; id: number }", variables: { "action": "{ type: 'remove'; id: number }" }, explanation: "Narrowing to type: 'remove'. id is now number." }, { lineIndex: 9, question: "What type does action have in the 'clear' case?", expectedAnswer: "{ type: 'clear' }", variables: { "action": "{ type: 'clear' }" }, explanation: "Only one member remaining. No properties other than type." }], concept: "discriminated-union-narrowing", difficulty: 2 },
  { id: "20-generic-constraint-trace", title: "Generic Constraint Flow (L13-L14)", description: "Trace how constraints influence the inferred type.", code: ["function merge<T extends Record<string, unknown>>(a: T, b: Partial<T>): T {", "  return { ...a, ...b };", "}", "", "const result = merge(", "  { name: 'Max', age: 30, active: true },", "  { age: 31 },", ");"], steps: [{ lineIndex: 4, question: "What is T?", expectedAnswer: "{ name: string; age: number; active: boolean } — the FULL type, not Record<string, unknown>", variables: { "T": "{ name: string; age: number; active: boolean }" }, explanation: "T retains the full type of the first argument. The constraint is only the minimum requirement." }, { lineIndex: 6, question: "What does Partial<T> allow in the second argument?", expectedAnswer: "{ name?: string; age?: number; active?: boolean } — all optional", variables: { "Partial<T>": "{ name?: string; age?: number; active?: boolean }" }, explanation: "Partial makes all properties of T optional. Only changed fields need to be specified." }, { lineIndex: 4, question: "What type does result have?", expectedAnswer: "{ name: string; age: number; active: boolean } — T, not Partial<T>!", variables: { "result": "{ name: 'Max', age: 31, active: true } (type: T)" }, explanation: "merge returns T — the full, non-partial type. Runtime: age is 31 (overridden)." }], concept: "generic-constraint-inference", difficulty: 3 },
  { id: "20-infer-chain", title: "Multiple infer in One Pattern (L17)", description: "Trace how multiple infer variables are extracted simultaneously.", code: ["type FnInfo<T> = T extends (a: infer A, b: infer B) => infer R", "  ? { params: [A, B]; ret: R }", "  : never;", "", "type Info = FnInfo<(name: string, age: number) => boolean>;"], steps: [{ lineIndex: 4, question: "What is extracted for A?", expectedAnswer: "A = string (first parameter)", variables: { "A": "string" }, explanation: "infer A is at the position of the first parameter." }, { lineIndex: 4, question: "What is extracted for B and R?", expectedAnswer: "B = number, R = boolean", variables: { "B": "number", "R": "boolean" }, explanation: "Each infer extracts the type at its position." }, { lineIndex: 4, question: "What is Info?", expectedAnswer: "{ params: [string, number]; ret: boolean }", variables: { "Info": "{ params: [string, number]; ret: boolean }" }, explanation: "All infer variables are substituted into the result." }], concept: "multi-infer", difficulty: 3 },
];