/**
 * Lesson 10 — Tracing Exercises: Review Challenge
 *
 * 4 integrated tracing exercises combining concepts from all lessons.
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  {
    id: "10-full-pipeline",
    title: "Complete Type Pipeline: unknown -> Type Guard -> Type-Safe",
    description: "Trace how unknown data becomes type-safe through Type Guards.",
    code: [
      "interface Product { name: string; price: number; }",
      "",
      "function isProduct(data: unknown): data is Product {",
      "  return typeof data === 'object' && data !== null && 'name' in data && 'price' in data;",
      "}",
      "",
      "const raw: unknown = JSON.parse('{\"name\": \"Laptop\", \"price\": 999}');",
      "// raw has type: unknown",
      "",
      "if (isProduct(raw)) {",
      "  console.log(`${raw.name}: ${raw.price} EUR`);",
      "  // raw has type: Product",
      "}",
    ],
    steps: [
      {
        lineIndex: 6,
        question: "What type does raw have after JSON.parse? (L02)",
        expectedAnswer: "unknown — JSON.parse returns any, but we annotate unknown",
        variables: { "raw": "(Type: unknown)" },
        explanation: "JSON.parse technically returns any. With the unknown annotation, we enforce checking.",
      },
      {
        lineIndex: 9,
        question: "What type does raw have INSIDE the if-block? (L06)",
        expectedAnswer: "Product — the Type Guard narrowed the type",
        variables: { "raw": "(Type: Product)" },
        explanation: "isProduct returns 'data is Product'. When true, TypeScript narrows to Product.",
      },
      {
        lineIndex: 10,
        question: "What is the output?",
        expectedAnswer: "'Laptop: 999 EUR'",
        variables: {},
        explanation: "raw.name and raw.price are now type-safely accessible.",
      },
    ],
    concept: "unknown -> Type Guard -> type-safe (L02+L06)",
    difficulty: 2,
  },

  {
    id: "10-widening-chain",
    title: "Widening Chain: const, let, as const, satisfies",
    description: "Trace how different declarations affect the type.",
    code: [
      "const a = 'hello';",
      "let b = 'hello';",
      "const c = 'hello' as const;",
      "let d = 'hello' as const;",
      "",
      "const obj1 = { method: 'GET' };",
      "const obj2 = { method: 'GET' } as const;",
      "",
      "type Method = 'GET' | 'POST';",
      "const obj3 = { method: 'GET' } satisfies { method: Method };",
    ],
    steps: [
      {
        lineIndex: 0,
        question: "What type does a have? (L03/L09)",
        expectedAnswer: "'hello' (Literal Type — const with Primitive)",
        variables: { "a": "(Type: 'hello')" },
        explanation: "const with a Primitive infers the Literal Type.",
      },
      {
        lineIndex: 1,
        question: "What type does b have?",
        expectedAnswer: "string (Widening — let can be reassigned)",
        variables: { "a": "'hello'", "b": "(Type: string)" },
        explanation: "let widened to string because the value could be changed later.",
      },
      {
        lineIndex: 3,
        question: "What type does d have?",
        expectedAnswer: "'hello' (as const prevents widening even with let)",
        variables: { "d": "(Type: 'hello')" },
        explanation: "as const enforces the Literal Type — even with let.",
      },
      {
        lineIndex: 5,
        question: "What type does obj1.method have?",
        expectedAnswer: "string (Property Widening with Objects)",
        variables: { "obj1.method": "(Type: string)" },
        explanation: "Object properties are widened — even with const. The object is const, its properties are not.",
      },
      {
        lineIndex: 6,
        question: "What type does obj2.method have?",
        expectedAnswer: "'GET' (as const preserves Literal Type)",
        variables: { "obj2.method": "(Type: 'GET')" },
        explanation: "as const makes everything readonly AND preserves Literal Types.",
      },
    ],
    concept: "widening-chain (L03+L09)",
    difficulty: 3,
  },

  {
    id: "10-discriminated-union-flow",
    title: "Discriminated Union Narrowing Flow",
    description: "Trace how the type changes through a switch expression.",
    code: [
      "type Action =",
      "  | { type: 'add'; item: string }",
      "  | { type: 'remove'; index: number }",
      "  | { type: 'clear' };",
      "",
      "function reducer(items: string[], action: Action): string[] {",
      "  switch (action.type) {",
      "    case 'add': return [...items, action.item];",
      "    case 'remove': return items.filter((_, i) => i !== action.index);",
      "    case 'clear': return [];",
      "    default: const _: never = action; return _;",
      "  }",
      "}",
      "",
      "let state = ['A', 'B', 'C'];",
      "state = reducer(state, { type: 'add', item: 'D' });",
      "state = reducer(state, { type: 'remove', index: 1 });",
    ],
    steps: [
      {
        lineIndex: 7,
        question: "What type does action have in case 'add'? Which properties are accessible?",
        expectedAnswer: "{ type: 'add'; item: string } — action.item is accessible",
        variables: { "action": "(Type: { type: 'add'; item: string })" },
        explanation: "switch narrows to the member with type: 'add'. action.item is now safe.",
      },
      {
        lineIndex: 15,
        question: "What is state after reducer(state, { type: 'add', item: 'D' })?",
        expectedAnswer: "['A', 'B', 'C', 'D']",
        variables: { "state": "['A', 'B', 'C', 'D']" },
        explanation: "case 'add' appends item 'D' to the end.",
      },
      {
        lineIndex: 16,
        question: "What is state after reducer(state, { type: 'remove', index: 1 })?",
        expectedAnswer: "['A', 'C', 'D'] — Index 1 ('B') was removed",
        variables: { "state": "['A', 'C', 'D']" },
        explanation: "case 'remove' filters out index 1. 'B' is removed.",
      },
    ],
    concept: "discriminated-union-reducer (L07)",
    difficulty: 3,
  },

  {
    id: "10-intersection-extends-flow",
    title: "Interface extends vs Intersection — Type Composition",
    description: "Trace how extends and & compose types.",
    code: [
      "interface Base { id: string; createdAt: Date; }",
      "interface User extends Base { name: string; email: string; }",
      "type AdminMixin = { permissions: string[]; isSuperAdmin: boolean; };",
      "type Admin = User & AdminMixin;",
      "",
      "const admin: Admin = {",
      "  id: '1', createdAt: new Date(),",
      "  name: 'Max', email: 'max@admin.de',",
      "  permissions: ['read', 'write', 'delete'],",
      "  isSuperAdmin: true,",
      "};",
    ],
    steps: [
      {
        lineIndex: 0,
        question: "What properties does Base have?",
        expectedAnswer: "id: string, createdAt: Date",
        variables: { "Base": "{ id: string; createdAt: Date }" },
        explanation: "Base defines the base properties.",
      },
      {
        lineIndex: 1,
        question: "What properties does User have? (L08: extends)",
        expectedAnswer: "id, createdAt (inherited) + name, email (own) = 4 properties",
        variables: { "User": "{ id: string; createdAt: Date; name: string; email: string }" },
        explanation: "extends inherits all properties from Base and adds name + email.",
      },
      {
        lineIndex: 3,
        question: "What properties does Admin have? (L07: &)",
        expectedAnswer: "All 4 from User + permissions + isSuperAdmin = 6 properties",
        variables: { "Admin": "User & AdminMixin — all 6 properties" },
        explanation: "Intersection combines all properties from User and AdminMixin.",
      },
    ],
    concept: "extends-intersection-combined (L07+L08)",
    difficulty: 2,
  },
];