/**
 * Lesson 16 — Tracing Exercises: Mapped Types
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  {
    id: "16-mapped-type-iteration",
    title: "Mapped Type Iteration over Keys",
    description: "Trace how a mapped type iterates over keys step by step.",
    code: [
      "interface User {",
      "  id: number;",
      "  name: string;",
      "  email: string;",
      "}",
      "",
      "type Nullable<T> = { [K in keyof T]: T[K] | null };",
      "",
      "type NullableUser = Nullable<User>;",
    ],
    steps: [
      {
        lineIndex: 6,
        question: "What is keyof User?",
        expectedAnswer: "'id' | 'name' | 'email'",
        variables: { "keyof User": "'id' | 'name' | 'email'" },
        explanation: "keyof returns the union of all property names.",
      },
      {
        lineIndex: 8,
        question: "What happens for K = 'id'?",
        expectedAnswer: "id: number | null",
        variables: { "K": "'id'", "T[K]": "number", "T[K] | null": "number | null" },
        explanation: "For K='id', T[K] = User['id'] = number. | null is added.",
      },
      {
        lineIndex: 8,
        question: "What happens for K = 'name'?",
        expectedAnswer: "name: string | null",
        variables: { "K": "'name'", "T[K]": "string", "T[K] | null": "string | null" },
        explanation: "For K='name', T[K] = string. | null is added.",
      },
      {
        lineIndex: 8,
        question: "What is the complete result NullableUser?",
        expectedAnswer: "{ id: number | null; name: string | null; email: string | null; }",
        variables: { "NullableUser": "{ id: number | null; name: string | null; email: string | null; }" },
        explanation: "The mapped type iterated over all 3 keys and added | null to each.",
      },
    ],
    concept: "mapped-type-iteration",
    difficulty: 1,
  },
  {
    id: "16-key-remapping-flow",
    title: "Key Remapping with Filtering",
    description: "Trace how key remapping renames and filters keys.",
    code: [
      "type StringKeysOnly<T> = {",
      "  [K in keyof T as T[K] extends string ? K : never]: T[K];",
      "};",
      "",
      "interface Product {",
      "  id: number;",
      "  name: string;",
      "  price: number;",
      "  description: string;",
      "}",
      "",
      "type StringProps = StringKeysOnly<Product>;",
    ],
    steps: [
      {
        lineIndex: 11,
        question: "What happens for K = 'id'? (id: number)",
        expectedAnswer: "number extends string? No -> never -> key is removed",
        variables: { "K": "'id'", "T[K]": "number", "number extends string": "false", "Remapped Key": "never" },
        explanation: "number extends string is false. never as a key means the key is removed.",
      },
      {
        lineIndex: 11,
        question: "What happens for K = 'name'? (name: string)",
        expectedAnswer: "string extends string? Yes -> K stays -> name: string",
        variables: { "K": "'name'", "T[K]": "string", "string extends string": "true", "Remapped Key": "'name'" },
        explanation: "string extends string is true. K is kept.",
      },
      {
        lineIndex: 11,
        question: "What happens for K = 'price'? (price: number)",
        expectedAnswer: "number extends string? No -> never -> key is removed",
        variables: { "K": "'price'", "T[K]": "number", "Remapped Key": "never" },
        explanation: "Like 'id': number is not a string, the key is removed.",
      },
      {
        lineIndex: 11,
        question: "What is the final result StringProps?",
        expectedAnswer: "{ name: string; description: string; }",
        variables: { "StringProps": "{ name: string; description: string; }" },
        explanation: "Only name and description have a string type. id and price were filtered out.",
      },
    ],
    concept: "key-remapping-filtering",
    difficulty: 2,
  },
  {
    id: "16-modifier-effects",
    title: "Modifier Effects on Properties",
    description: "Trace how different modifiers change properties.",
    code: [
      "interface Original {",
      "  readonly host: string;",
      "  port?: number;",
      "  readonly debug?: boolean;",
      "}",
      "",
      "type A = { -readonly [K in keyof Original]: Original[K] };",
      "type B = { [K in keyof Original]-?: Original[K] };",
      "type C = { -readonly [K in keyof Original]-?: Original[K] };",
    ],
    steps: [
      {
        lineIndex: 6,
        question: "What is type A? (-readonly)",
        expectedAnswer: "{ host: string; port?: number; debug?: boolean; }",
        variables: { "A": "{ host: string; port?: number; debug?: boolean; }" },
        explanation: "-readonly removes readonly. host and debug lose readonly. Optional (?) is preserved.",
      },
      {
        lineIndex: 7,
        question: "What is type B? (-?)",
        expectedAnswer: "{ readonly host: string; port: number; readonly debug: boolean; }",
        variables: { "B": "{ readonly host: string; port: number; readonly debug: boolean; }" },
        explanation: "-? removes optional. port and debug become required. Readonly is preserved.",
      },
      {
        lineIndex: 8,
        question: "What is type C? (-readonly and -?)",
        expectedAnswer: "{ host: string; port: number; debug: boolean; }",
        variables: { "C": "{ host: string; port: number; debug: boolean; }" },
        explanation: "Both modifiers are removed. Everything is writable and required.",
      },
    ],
    concept: "modifier-combinations",
    difficulty: 2,
  },
  {
    id: "16-conditional-mapped",
    title: "Conditional inside Mapped Type",
    description: "Trace how conditionals apply differently per property.",
    code: [
      "type Serialize<T> = {",
      "  [K in keyof T]: T[K] extends Date ? string",
      "    : T[K] extends boolean ? 'true' | 'false'",
      "    : T[K];",
      "};",
      "",
      "interface Event {",
      "  name: string;",
      "  date: Date;",
      "  active: boolean;",
      "  count: number;",
      "}",
      "",
      "type SerializedEvent = Serialize<Event>;",
    ],
    steps: [
      {
        lineIndex: 13,
        question: "What becomes of 'name: string'?",
        expectedAnswer: "name: string (unchanged — no conditional matches)",
        variables: { "K": "'name'", "T[K]": "string", "Result": "string" },
        explanation: "string extends Date? No. string extends boolean? No. -> T[K] = string remains.",
      },
      {
        lineIndex: 13,
        question: "What becomes of 'date: Date'?",
        expectedAnswer: "date: string (Date extends Date -> string)",
        variables: { "K": "'date'", "T[K]": "Date", "Result": "string" },
        explanation: "Date extends Date is true -> first branch: string.",
      },
      {
        lineIndex: 13,
        question: "What becomes of 'active: boolean'?",
        expectedAnswer: "active: 'true' | 'false'",
        variables: { "K": "'active'", "T[K]": "boolean", "Result": "'true' | 'false'" },
        explanation: "boolean extends Date? No. boolean extends boolean? Yes -> 'true' | 'false'.",
      },
      {
        lineIndex: 13,
        question: "What is the complete result?",
        expectedAnswer: "{ name: string; date: string; active: 'true' | 'false'; count: number; }",
        variables: { "SerializedEvent": "{ name: string; date: string; active: 'true' | 'false'; count: number; }" },
        explanation: "Each property is individually transformed by the conditional type.",
      },
    ],
    concept: "conditional-per-property",
    difficulty: 3,
  },
];