/**
 * Lektion 17 — Completion Problems: Conditional Types
 */

export interface CompletionProblem { id: string; title: string; description: string; template: string; solution: string; blanks: { placeholder: string; answer: string; hint: string }[]; concept: string; }

export const completionProblems: CompletionProblem[] = [
  { id: "17-cp-isstring", title: "IsString<T>", description: "Vervollstaendige den Conditional Type.", template: `type IsString<T> = T ______ string ? ______ : ______;`, solution: `type IsString<T> = T extends string ? true : false;`, blanks: [{ placeholder: "______", answer: "extends", hint: "Welches Keyword prueft die Subtyp-Beziehung?" }, { placeholder: "______", answer: "true", hint: "Was wird zurueckgegeben wenn T ein string ist?" }, { placeholder: "______", answer: "false", hint: "Was wird zurueckgegeben wenn T KEIN string ist?" }], concept: "Conditional Type Grundsyntax" },
  { id: "17-cp-unpack", title: "UnpackPromise<T>", description: "Vervollstaendige die Promise-Extraktion.", template: `type UnpackPromise<T> = T extends ______<______ U> ? U : T;`, solution: `type UnpackPromise<T> = T extends Promise<infer U> ? U : T;`, blanks: [{ placeholder: "______", answer: "Promise", hint: "Welcher Typ soll entpackt werden?" }, { placeholder: "______", answer: "infer", hint: "Welches Keyword deklariert eine Typ-Variable?" }], concept: "infer mit Promise" },
  { id: "17-cp-returntype", title: "MyReturnType<T>", description: "Vervollstaendige die Return-Type-Extraktion.", template: `type MyReturnType<T> = T extends (...args: ______[]) => ______ R ? R : ______;`, solution: `type MyReturnType<T> = T extends (...args: any[]) => infer R ? R : never;`, blanks: [{ placeholder: "______", answer: "any", hint: "Welcher Typ akzeptiert alle Parameter?" }, { placeholder: "______", answer: "infer", hint: "Welches Keyword extrahiert den Rueckgabetyp?" }, { placeholder: "______", answer: "never", hint: "Was gibt man zurueck wenn T keine Funktion ist?" }], concept: "ReturnType Pattern" },
  { id: "17-cp-flatten", title: "Flatten<T>", description: "Vervollstaendige den rekursiven Flatten-Typ.", template: `type Flatten<T> = T extends (infer U)[] ? ______<U> : T;`, solution: `type Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;`, blanks: [{ placeholder: "______", answer: "Flatten", hint: "Welcher Typ ruft sich selbst auf (Rekursion)?" }], concept: "Rekursiver Conditional Type" },
  { id: "17-cp-isnever", title: "IsNever<T>", description: "Vervollstaendige die never-Erkennung.", template: `type IsNever<T> = ______<T> extends ______<never> ? true : false;`, solution: `type IsNever<T> = [T] extends [never] ? true : false;`, blanks: [{ placeholder: "______", answer: "[T]", hint: "Wie verhindert man Distribution? Packe T in ein..." }, { placeholder: "______", answer: "[never]", hint: "Gegen was wird gepreuft? Auch in ein Tuple gepackt." }], concept: "never-Erkennung" },
  { id: "17-cp-exclude", title: "MyExclude<T, U>", description: "Vervollstaendige Exclude (entfernt U-Member aus T).", template: `type MyExclude<T, U> = T extends U ? ______ : ______;`, solution: `type MyExclude<T, U> = T extends U ? never : T;`, blanks: [{ placeholder: "______", answer: "never", hint: "Was entfernt ein Member aus dem Union?" }, { placeholder: "______", answer: "T", hint: "Was behaelt ein Member im Union?" }], concept: "Distributive Exclude" },
];
