/**
 * Lektion 17 — Debugging Challenges: Conditional Types
 */

import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  { id: "L17-D1", title: "Conditional Type in Funktion nicht narrowbar", buggyCode: "function process<T extends string | number>(v: T): T extends string ? string : number {\n  if (typeof v === 'string') return v.toUpperCase(); // Error!\n  return 0; // Error!\n}", bugType: "type-error", bugLine: 2, options: ["TypeScript kann Conditional Types nicht durch if/else narrowen", "typeof ist falsch", "Der Conditional Type ist falsch", "extends string | number ist falsch"], correctOption: 0, hints: ["Kann TypeScript den Conditional Type T extends string ? ... durch Control Flow aufloesen?", "Nein — das ist eine bekannte Einschraenkung. Casts oder Overloads sind noetig."], fixedCode: "function process<T extends string | number>(v: T): T extends string ? string : number {\n  if (typeof v === 'string') return v.toUpperCase() as any;\n  return 0 as any;\n}\n// Alternativ: Function Overloads verwenden", explanation: "TypeScript kann Conditional Types nicht durch Runtime-Checks narrowen. as any oder Overloads sind die Workarounds.", concept: "conditional-narrowing-limitation", difficulty: 3 },
  { id: "L17-D2", title: "Distribution ueberrascht bei never", buggyCode: "type IsString<T> = T extends string ? 'yes' : 'no';\n\ntype A = IsString<never>;\n// Erwartet: 'no'\n// Ergebnis: never!", bugType: "logic-error", bugLine: 3, options: ["never ist der leere Union — Distribution ueber nichts ergibt never", "extends string ist falsch fuer never", "IsString braucht einen Default", "never ist ein Bug in TypeScript"], correctOption: 0, hints: ["Was ist never als Union betrachtet?", "Der leere Union. Distribution ueber 0 Member = 0 Ergebnisse = never."], fixedCode: "type IsString<T> = [T] extends [never]\n  ? 'never'\n  : T extends string ? 'yes' : 'no';", explanation: "never = leerer Union. Distributive Conditionals evaluieren fuer jedes Member — bei 0 Membern ist das Ergebnis never. Mit [T] extends [never] kann man never speziell abfangen.", concept: "never-distribution", difficulty: 4 },
  { id: "L17-D3", title: "Flatten ohne Rekursion", buggyCode: "type Flatten<T> = T extends (infer U)[] ? U : T;\n\ntype A = Flatten<string[][]>;\n// Erwartet: string\n// Ergebnis: string[] (nur eine Ebene!)", bugType: "logic-error", bugLine: 1, options: ["Ohne Rekursion wird nur eine Array-Ebene entpackt", "infer U ist falsch", "(infer U)[] matcht nicht", "Flatten braucht einen zweiten Parameter"], correctOption: 0, hints: ["Was passiert wenn U selbst ein Array ist?", "Ohne Rekursion bleibt string[][] bei string[] stehen. Flatten<U> wuerde weiter entpacken."], fixedCode: "type Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;", explanation: "Ohne Rekursion (Flatten<U>) wird nur die aeusserste Array-Ebene entpackt. Die Rekursion ist entscheidend fuer tiefes Entpacken.", concept: "recursive-flatten", difficulty: 2 },
  { id: "L17-D4", title: "infer ausserhalb von extends", buggyCode: "type GetInner<T> = infer U; // Error!\n\n// Oder:\ntype GetInner2<T> = T extends string\n  ? infer U // Error! infer im true-Branch\n  : never;", bugType: "type-error", bugLine: 1, options: ["infer darf nur innerhalb des extends-Patterns stehen, nicht anderswo", "infer braucht einen Default", "T muss ein Generic sein", "infer funktioniert nur mit Funktionen"], correctOption: 0, hints: ["Wo genau darf infer stehen?", "Nur im extends-Teil: T extends Pattern<infer U>. Nicht im true/false-Branch."], fixedCode: "type GetInner<T> = T extends Array<infer U> ? U : never;", explanation: "infer deklariert eine Typ-Variable die durch Pattern Matching im extends-Teil gefuellt wird. Es darf NUR dort stehen.", concept: "infer-placement", difficulty: 2 },
  { id: "L17-D5", title: "Distributive Conditional bei direktem Union", buggyCode: "// Erwartung: distributiv\ntype Result = string | number extends string ? 'yes' : 'no';\n// Ergebnis: 'no' (NICHT 'yes' | 'no'!)\n\n// Distribution passiert nur bei Typparametern!", bugType: "logic-error", bugLine: 2, options: ["Distribution passiert nur bei nackten Typparametern, nicht bei direkten Union-Typen", "extends string ist falsch", "string | number muesste in Klammern", "TypeScript-Bug"], correctOption: 0, hints: ["Wird string | number hier ueber einen Typparameter uebergeben?", "Nein — es steht direkt im extends. Distribution braucht einen nackten Typparameter T."], fixedCode: "type DistResult<T> = T extends string ? 'yes' : 'no';\ntype Result = DistResult<string | number>;\n// 'yes' | 'no' — jetzt distributiv!", explanation: "Distribution passiert NUR wenn T ein nackter Typparameter ist. Direkte Union-Typen in extends werden als Ganzes geprueft. string | number extends string ist false.", concept: "naked-type-parameter", difficulty: 3 },
];
