/**
 * Lektion 17 — Fehlkonzeption-Exercises: Conditional Types
 */

export interface Misconception { id: string; title: string; code: string; commonBelief: string; reality: string; concept: string; difficulty: number; }

export const misconceptions: Misconception[] = [
  { id: "17-runtime-conditional", title: "Conditional Types erzeugen Runtime-Code", code: `type Result<T> = T extends string ? string : number;\n// "Jetzt prueft TypeScript zur Laufzeit ob T ein string ist"`, commonBelief: "Conditional Types fuehren Runtime-Checks durch.", reality: "Conditional Types existieren NUR zur Compile-Zeit. Sie werden beim Compilieren komplett entfernt und erzeugen keinen JavaScript-Code.", concept: "Type-Level vs Runtime", difficulty: 1 },
  { id: "17-narrowing-conditional", title: "if/else narrowt Conditional Types", code: `function process<T>(v: T): T extends string ? string : number {\n  if (typeof v === 'string') return v.toUpperCase(); // Error!\n  return 0; // Error!\n}`, commonBelief: "TypeScript narrowt den Conditional Type durch Control Flow.", reality: "TypeScript kann Conditional Types NICHT durch if/else narrowen. Das ist eine bekannte Einschraenkung. Loesung: Overloads oder Casts.", concept: "Control Flow vs Conditional Types", difficulty: 3 },
  { id: "17-infer-everywhere", title: "infer funktioniert ueberall", code: `type Bad = infer T; // Error!\ntype AlsoBad<T> = T extends string ? infer U : never; // Error!`, commonBelief: "infer kann an jeder Position im Typsystem verwendet werden.", reality: "infer darf NUR innerhalb des extends-Teils eines Conditional Types stehen. Nirgendwo sonst. Es deklariert eine Variable die durch Pattern Matching gefuellt wird.", concept: "infer Einschraenkungen", difficulty: 2 },
  { id: "17-never-is-false", title: "never bei Distribution bedeutet false", code: `type IsString<T> = T extends string ? true : false;\ntype A = IsString<never>; // Erwartung: false\n// Realitaet: never`, commonBelief: "never extends string ergibt false.", reality: "never ist der leere Union. Distributive Conditional Types evaluieren fuer jedes Union-Member — bei 0 Membern ist das Ergebnis never, nicht true oder false.", concept: "never + Distribution", difficulty: 4 },
  { id: "17-distribution-always", title: "Conditional Types verteilen immer", code: `type A<T> = T extends any ? T[] : never;\ntype B = A<string | number>; // string[] | number[] (distributiv)\n\n// Aber:\ntype C = string | number extends any ? (string | number)[] : never;\n// (string | number)[] — NICHT distributiv!`, commonBelief: "Alle Conditional Types verteilen ueber Unions.", reality: "Distribution passiert NUR wenn T ein nackter Typparameter ist. Direkte Union-Typen (nicht ueber Typparameter) verteilen NICHT. Das ist der Unterschied.", concept: "Nackte Typparameter", difficulty: 3 },
  { id: "17-single-flatten", title: "Flatten entpackt nur eine Ebene", code: `type Flatten<T> = T extends (infer U)[] ? U : T;\n// Flatten<string[][]> = string[] (nicht string!)`, commonBelief: "Flatten entpackt Arrays beliebig tief.", reality: "Ohne Rekursion entpackt Flatten nur EINE Ebene: string[][] -> string[]. Fuer tiefes Entpacken braucht man: T extends (infer U)[] ? Flatten<U> : T — die Rekursion ist entscheidend!", concept: "Rekursion vs einmaliges Entpacken", difficulty: 2 },
  { id: "17-infer-position", title: "infer-Position ist egal", code: `type A<T> = T extends (infer U)[] ? U : never; // Element-Typ\ntype B<T> = T extends Array<infer U> ? U : never; // Auch Element-Typ\n// A und B machen das Gleiche — aber infer an anderer Stelle extrahiert anderes!`, commonBelief: "Es ist egal wo infer steht — es extrahiert immer dasselbe.", reality: "infer extrahiert GENAU den Typ an der Position wo es steht. infer im Return extrahiert den Return-Type, infer im Parameter extrahiert den Parameter-Typ. Die Position bestimmt was extrahiert wird.", concept: "infer Positionierung", difficulty: 2 },
  { id: "17-extends-equality", title: "extends bedeutet Gleichheit", code: `type Test = 'hello' extends string ? true : false; // true\n// Aber: string extends 'hello' ? true : false → false!`, commonBelief: "T extends U prueft ob T und U gleich sind.", reality: "extends prueft Subtyp-Beziehung, nicht Gleichheit. 'hello' extends string ist true (Literal ist Subtyp). Aber string extends 'hello' ist false (string ist NICHT Subtyp eines Literals). extends ist asymmetrisch!", concept: "extends = Subtyp, nicht Gleichheit", difficulty: 3 },
];
