/**
 * Lektion 17 — Tracing-Exercises: Conditional Types
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  { id: "17-distribution-step", title: "Distribution Schritt fuer Schritt", description: "Verfolge wie ein distributiver Conditional Type ueber einen Union verteilt.", code: ["type ToArray<T> = T extends any ? T[] : never;", "", "type Result = ToArray<string | number | boolean>;"], steps: [{ lineIndex: 2, question: "Schritt 1: Was passiert fuer string?", expectedAnswer: "string extends any = true -> string[]", variables: { "T": "string", "Result": "string[]" }, explanation: "Erstes Union-Member: string. string extends any ist true -> string[]." }, { lineIndex: 2, question: "Schritt 2: Was passiert fuer number?", expectedAnswer: "number extends any = true -> number[]", variables: { "T": "number", "Result": "number[]" }, explanation: "Zweites Union-Member: number. number extends any ist true -> number[]." }, { lineIndex: 2, question: "Schritt 3: Was passiert fuer boolean?", expectedAnswer: "boolean extends any = true -> boolean[]", variables: { "T": "boolean", "Result": "boolean[]" }, explanation: "Drittes Union-Member: boolean -> boolean[]." }, { lineIndex: 2, question: "Was ist das Endergebnis?", expectedAnswer: "string[] | number[] | boolean[]", variables: { "Result": "string[] | number[] | boolean[]" }, explanation: "Alle Einzelergebnisse werden zum Union zusammengefuegt." }], concept: "distribution-step-by-step", difficulty: 2 },
  { id: "17-infer-extraction", title: "infer extrahiert Typen aus Patterns", description: "Verfolge wie infer verschiedene Teile einer Funktion extrahiert.", code: ["type FnParts<T> =", "  T extends (a: infer A, b: infer B) => infer R", "  ? { first: A; second: B; ret: R }", "  : never;", "", "type Parts = FnParts<(name: string, age: number) => boolean>;"], steps: [{ lineIndex: 5, question: "Matcht das Pattern?", expectedAnswer: "Ja — (name: string, age: number) => boolean matcht (a: infer A, b: infer B) => infer R", variables: { "Match": "true" }, explanation: "Die Funktion hat 2 Parameter und einen Return-Type — passt auf das Pattern." }, { lineIndex: 5, question: "Was ist A?", expectedAnswer: "string (erster Parameter)", variables: { "A": "string" }, explanation: "infer A steht an der Position des ersten Parameters -> A = string." }, { lineIndex: 5, question: "Was ist B und R?", expectedAnswer: "B = number, R = boolean", variables: { "B": "number", "R": "boolean" }, explanation: "B = zweiter Parameter (number), R = Return-Type (boolean)." }, { lineIndex: 5, question: "Was ist Parts?", expectedAnswer: "{ first: string; second: number; ret: boolean }", variables: { "Parts": "{ first: string; second: number; ret: boolean }" }, explanation: "Alle infer-Variablen werden in das Ergebnis-Objekt eingesetzt." }], concept: "infer-multi-extraction", difficulty: 3 },
  { id: "17-recursive-flatten", title: "Rekursives Flatten Schritt fuer Schritt", description: "Verfolge wie Flatten rekursiv ein verschachteltes Array entpackt.", code: ["type Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;", "", "type Result = Flatten<number[][][]>;"], steps: [{ lineIndex: 2, question: "Schritt 1: Flatten<number[][][]>", expectedAnswer: "number[][][] extends (infer U)[]? Ja, U = number[][]. -> Flatten<number[][]>", variables: { "T": "number[][][]", "U": "number[][]" }, explanation: "Aeusserstes Array wird entpackt. U = number[][]." }, { lineIndex: 2, question: "Schritt 2: Flatten<number[][]>", expectedAnswer: "number[][] extends (infer U)[]? Ja, U = number[]. -> Flatten<number[]>", variables: { "T": "number[][]", "U": "number[]" }, explanation: "Naechste Ebene wird entpackt. U = number[]." }, { lineIndex: 2, question: "Schritt 3: Flatten<number[]>", expectedAnswer: "number[] extends (infer U)[]? Ja, U = number. -> Flatten<number>", variables: { "T": "number[]", "U": "number" }, explanation: "Letzte Array-Ebene wird entpackt. U = number." }, { lineIndex: 2, question: "Schritt 4: Flatten<number>", expectedAnswer: "number extends (infer U)[]? Nein -> T = number. Fertig!", variables: { "T": "number", "Result": "number" }, explanation: "number ist kein Array. Else-Branch: T = number. Rekursion terminiert." }], concept: "recursive-flatten-trace", difficulty: 3 },
  { id: "17-never-distribution", title: "never bei Distribution", description: "Verfolge was passiert wenn never auf einen distributiven Conditional trifft.", code: ["type IsString<T> = T extends string ? 'yes' : 'no';", "", "type A = IsString<string>;", "type B = IsString<number>;", "type C = IsString<string | number>;", "type D = IsString<never>;"], steps: [{ lineIndex: 2, question: "IsString<string>?", expectedAnswer: "'yes'", variables: { "A": "'yes'" }, explanation: "string extends string ist true -> 'yes'." }, { lineIndex: 4, question: "IsString<string | number>?", expectedAnswer: "'yes' | 'no' (distributiv)", variables: { "C": "'yes' | 'no'" }, explanation: "Distribution: IsString<string> | IsString<number> = 'yes' | 'no'." }, { lineIndex: 5, question: "IsString<never>?", expectedAnswer: "never (NICHT 'no'!)", variables: { "D": "never" }, explanation: "never = leerer Union. Distribution ueber 0 Member = 0 Ergebnisse = never." }], concept: "never-is-empty-union", difficulty: 4 },
];
