/**
 * Lektion 17 — Transfer Tasks: Conditional Types
 */

import type { TransferTask } from "../tools/transfer-engine.ts";

export const transferTasks: TransferTask[] = [
  { id: "17-smart-api-client", title: "Smart API Client mit Conditional Return Types", prerequisiteLessons: [16, 17], scenario: "Dein API-Client gibt immer `unknown` zurueck und erfordert manuelle Casts. Bei jedem Endpoint weiss man eigentlich genau welcher Typ zurueckkommt — aber der Client nutzt dieses Wissen nicht.", task: "Erstelle einen typsicheren API-Client:\n\n1. Definiere ein EndpointMap Interface das Pfade auf Response-Typen mappt\n2. Nutze Conditional Types um den Return-Type basierend auf dem Pfad zu bestimmen\n3. Verwende infer um Pfad-Parameter zu extrahieren (z.B. /users/:id)\n4. Demonstriere mit GET /users, GET /users/:id, POST /users", starterCode: "// TODO: EndpointMap, ApiClient mit Conditional Return Types", solutionCode: "interface EndpointMap {\n  '/users': User[];\n  '/users/:id': User;\n  '/products': Product[];\n}\n\ntype ResponseFor<Path extends string> =\n  Path extends keyof EndpointMap ? EndpointMap[Path] : unknown;\n\nasync function apiGet<P extends string>(path: P): Promise<ResponseFor<P>> {\n  const res = await fetch(path);\n  return res.json();\n}\n\n// const users = await apiGet('/users'); // User[]\n// const user = await apiGet('/users/:id'); // User", conceptsBridged: ["Conditional Types fuer Response-Ableitung", "infer fuer Pfad-Parameter", "Mapped Interface als Endpoint-Registry"], estimatedMinutes: 20, difficulty: 3 },
  { id: "17-type-safe-builder", title: "Typ-sichere Query Builder mit Conditional Types", prerequisiteLessons: [14, 17], scenario: "Du baust einen SQL-Query-Builder. Bisher gibt jede Methode `any` zurueck. WHERE-Bedingungen akzeptieren falsche Spalten, SELECT gibt die falschen Felder zurueck.", task: "Erstelle einen typsicheren Query Builder:\n\n1. select<K extends keyof T>(...keys: K[]) soll den Result-Typ auf Pick<T, K> einschraenken\n2. where<K extends keyof T>(key: K, op: '=' | '>' | '<', value: T[K]) soll typsicher sein\n3. Nutze Conditional Types fuer den Ergebnis-Typ basierend auf den select-Feldern\n4. Demonstriere mit einem User-Typ", starterCode: "// TODO: QueryBuilder<T, Selected> mit Conditional Types", solutionCode: "class QueryBuilder<T, Selected extends keyof T = keyof T> {\n  private _where: string[] = [];\n  private _select: Selected[] = [];\n\n  select<K extends keyof T>(...keys: K[]): QueryBuilder<T, K> {\n    return new QueryBuilder<T, K>();\n  }\n\n  where<K extends keyof T>(key: K, op: '=' | '>' | '<', value: T[K]): this {\n    return this;\n  }\n\n  execute(): Pick<T, Selected>[] {\n    return [] as Pick<T, Selected>[];\n  }\n}\n\ninterface User { id: number; name: string; email: string; age: number; }\nconst result = new QueryBuilder<User>()\n  .select('name', 'email')\n  .where('age', '>', 18)\n  .execute();\n// result: Pick<User, 'name' | 'email'>[] = { name: string; email: string }[]", conceptsBridged: ["Builder Pattern mit Typ-Transformation", "Conditional Types fuer Result-Typ-Einschraenkung", "Generic Constraints mit keyof"], estimatedMinutes: 25, difficulty: 4 },
];
