/**
 * Lesson 19 — Completion Problems: Modules & Declarations
 */
export interface CompletionProblem { id: string; title: string; description: string; template: string; solution: string; blanks: { placeholder: string; answer: string; hint: string }[]; concept: string; }

export const completionProblems: CompletionProblem[] = [
  { id: "19-cp-type-import", title: "Type-Only Import", description: "Complete the Type-Only Import.", template: `import ______ { User, Config } from './types';`, solution: `import type { User, Config } from './types';`, blanks: [{ placeholder: "______", answer: "type", hint: "Which keyword makes the import type-only?" }], concept: "Type-Only Import" },
  { id: "19-cp-declare-module", title: "Module Declaration", description: "Complete the declaration for an external library.", template: `______ module 'my-lib' {\n  export function init(config: Config): void;\n  export ______ Config { debug: boolean; }\n}`, solution: `declare module 'my-lib' {\n  export function init(config: Config): void;\n  export interface Config { debug: boolean; }\n}`, blanks: [{ placeholder: "______", answer: "declare", hint: "Which keyword introduces a declaration?" }, { placeholder: "______", answer: "interface", hint: "Which keyword defines an object type?" }], concept: "declare module" },
  { id: "19-cp-global-aug", title: "Global Augmentation", description: "Complete the global augmentation.", template: `declare ______ {\n  interface Window {\n    __APP_VERSION__: string;\n  }\n}\n\n______ {};`, solution: `declare global {\n  interface Window {\n    __APP_VERSION__: string;\n  }\n}\n\nexport {};`, blanks: [{ placeholder: "______", answer: "global", hint: "Which keyword extends the global scope?" }, { placeholder: "______", answer: "export", hint: "Which keyword makes the file a module?" }], concept: "Global Augmentation" },
  { id: "19-cp-barrel", title: "Barrel File", description: "Complete the re-exports.", template: `// index.ts\n______ { UserService } from './user-service';\n______ { ProductService } from './product-service';\nexport ______ { User, Product } from './types';`, solution: `// index.ts\nexport { UserService } from './user-service';\nexport { ProductService } from './product-service';\nexport type { User, Product } from './types';`, blanks: [{ placeholder: "______", answer: "export", hint: "Which keyword re-exports from another module?" }, { placeholder: "______", answer: "export", hint: "Same as above — re-export." }, { placeholder: "______", answer: "type", hint: "Which keyword marks the export as type-only?" }], concept: "Barrel File / Re-Exports" },
  { id: "19-cp-css-module", title: "CSS Module Declaration", description: "Complete the Wildcard Declaration.", template: `declare module '______.module.css' {\n  const classes: Record<string, ______>;\n  export ______ classes;\n}`, solution: `declare module '*.module.css' {\n  const classes: Record<string, string>;\n  export default classes;\n}`, blanks: [{ placeholder: "______", answer: "*", hint: "Which character represents 'any file name'?" }, { placeholder: "______", answer: "string", hint: "What type do CSS class names have?" }, { placeholder: "______", answer: "default", hint: "Which export keyword for the main export?" }], concept: "Wildcard Declaration" },
  { id: "19-cp-env", title: "Type-Safe Environment Variables", description: "Complete the ProcessEnv augmentation.", template: `declare global {\n  namespace ______ {\n    interface ______ {\n      NODE_ENV: 'development' | 'production';\n      DATABASE_URL: string;\n    }\n  }\n}\nexport {};`, solution: `declare global {\n  namespace NodeJS {\n    interface ProcessEnv {\n      NODE_ENV: 'development' | 'production';\n      DATABASE_URL: string;\n    }\n  }\n}\nexport {};`, blanks: [{ placeholder: "______", answer: "NodeJS", hint: "In which namespace does ProcessEnv live?" }, { placeholder: "______", answer: "ProcessEnv", hint: "What is the interface for environment variables called?" }], concept: "ProcessEnv Augmentation" },
];