/**
 * Lesson 19 — Debugging Challenges: Modules & Declarations
 */
import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  { id: "L19-D1", title: "Augmentation without export", buggyCode: "// env.d.ts\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv { API_KEY: string; }\n  }\n}\n// No export! Augmentation does not work.", bugType: "logic-error", bugLine: 1, options: ["File is not a module — declare global needs export {} at the end", "declare global is incorrect", "namespace NodeJS does not exist", "ProcessEnv is readonly"], correctOption: 0, hints: ["Is this file a module or a script?", "Without import/export it is treated as a script."], fixedCode: "// env.d.ts\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv { API_KEY: string; }\n  }\n}\nexport {};", explanation: "declare global only works in modules. Without export {} the file is a script and the augmentation is ignored.", concept: "module-vs-script", difficulty: 2 },
  { id: "L19-D2", title: "Implementation in .d.ts", buggyCode: "// math.d.ts\nexport function add(a: number, b: number): number {\n  return a + b; // Error!\n}", bugType: "type-error", bugLine: 2, options: [".d.ts files may not contain implementation — only declarations", "The function is incorrect", "export is not allowed in .d.ts", "number is incorrect"], correctOption: 0, hints: ["What is allowed in a .d.ts file?", "Only type declarations, no function bodies."], fixedCode: "// math.d.ts\nexport declare function add(a: number, b: number): number;", explanation: ".d.ts files contain only declarations. Function bodies and other implementation details are not allowed.", concept: "dts-no-implementation", difficulty: 1 },
  { id: "L19-D3", title: "Default Import without esModuleInterop", buggyCode: "// tsconfig: esModuleInterop: false\nimport lodash from 'lodash';\n// Error: Module has no default export", bugType: "type-error", bugLine: 2, options: ["CJS modules have no default export — esModuleInterop: true is needed", "lodash is not installed", "import syntax is incorrect", "lodash has no types"], correctOption: 0, hints: ["How does lodash export? module.exports = { ... }", "Without esModuleInterop there is no default export for CJS."], fixedCode: "// Option 1: esModuleInterop: true in tsconfig.json\nimport lodash from 'lodash';\n\n// Option 2: Namespace Import\nimport * as lodash from 'lodash';", explanation: "CJS module.exports is not an ES Module Default Export. esModuleInterop adds helpers that treat the CJS export as a default export.", concept: "esmoduleinterop", difficulty: 2 },
  { id: "L19-D4", title: "Missing @types", buggyCode: "import express from 'express';\n// Error: Could not find a declaration file for module 'express'\n// Try: npm i @types/express", bugType: "type-error", bugLine: 1, options: ["express has no built-in types — install @types/express", "express is not installed", "import syntax is incorrect", "TypeScript cannot import JavaScript"], correctOption: 0, hints: ["Does express have built-in .d.ts files?", "npm install @types/express installs community types."], fixedCode: "// Terminal: npm install @types/express\nimport express from 'express';\n// Now with full types!", explanation: "Many libraries (especially older ones) have no built-in types. @types packages from DefinitelyTyped fill this gap.", concept: "types-packages", difficulty: 1 },
  { id: "L19-D5", title: "Circular Import via Barrel File", buggyCode: "// types/index.ts (Barrel)\nexport * from './user';\nexport * from './product';\n\n// user.ts\nimport { Product } from './index'; // Circular!\n\n// product.ts\nimport { User } from './index'; // Circular!", bugType: "logic-error", bugLine: 6, options: ["Barrel file creates circular imports — use direct imports", "export * is incorrect", "The types are incorrect", "TypeScript does not support re-exports"], correctOption: 0, hints: ["What happens when user.ts imports from index.ts and index.ts imports from user.ts?", "Circular imports: A imports B which imports A."], fixedCode: "// user.ts — import directly instead of via barrel\nimport { Product } from './product';\n\n// product.ts\nimport { User } from './user';", explanation: "Barrel files can create circular dependencies when modules import each other via the barrel. Solution: direct imports between modules.", concept: "circular-barrel-imports", difficulty: 3 },
];