/**
 * Lesson 19 — Misconception Exercises: Modules & Declarations
 */
export interface Misconception { id: string; title: string; code: string; commonBelief: string; reality: string; concept: string; difficulty: number; }

export const misconceptions: Misconception[] = [
  { id: "19-declare-creates-code", title: "declare generates JavaScript code", code: `declare const API_URL: string;\n// "Now API_URL exists in JavaScript"`, commonBelief: "declare creates variables in the generated JavaScript.", reality: "declare generates NO code. It only informs TypeScript about values that exist elsewhere (e.g. through a script tag or a global variable). When compiling, declare is completely removed.", concept: "declare = type information only", difficulty: 1 },
  { id: "19-dts-is-typescript", title: ".d.ts files contain TypeScript code", code: `// math.d.ts\nexport function add(a: number, b: number): number {\n  return a + b; // Error in .d.ts!\n}`, commonBelief: ".d.ts files are regular TypeScript files.", reality: ".d.ts files contain ONLY type declarations — no implementation. Function bodies, variable initializations, and other implementation details are not allowed. They describe the shape, not the logic.", concept: ".d.ts = declarations only", difficulty: 1 },
  { id: "19-default-export-best", title: "Default exports are better than named exports", code: `// Default Export\nexport default class UserService { ... }\n// Import: import MyService from './user-service'; // Any name possible!`, commonBelief: "Default exports are the preferred export type.", reality: "Named exports are better in most cases: The name is consistent, IDE autocompletion works better, refactoring is safer. Default exports allow arbitrary names when importing — this leads to inconsistencies.", concept: "Named vs Default Exports", difficulty: 2 },
  { id: "19-barrel-always-good", title: "Barrel files are always a good idea", code: `// index.ts (Barrel)\nexport * from './huge-module-a';\nexport * from './huge-module-b';\nexport * from './huge-module-c';\n// Imports EVERYTHING, even if only 1 function is needed`, commonBelief: "Barrel files always improve code organization.", reality: "Barrel files can impair tree-shaking and lead to larger bundles. The bundler must analyze all exports, even if only a small portion is imported. In performance-critical projects: prefer direct imports.", concept: "Barrel files and tree-shaking", difficulty: 3 },
  { id: "19-augmentation-without-module", title: "Augmentation works without export", code: `// env.d.ts (NO export/import!)\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv { API_KEY: string; }\n  }\n}\n// Doesn't work! The file is not a module.`, commonBelief: "declare global works in any file.", reality: "declare global only works in modules (files with import or export). Without export {} the file is treated as a script and the augmentation is ignored. The solution: `export {}` at the end.", concept: "Module vs Script Context", difficulty: 3 },
  { id: "19-types-override", title: "@types overrides built-in types", code: `npm install @types/react\n// "Now React has NEW types"`, commonBelief: "@types replaces a library's types completely.", reality: "@types SUPPLEMENTS missing types. When a library already has built-in types (.d.ts in the package), @types is usually not needed and can even cause conflicts. First check whether the library already ships its own types before installing @types.", concept: "@types vs built-in types", difficulty: 2 },
  { id: "19-namespace-vs-module", title: "Namespaces and modules are the same", code: `namespace MyLib { export function doSomething() {} }\n// vs\nexport function doSomething() {}`, commonBelief: "Namespaces are the TypeScript way to write modules.", reality: "Namespaces are an older TypeScript feature. In modern code, ES Modules (import/export) should be used. Namespaces are only relevant for special cases: global augmentation (declare namespace) and legacy code.", concept: "Namespaces vs ES Modules", difficulty: 2 },
  { id: "19-import-type-optional", title: "import type is optional and unnecessary", code: `import { User } from './types'; // Normal\nimport type { User } from './types'; // Type-Only\n// "Both do the same thing"`, commonBelief: "import type is just syntactic sugar with no effect.", reality: "import type has real effects: 1) It is completely removed when compiling (no JS import). 2) It prevents unwanted side effects. 3) It is compatible with isolatedModules. 4) It documents intent. For libraries with side effects, the difference can be important.", concept: "import type semantics", difficulty: 3 },
];