/**
 * Lesson 19 — Tracing Exercises: Modules & Declarations
 */
import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  { id: "19-module-resolution", title: "Module Resolution Step by Step", description: "Trace how TypeScript resolves a module.", code: ["import { UserService } from './services';", "", "// TypeScript looks for:", "// 1. ./services.ts", "// 2. ./services.tsx", "// 3. ./services/index.ts", "// 4. ./services/index.tsx"], steps: [{ lineIndex: 0, question: "What does TypeScript look for first?", expectedAnswer: "./services.ts (direct file with .ts extension)", variables: { "Step 1": "./services.ts" }, explanation: "TypeScript first tries the direct file with the .ts extension." }, { lineIndex: 0, question: "What if ./services.ts does not exist?", expectedAnswer: "./services/index.ts (directory with index.ts)", variables: { "Step 3": "./services/index.ts" }, explanation: "If the direct file is not found, TypeScript looks for index.ts in the directory." }], concept: "module-resolution-order", difficulty: 1 },
  { id: "19-interface-merging", title: "Interface Merging Across Files", description: "Trace how interface merging works.", code: ["// file-a.ts", "interface Config { name: string; }", "", "// file-b.ts (Augmentation)", "interface Config { version: string; debug: boolean; }", "", "// Result:", "const cfg: Config = { name: 'App', version: '1.0', debug: true };"], steps: [{ lineIndex: 1, question: "What does Config have after file-a.ts?", expectedAnswer: "{ name: string; }", variables: { "Config": "{ name: string; }" }, explanation: "First declaration: Config only has name." }, { lineIndex: 4, question: "What does Config have after file-b.ts?", expectedAnswer: "{ name: string; version: string; debug: boolean; }", variables: { "Config": "{ name: string; version: string; debug: boolean; }" }, explanation: "Interface merging: both declarations are combined." }, { lineIndex: 7, question: "Which properties must cfg have?", expectedAnswer: "All three: name, version, debug", variables: { "cfg": "{ name: 'App', version: '1.0', debug: true }" }, explanation: "The merged interface requires all properties from both declarations." }], concept: "interface-merging-trace", difficulty: 2 },
  { id: "19-type-import-erasure", title: "Type Import Erasure", description: "Trace what happens during compilation.", code: ["import { UserService } from './services';", "import type { User } from './types';", "", "const service = new UserService();", "const user: User = service.getUser('1');"], steps: [{ lineIndex: 0, question: "Does this import remain in the JavaScript?", expectedAnswer: "Yes — UserService is used as a value (new UserService())", variables: { "Import": "remains in JS" }, explanation: "UserService is used as a value (constructor call). The import is kept." }, { lineIndex: 1, question: "Does this import remain in the JavaScript?", expectedAnswer: "No — import type is completely removed during compilation", variables: { "Import": "gets removed" }, explanation: "import type imports are ALWAYS removed. User is only used as a type annotation." }, { lineIndex: 4, question: "What remains in the generated JavaScript?", expectedAnswer: "const user = service.getUser('1'); (without type annotation)", variables: { "JS Output": "const user = service.getUser('1');" }, explanation: "Type annotations are removed. Only the value code remains." }], concept: "type-erasure", difficulty: 2 },
  { id: "19-augmentation-flow", title: "Augmentation Order", description: "Trace how augmentation extends types.", code: ["// express has: interface Request { body: any; }", "", "// Our augmentation:", "declare module 'express' {", "  interface Request {", "    user?: { id: string; role: string };", "    requestId: string;", "  }", "}", "", "// Result: Request has body + user + requestId"], steps: [{ lineIndex: 0, question: "What does Request have before the augmentation?", expectedAnswer: "body: any (and other Express standard properties)", variables: { "Request": "{ body: any; params: ...; query: ...; ... }" }, explanation: "Express defines Request with standard properties." }, { lineIndex: 3, question: "What happens in the augmentation?", expectedAnswer: "Interface merging: user and requestId are added to Request", variables: { "Augmentation": "{ user?: ...; requestId: string; }" }, explanation: "The new properties are added through interface merging." }, { lineIndex: 10, question: "What does Request have after the augmentation?", expectedAnswer: "body + user + requestId (all together)", variables: { "Request": "{ body: any; user?: { id: string; role: string }; requestId: string; ... }" }, explanation: "The result is the union of all properties from the original and the augmentation." }], concept: "augmentation-merging", difficulty: 2 },
];