/**
 * Lektion 20 — Debugging Challenges: Review Phase 2
 */
import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  { id: "L20-D1", title: "never im Wert statt im Key (L16)", buggyCode: "type RemoveStrings<T> = {\n  [K in keyof T]: T[K] extends string ? never : T[K];\n};\n// Properties bleiben mit Typ never!", bugType: "logic-error", bugLine: 2, options: ["never im Wert macht die Property unbenutzbar, entfernt sie aber nicht — as never im Key noetig", "extends string ist falsch", "keyof T ist falsch", "Conditional Type fehlt"], correctOption: 0, hints: ["never im Wert vs never im Key — was ist der Unterschied?"], fixedCode: "type RemoveStrings<T> = {\n  [K in keyof T as T[K] extends string ? never : K]: T[K];\n};", explanation: "never im KEY Remapping entfernt die Property. never als Wert laesst die Property existieren.", concept: "never-key-vs-value", difficulty: 3 },
  { id: "L20-D2", title: "Distribution ueberrascht (L17)", buggyCode: "type ToArray<T> = T extends any ? T[] : never;\ntype Result = ToArray<string | number>;\n// Erwartet: (string | number)[]\n// Ergebnis: string[] | number[]", bugType: "logic-error", bugLine: 1, options: ["Distributiv: jedes Union-Member wird einzeln verarbeitet. [T] extends [any] fuer nicht-distributiv.", "extends any ist falsch", "T[] ist falsch", "never ist falsch"], correctOption: 0, hints: ["Was macht Distribution mit Unions?"], fixedCode: "type ToArrayND<T> = [T] extends [any] ? T[] : never;\ntype Result = ToArrayND<string | number>;\n// (string | number)[]", explanation: "[T] extends [any] verhindert Distribution. Der Union wird als Ganzes geprueft.", concept: "distributive-conditional", difficulty: 3 },
  { id: "L20-D3", title: "Augmentation ohne export (L19)", buggyCode: "declare global {\n  interface Window { appVersion: string; }\n}\n// Funktioniert nicht!", bugType: "logic-error", bugLine: 1, options: ["Datei ist kein Modul — export {} am Ende fehlt", "declare global ist falsch", "Window ist read-only", "interface ist falsch"], correctOption: 0, hints: ["Ist die Datei ein Modul oder ein Script?"], fixedCode: "declare global {\n  interface Window { appVersion: string; }\n}\nexport {};", explanation: "declare global braucht Modul-Kontext. export {} macht die Datei zum Modul.", concept: "module-augmentation", difficulty: 2 },
  { id: "L20-D4", title: "Flatten ohne Rekursion (L17)", buggyCode: "type Flatten<T> = T extends (infer U)[] ? U : T;\ntype Result = Flatten<string[][]>; // string[] statt string!", bugType: "logic-error", bugLine: 1, options: ["Ohne Rekursion wird nur eine Ebene entpackt — Flatten<U> statt U", "infer ist falsch", "(infer U)[] ist falsch", "Conditional ist falsch"], correctOption: 0, hints: ["Was passiert wenn U selbst ein Array ist?"], fixedCode: "type Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;", explanation: "Rekursion: Flatten<U> ruft sich selbst auf bis kein Array mehr da ist.", concept: "recursive-types", difficulty: 2 },
  { id: "L20-D5", title: "DeepPartial ohne Function-Guard (L16)", buggyCode: "type DeepPartial<T> = {\n  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];\n};\n// Funktionen werden kaputt!", bugType: "logic-error", bugLine: 2, options: ["Funktionen sind auch object — Function-Check noetig: T[K] extends Function ? T[K] : DeepPartial<T[K]>", "extends object ist falsch", "Rekursion ist falsch", "? ist falsch"], correctOption: 0, hints: ["Ist Function ein Subtyp von object?"], fixedCode: "type DeepPartial<T> = {\n  [K in keyof T]?: T[K] extends object\n    ? T[K] extends Function ? T[K] : DeepPartial<T[K]>\n    : T[K];\n};", explanation: "Function extends object ist true. Ohne Guard wird DeepPartial auf Funktionen angewendet.", concept: "deep-recursive-guard", difficulty: 3 },
];
