/**
 * Lektion 20 — Fehlkonzeption-Exercises: Review Phase 2
 */
export interface Misconception { id: string; title: string; code: string; commonBelief: string; reality: string; concept: string; difficulty: number; }

export const misconceptions: Misconception[] = [
  { id: "20-types-are-runtime", title: "TypeScript-Typen existieren zur Laufzeit", code: `type User = { name: string; age: number };\nconst data = JSON.parse('{"name":"Max"}');\nif (data instanceof User) { ... } // Error!`, commonBelief: "Man kann TypeScript-Typen fuer Runtime-Checks verwenden.", reality: "Typen werden beim Compilieren KOMPLETT entfernt. Fuer Runtime-Checks braucht man typeof, instanceof (mit Klassen), oder Validation Libraries (Zod, Yup).", concept: "Type Erasure", difficulty: 2 },
  { id: "20-any-is-fine", title: "any ist OK wenn man es schnell braucht", code: `function process(data: any) {\n  return data.name.toUpperCase(); // Kein Fehler!\n}\nprocess(42); // Runtime: TypeError!`, commonBelief: "any ist eine schnelle Loesung die man spaeter fixen kann.", reality: "any deaktiviert ALLE Typ-Pruefungen. Fehler werden erst zur Laufzeit entdeckt. unknown ist die sichere Alternative — es erzwingt eine Pruefung vor dem Zugriff.", concept: "any vs unknown", difficulty: 1 },
  { id: "20-generics-slow", title: "Generics machen den Code langsamer", code: `function identity<T>(x: T): T { return x; }\n// "Generic = Overhead?"`, commonBelief: "Generics fuegen Runtime-Overhead hinzu.", reality: "Generics existieren nur zur Compile-Zeit. Im generierten JavaScript gibt es KEINEN Unterschied. identity<string>('hello') wird zu identity('hello') — kein Overhead.", concept: "Generics = Zero-Cost", difficulty: 1 },
  { id: "20-mapped-runtime", title: "Mapped Types erzeugen Objekte", code: `type Getters<T> = { [K in keyof T as \`get\${Capitalize<K>}\`]: () => T[K] };\n// "Jetzt existieren getName(), getAge() als Funktionen"`, commonBelief: "Mapped Types generieren Runtime-Code.", reality: "Mapped Types beschreiben die FORM eines Typs. Sie erzeugen keinen Code. Die Implementierung (z.B. mit Object.keys-Loop) muss separat geschrieben werden.", concept: "Type-Level vs Runtime", difficulty: 2 },
  { id: "20-extends-equals", title: "extends bedeutet Gleichheit", code: `type Test = 'hello' extends string ? true : false; // true\n// Aber: string extends 'hello' → false!`, commonBelief: "T extends U prueft ob T und U gleich sind.", reality: "extends prueft SUBTYP-Beziehung, nicht Gleichheit. 'hello' extends string (Literal ist Subtyp von string). Aber string extends 'hello' ist false (string ist KEIN Subtyp eines Literals). Asymmetrisch!", concept: "extends = Subtyp", difficulty: 3 },
  { id: "20-interface-vs-type", title: "Interface und Type sind austauschbar", code: `interface A { name: string; }\ntype B = { name: string; };\n// "A und B sind identisch"`, commonBelief: "interface und type sind komplett austauschbar.", reality: "Strukturell sind sie kompatibel, aber: Interfaces unterstuetzen Declaration Merging (Augmentation). Type Aliases koennen Unions, Tuples und Mapped Types sein. Fuer oeffentliche APIs: Interface. Fuer interne Typen: Type Alias.", concept: "Interface vs Type Alias", difficulty: 2 },
  { id: "20-readonly-deep", title: "Readonly macht alles tief unveraenderlich", code: `interface Config { db: { host: string } };\nconst cfg: Readonly<Config> = { db: { host: 'localhost' } };\ncfg.db.host = 'new'; // Kein Fehler!`, commonBelief: "Readonly<T> macht verschachtelte Objekte readonly.", reality: "Readonly<T> ist nur eine Ebene tief. cfg.db ist readonly, aber cfg.db.host nicht! Fuer tiefes Readonly braucht man DeepReadonly<T> — einen rekursiven Mapped Type.", concept: "Shallow vs Deep Readonly", difficulty: 3 },
  { id: "20-never-empty", title: "never ist wie void oder undefined", code: `type A = string & number; // never\nfunction fail(): never { throw new Error(); }`, commonBelief: "never ist wie void — es bedeutet 'nichts zurueckgeben'.", reality: "never ist der Typ der KEINE Werte hat — nicht einmal undefined. void bedeutet 'kein Rueckgabewert', never bedeutet 'kommt nie vor'. never ist der leere Union, das Ergebnis unmoeglicher Typen (string & number), und der Return-Type von Funktionen die nie zurueckkehren.", concept: "never vs void", difficulty: 3 },
];
