/**
 * Lektion 20 — Tracing-Exercises: Review Phase 2
 */
import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  { id: "20-full-pipeline", title: "Mapped + Conditional + Template Literal kombiniert", description: "Verfolge wie drei Konzepte zusammenwirken.", code: ["type EventMap<T> = {", "  [K in keyof T & string as `${K}Changed`]:", "    T[K] extends object ? { prev: T[K]; next: T[K] } : T[K];", "};", "", "interface User { name: string; settings: { theme: string } }", "type Events = EventMap<User>;"], steps: [{ lineIndex: 6, question: "Was passiert fuer K = 'name'?", expectedAnswer: "Key wird 'nameChanged'. string extends object? Nein -> string", variables: { "K": "'name'", "Remapped": "'nameChanged'", "Value": "string" }, explanation: "Template Literal Key + Conditional Value: nameChanged: string." }, { lineIndex: 6, question: "Was passiert fuer K = 'settings'?", expectedAnswer: "Key wird 'settingsChanged'. object extends object? Ja -> { prev: ..., next: ... }", variables: { "K": "'settings'", "Remapped": "'settingsChanged'", "Value": "{ prev: { theme: string }; next: { theme: string } }" }, explanation: "settings ist ein Objekt -> der Conditional erzeugt prev/next Wrapper." }, { lineIndex: 6, question: "Was ist das Endergebnis Events?", expectedAnswer: "{ nameChanged: string; settingsChanged: { prev: { theme: string }; next: { theme: string } } }", variables: { "Events": "{ nameChanged: string; settingsChanged: { prev: ...; next: ... } }" }, explanation: "Alle drei Konzepte zusammen: Mapped iteriert, Template Literal benennt um, Conditional transformiert." }], concept: "triumvirate-combination", difficulty: 4 },
  { id: "20-type-narrowing-trace", title: "Type Narrowing in switch (L11-L12)", description: "Verfolge wie TypeScript den Typ in einem switch verengt.", code: ["type Action =", "  | { type: 'add'; item: string }", "  | { type: 'remove'; id: number }", "  | { type: 'clear' };", "", "function handle(action: Action) {", "  switch (action.type) {", "    case 'add': return action.item;", "    case 'remove': return action.id;", "    case 'clear': return null;", "  }", "}"], steps: [{ lineIndex: 7, question: "Welchen Typ hat action im 'add'-Case?", expectedAnswer: "{ type: 'add'; item: string }", variables: { "action": "{ type: 'add'; item: string }" }, explanation: "TypeScript narrowt auf den Union-Member mit type: 'add'. item ist jetzt string." }, { lineIndex: 8, question: "Welchen Typ hat action im 'remove'-Case?", expectedAnswer: "{ type: 'remove'; id: number }", variables: { "action": "{ type: 'remove'; id: number }" }, explanation: "Narrowing auf type: 'remove'. id ist jetzt number." }, { lineIndex: 9, question: "Welchen Typ hat action im 'clear'-Case?", expectedAnswer: "{ type: 'clear' }", variables: { "action": "{ type: 'clear' }" }, explanation: "Nur noch ein Member uebrig. Keine Properties ausser type." }], concept: "discriminated-union-narrowing", difficulty: 2 },
  { id: "20-generic-constraint-trace", title: "Generic Constraint Flow (L13-L14)", description: "Verfolge wie Constraints den inferierten Typ beeinflussen.", code: ["function merge<T extends Record<string, unknown>>(a: T, b: Partial<T>): T {", "  return { ...a, ...b };", "}", "", "const result = merge(", "  { name: 'Max', age: 30, active: true },", "  { age: 31 },", ");"], steps: [{ lineIndex: 4, question: "Was ist T?", expectedAnswer: "{ name: string; age: number; active: boolean } — der VOLLE Typ, nicht Record<string, unknown>", variables: { "T": "{ name: string; age: number; active: boolean }" }, explanation: "T behaelt den vollen Typ des ersten Arguments. Das Constraint ist nur die Mindestanforderung." }, { lineIndex: 6, question: "Was erlaubt Partial<T> im zweiten Argument?", expectedAnswer: "{ name?: string; age?: number; active?: boolean } — alle optional", variables: { "Partial<T>": "{ name?: string; age?: number; active?: boolean }" }, explanation: "Partial macht alle Properties von T optional. Nur geaenderte Felder muessen angegeben werden." }, { lineIndex: 4, question: "Welchen Typ hat result?", expectedAnswer: "{ name: string; age: number; active: boolean } — T, nicht Partial<T>!", variables: { "result": "{ name: 'Max', age: 31, active: true } (Typ: T)" }, explanation: "merge gibt T zurueck — den vollen, nicht-partiellen Typ. Runtime: age ist 31 (ueberschrieben)." }], concept: "generic-constraint-inference", difficulty: 3 },
  { id: "20-infer-chain", title: "Mehrere infer in einem Pattern (L17)", description: "Verfolge wie mehrere infer-Variablen gleichzeitig extrahiert werden.", code: ["type FnInfo<T> = T extends (a: infer A, b: infer B) => infer R", "  ? { params: [A, B]; ret: R }", "  : never;", "", "type Info = FnInfo<(name: string, age: number) => boolean>;"], steps: [{ lineIndex: 4, question: "Was wird fuer A extrahiert?", expectedAnswer: "A = string (erster Parameter)", variables: { "A": "string" }, explanation: "infer A steht an der Position des ersten Parameters." }, { lineIndex: 4, question: "Was wird fuer B und R extrahiert?", expectedAnswer: "B = number, R = boolean", variables: { "B": "number", "R": "boolean" }, explanation: "Jedes infer extrahiert den Typ an seiner Position." }, { lineIndex: 4, question: "Was ist Info?", expectedAnswer: "{ params: [string, number]; ret: boolean }", variables: { "Info": "{ params: [string, number]; ret: boolean }" }, explanation: "Alle infer-Variablen werden in das Ergebnis eingesetzt." }], concept: "multi-infer", difficulty: 3 },
];
