/**
 * Lektion 20 — Transfer Tasks: Review Phase 2
 */
import type { TransferTask } from "../tools/transfer-engine.ts";

export const transferTasks: TransferTask[] = [
  { id: "20-fullstack-types", title: "Fullstack Type System: Shared Types zwischen Frontend und Backend", prerequisiteLessons: [13, 14, 15, 16, 17, 18, 19], scenario: "Dein Fullstack-Projekt hat separate Typ-Definitionen fuer Frontend (React) und Backend (Express). User-Typen existieren doppelt. Wenn das Backend eine Property hinzufuegt, vergisst das Frontend die Anpassung.", task: "Erstelle ein shared-types Paket:\n\n1. Definiere Entity-Basis-Typen (BaseEntity, User, Product, Order)\n2. Leite CreateDTO, UpdateDTO, ResponseDTO automatisch ab (Mapped Types)\n3. Generiere Event-Typen fuer WebSockets (Template Literals)\n4. Erstelle einen typsicheren API-Client mit Conditional Return Types\n5. Schreibe Declaration Files fuer Frontend/Backend-spezifische Erweiterungen", starterCode: "// TODO: Shared Types, DTOs, Events, ApiClient, Declarations", solutionCode: "// shared/entities.ts\ninterface BaseEntity { id: string; createdAt: Date; updatedAt: Date; }\ninterface User extends BaseEntity { name: string; email: string; role: 'admin' | 'user'; }\ninterface Product extends BaseEntity { name: string; price: number; }\n\n// shared/dto.ts\ntype CreateDTO<T extends BaseEntity> = Omit<T, keyof BaseEntity>;\ntype UpdateDTO<T extends BaseEntity> = Partial<Omit<T, keyof BaseEntity>>;\ntype ResponseDTO<T extends BaseEntity> = { [K in keyof T]: T[K] extends Date ? string : T[K] };\n\n// shared/events.ts\ntype EntityEvents<T extends BaseEntity> = {\n  [K in 'created' | 'updated' | 'deleted' as `${string & Uncapitalize<T['id'] extends string ? 'entity' : 'entity'>}:${K}`]: K extends 'deleted' ? { id: string } : ResponseDTO<T>;\n};\n\n// shared/api.ts\ninterface EndpointMap {\n  'GET /users': ResponseDTO<User>[];\n  'GET /users/:id': ResponseDTO<User>;\n  'POST /users': ResponseDTO<User>;\n}\ntype ApiResponse<E extends keyof EndpointMap> = EndpointMap[E];", conceptsBridged: ["Mapped Types fuer DTO-Generierung", "Template Literal Types fuer Event-Namen", "Conditional Types fuer API-Return-Types", "Declaration Files fuer Framework-spezifische Erweiterungen", "Shared Types zwischen Frontend und Backend"], estimatedMinutes: 30, difficulty: 5 },
  { id: "20-type-challenge", title: "Type Challenge: Baue einen typsicheren Form Builder", prerequisiteLessons: [14, 16, 17, 18], scenario: "Du hast 50 Formulare in deiner App. Jedes hat eigenen Boilerplate fuer Validierung, Fehlermeldungen und Formular-State. Du willst einen generischen FormBuilder der alles aus dem Typ ableitet.", task: "Erstelle einen typsicheren Form Builder:\n\n1. FormBuilder<T> mit register(field, rules), validate(), getErrors()\n2. Felder muessen gueltige Keys von T sein\n3. Regeln muessen zum Feld-Typ passen (string: minLength, number: min/max)\n4. getErrors() gibt FormErrors<T> zurueck\n5. Typ-sichere Default-Werte", starterCode: "// TODO: FormBuilder<T> mit Mapped Types fuer Rules und Errors", solutionCode: "type FieldRules<T> = T extends string\n  ? { required?: boolean; minLength?: number; maxLength?: number; pattern?: RegExp }\n  : T extends number\n  ? { required?: boolean; min?: number; max?: number }\n  : { required?: boolean };\n\ntype FormRules<T> = { [K in keyof T]?: FieldRules<T[K]> };\ntype FormErrors<T> = { [K in keyof T]?: string };\n\nclass FormBuilder<T extends Record<string, unknown>> {\n  private rules: FormRules<T> = {} as FormRules<T>;\n  private values: T;\n  constructor(defaults: T) { this.values = { ...defaults }; }\n  register<K extends keyof T>(field: K, rules: FieldRules<T[K]>): this {\n    (this.rules as any)[field] = rules;\n    return this;\n  }\n  validate(): FormErrors<T> {\n    const errors: FormErrors<T> = {};\n    for (const key of Object.keys(this.rules) as (keyof T)[]) {\n      const rule = this.rules[key] as any;\n      const value = this.values[key];\n      if (rule?.required && !value) (errors as any)[key] = 'Pflichtfeld';\n    }\n    return errors;\n  }\n}", conceptsBridged: ["Conditional Types fuer feld-typ-spezifische Regeln", "Mapped Types fuer FormRules und FormErrors", "Generische Klasse mit Builder-Pattern", "Type-Level-Entscheidungen fuer unterschiedliche Feld-Typen"], estimatedMinutes: 25, difficulty: 4 },
];
