/**
 * Lesson 18 — Completion Problems: Template Literal Types
 */
export interface CompletionProblem { id: string; title: string; description: string; template: string; solution: string; blanks: { placeholder: string; answer: string; hint: string }[]; concept: string; }

export const completionProblems: CompletionProblem[] = [
  { id: "18-cp-getter", title: "Generate Getter Name", description: "Complete the Template Literal Type.", template: "type GetterName<T extends string> = `______${______<T>}`;", solution: "type GetterName<T extends string> = `get${Capitalize<T>}`;", blanks: [{ placeholder: "______", answer: "get", hint: "Which prefix comes before the property name?" }, { placeholder: "______", answer: "Capitalize", hint: "Which utility capitalizes the first letter?" }], concept: "Template Literal + Capitalize" },
  { id: "18-cp-extract", title: "Extract Prefix", description: "Complete the string extraction.", template: "type ExtractPrefix<T extends string> = T extends `${______ P}_${string}` ? P : never;", solution: "type ExtractPrefix<T extends string> = T extends `${infer P}_${string}` ? P : never;", blanks: [{ placeholder: "______", answer: "infer", hint: "Which keyword declares a type variable in the pattern?" }], concept: "infer in Template Literal" },
  { id: "18-cp-split", title: "Split Type", description: "Complete the recursive split type.", template: "type Split<S extends string, D extends string> =\n  S extends `${infer H}${D}${infer T}` ? [H, ...______<T, D>] : [S];", solution: "type Split<S extends string, D extends string> =\n  S extends `${infer H}${D}${infer T}` ? [H, ...Split<T, D>] : [S];", blanks: [{ placeholder: "______", answer: "Split", hint: "Which type calls itself recursively?" }], concept: "Recursive Split" },
  { id: "18-cp-eventmap", title: "EventMap with Template Literals", description: "Complete the event map type.", template: "type EventMap<T> = {\n  [K in keyof T & string as `${K}______`]: {\n    previousValue: T[K]; newValue: T[K];\n  };\n};", solution: "type EventMap<T> = {\n  [K in keyof T & string as `${K}Changed`]: {\n    previousValue: T[K]; newValue: T[K];\n  };\n};", blanks: [{ placeholder: "______", answer: "Changed", hint: "Which suffix is appended to the property name?" }], concept: "Key Remapping + Template Literal" },
  { id: "18-cp-csslen", title: "CSS Length Type", description: "Complete the CSS length type.", template: "type CssLength = `${______}${______ | ______ | 'rem'}`;", solution: "type CssLength = `${number}${'px' | 'em' | 'rem'}`;", blanks: [{ placeholder: "______", answer: "number", hint: "Which type represents the numeric value?" }, { placeholder: "______", answer: "'px'", hint: "Which CSS unit is used for pixels?" }, { placeholder: "______", answer: "'em'", hint: "Which CSS unit is relative to font size?" }], concept: "CSS Length Pattern" },
  { id: "18-cp-route", title: "Extract Route Parameters", description: "Complete the parameter extraction.", template: "type ExtractParams<T extends string> =\n  T extends `${string}:${______ Param}/${infer Rest}` ? Param | ExtractParams<Rest> :\n  T extends `${string}:${infer Param}` ? Param : ______;", solution: "type ExtractParams<T extends string> =\n  T extends `${string}:${infer Param}/${infer Rest}` ? Param | ExtractParams<Rest> :\n  T extends `${string}:${infer Param}` ? Param : never;", blanks: [{ placeholder: "______", answer: "infer", hint: "Which keyword extracts the parameter name?" }, { placeholder: "______", answer: "never", hint: "What do you return when no parameter is found?" }], concept: "Route Parameter Extraction" },
];