/**
 * Lesson 18 — Debugging Challenges: Template Literal Types
 */
import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  { id: "L18-D1", title: "Capitalize instead of Uppercase", buggyCode: "type ScreamingCase<T extends string> = Capitalize<T>;\ntype A = ScreamingCase<'hello'>; // 'Hello' instead of 'HELLO'!", bugType: "logic-error", bugLine: 1, options: ["Capitalize only capitalizes the first letter — Uppercase capitalizes everything", "Capitalize is broken", "Template Literals don't work", "string type is wrong"], correctOption: 0, hints: ["What is the difference between Capitalize and Uppercase?", "Capitalize: first letter only. Uppercase: all letters."], fixedCode: "type ScreamingCase<T extends string> = Uppercase<T>;", explanation: "Capitalize<'hello'> = 'Hello'. Uppercase<'hello'> = 'HELLO'. For SCREAMING_CASE you need Uppercase.", concept: "capitalize-vs-uppercase", difficulty: 1 },
  { id: "L18-D2", title: "Missing string intersection with keyof", buggyCode: "type EventNames<T> = {\n  [K in keyof T as `${K}Changed`]: T[K]; // Error!\n};", errorMessage: "Type 'K' is not assignable to type 'string | number | bigint | boolean | null | undefined'", bugType: "type-error", bugLine: 2, options: ["K can be a symbol — Template Literals require string. Intersection: string & K", "keyof always returns string", "as clause is wrong", "Changed needs to be escaped"], correctOption: 0, hints: ["keyof T can also contain number and symbol.", "string & K filters for string keys."], fixedCode: "type EventNames<T> = {\n  [K in keyof T & string as `${K}Changed`]: T[K];\n};", explanation: "keyof T returns string | number | symbol. Template Literals only accept string. `keyof T & string` or `string & K` filters.", concept: "keyof-string-intersection", difficulty: 2 },
  { id: "L18-D3", title: "Replace only replaces the first occurrence", buggyCode: "type Replace<S extends string, From extends string, To extends string> =\n  S extends `${infer H}${From}${infer T}` ? `${H}${To}${T}` : S;\n\ntype A = Replace<'a.b.c', '.', '/'>;  // 'a/b.c' (not 'a/b/c'!)", bugType: "logic-error", bugLine: 2, options: ["Without recursion only the FIRST occurrence is replaced", "infer is wrong", "Template Literal cannot replace", "From needs to be escaped"], correctOption: 0, hints: ["After the first Replace — is the rest checked again?", "Recursion: ReplaceAll calls itself after each replacement."], fixedCode: "type ReplaceAll<S extends string, From extends string, To extends string> =\n  S extends `${infer H}${From}${infer T}` ? ReplaceAll<`${H}${To}${T}`, From, To> : S;", explanation: "Replace without recursion only replaces the first occurrence. ReplaceAll calls itself after each replacement until there are no more matches.", concept: "replace-vs-replaceall", difficulty: 2 },
  { id: "L18-D4", title: "Union explosion with Template Literals", buggyCode: "type Char = 'a'|'b'|'c'|'d'|'e'|'f'|'g'|'h'|'i'|'j'|'k'|'l'|'m'|'n'|'o'|'p'|'q'|'r'|'s'|'t'|'u'|'v'|'w'|'x'|'y'|'z';\ntype ThreeChar = `${Char}${Char}${Char}`;  // 26^3 = 17576 combinations!", bugType: "logic-error", bugLine: 2, options: ["Cartesian product produces too many combinations — TypeScript has union limits", "Char is defined incorrectly", "Template Literals can only handle 2 unions", "TypeScript bug"], correctOption: 0, hints: ["How many combinations are 26 * 26 * 26?", "TypeScript has a union limit (~100,000). 17576 is barely OK, but with 4 chars it would be 450,000+."], fixedCode: "// Instead of concrete unions: use a pattern\ntype ThreeChar = `${string}`;  // Or more specific constraints", explanation: "The cartesian product of unions can grow exponentially. TypeScript has limits. For large alphabets: use string patterns instead of concrete unions.", concept: "union-explosion", difficulty: 3 },
  { id: "L18-D5", title: "infer at the wrong end", buggyCode: "// Goal: extract file extension\ntype Extension<T extends string> = T extends `${infer Name}.${infer Ext}` ? Ext : never;\ntype A = Extension<'app.component.ts'>; // 'component.ts' instead of 'ts'!", bugType: "logic-error", bugLine: 2, options: ["First infer matches minimally, last matches maximally — Name = 'app', Ext = 'component.ts'", "infer doesn't work with dots", "Template Literal is wrong", "never is wrong"], correctOption: 0, hints: ["What does infer Name match? What does infer Ext match?", "Name matches up to the FIRST dot. Ext matches the entire rest."], fixedCode: "// Solution: recursively find the last dot\ntype Extension<T extends string> =\n  T extends `${string}.${infer Rest}`\n    ? Rest extends `${string}.${infer Deeper}`\n      ? Extension<Rest>\n      : Rest\n    : never;\n\n// Or simpler: match from the end", explanation: "For 'app.component.ts': infer Name = 'app' (shortest match), infer Ext = 'component.ts' (rest). For the last extension you need recursion.", concept: "infer-matching-order", difficulty: 3 },
];