/**
 * Lesson 18 — Misconception Exercises: Template Literal Types
 */
export interface Misconception { id: string; title: string; code: string; commonBelief: string; reality: string; concept: string; difficulty: number; }

export const misconceptions: Misconception[] = [
  { id: "18-runtime-validation", title: "Template Literal Types Validate at Runtime", code: `type Email = \`\${string}@\${string}.\${string}\`;\nconst email: Email = "not-an-email" as Email; // No runtime error!`, commonBelief: "Template Literal Types check string formats at runtime.", reality: "Template Literal Types exist only at compile time. They are removed during compilation. For runtime validation, you still need Regex or validator libraries.", concept: "Type-Level vs Runtime", difficulty: 1 },
  { id: "18-capitalize-all", title: "Capitalize Makes EVERYTHING Uppercase", code: `type A = Capitalize<"hello world">; // "Hello world" (not "Hello World"!)`, commonBelief: "Capitalize capitalizes all words (Title Case).", reality: "Capitalize only capitalizes the VERY FIRST letter. For Title Case, you would need to recursively capitalize each word start — a significantly more complex type.", concept: "Capitalize vs Title Case", difficulty: 2 },
  { id: "18-number-template", title: "Template Literal with number Yields number", code: `type CssLength = \`\${number}px\`;\n// Type is STRING, not number!\nconst a: CssLength = "100px"; // string, not 100`, commonBelief: "Template Literals with number yield numeric types.", reality: "Template Literal Types ALWAYS produce string types. ${number}px is a string like '100px', not the number 100. For numeric calculations, different patterns are needed.", concept: "Template Literals = Strings", difficulty: 2 },
  { id: "18-unlimited-combinations", title: "Unlimited Union Expansion", code: `type Char = 'a' | 'b' | ... | 'z'; // 26 characters\ntype TwoChars = \`\${Char}\${Char}\`; // 26 * 26 = 676 combinations\ntype ThreeChars = \`\${Char}\${Char}\${Char}\`; // 26^3 = 17576 — TOO MUCH!`, commonBelief: "Template Literal Types can generate arbitrarily large unions.", reality: "TypeScript has a limit for union size (~100,000). With too many combinations, you get the error 'Expression produces a union type that is too complex'. Avoid large cartesian products!", concept: "Union Size Limit", difficulty: 3 },
  { id: "18-infer-greedy", title: "infer Always Matches the Shortest", code: `type GetRest<T extends string> = T extends \`\${infer First}.\${infer Rest}\` ? Rest : never;\ntype A = GetRest<"a.b.c">; // "b.c" (not just "b"!)`, commonBelief: "infer always matches the shortest possible string.", reality: "infer in the first placeholder matches the shortest, but infer in the LAST placeholder matches the longest. For a.b.c: First = 'a', Rest = 'b.c'. This is like non-greedy vs greedy in Regex.", concept: "infer Matching Strategy", difficulty: 3 },
  { id: "18-template-literal-exact", title: "Template Literals Are Exact Matches", code: `type HasDot = \`\${string}.\${string}\`;\nconst a: HasDot = "a.b.c.d"; // OK! Even though there are multiple dots`, commonBelief: "Template Literal Types only match the exact pattern.", reality: "Template Literals with ${string} are very permissive — string matches EVERYTHING, including empty strings and strings with additional special characters. 'a.b.c.d' matches '${string}.${string}' because the second ${string} can also match 'b.c.d'.", concept: "Permissive Patterns", difficulty: 3 },
  { id: "18-recursive-limit", title: "Recursive String Types Are Unlimited", code: `type Repeat<S extends string, N extends number> = ...\n// With N > ~45, a recursion error occurs`, commonBelief: "Recursive Template Literal Types can go arbitrarily deep.", reality: "TypeScript has a recursion limit (~50 levels). Complex recursive string manipulations can quickly hit this limit. For production code: keep it simple!", concept: "Recursion Limit", difficulty: 3 },
  { id: "18-uncapitalize-vs-lowercase", title: "Uncapitalize and Lowercase Are the Same", code: `type A = Uncapitalize<"HELLO">; // "hELLO" (not "hello"!)\ntype B = Lowercase<"HELLO">;     // "hello"`, commonBelief: "Uncapitalize and Lowercase do the same thing.", reality: "Uncapitalize only changes the FIRST letter to lowercase. Lowercase changes ALL of them. 'HELLO' -> Uncapitalize: 'hELLO', Lowercase: 'hello'.", concept: "Uncapitalize vs Lowercase", difficulty: 2 },
];