/**
 * Lesson 18 — Parson's Problems: Template Literal Types
 */
import type { ParsonsProblem } from "../tools/parsons-engine.ts";

export const parsonsProblems: ParsonsProblem[] = [
  { id: "L18-P1", title: "Generate Event Name Type", description: "Order the lines to form a type that generates event handler names.", correctOrder: ["type EventHandlers<T> = {", "  [K in keyof T & string as `on${Capitalize<K>}Change`]:", "    (newValue: T[K], oldValue: T[K]) => void;", "};"], distractors: ["  [K in keyof T as `on${K}Change`]:", "  [K in keyof T as `on${Uppercase<K>}Change`]:"], hint: "string & K for string filtering, Capitalize (not Uppercase) for the first letter.", concept: "event-handler-generation", difficulty: 3 },
  { id: "L18-P2", title: "Extract Route Parameters", description: "Order the lines for recursive parameter extraction.", correctOrder: ["type ExtractParams<T extends string> =", "  T extends `${string}:${infer Param}/${infer Rest}`", "    ? Param | ExtractParams<Rest>", "    : T extends `${string}:${infer Param}`", "      ? Param", "      : never;"], distractors: ["  T extends `${infer Param}/${infer Rest}`", "    ? ExtractParams<Param>"], hint: "Two cases: with /-rest (recursive) and without (last parameter). Match the :param pattern.", concept: "route-param-extraction", difficulty: 4 },
  { id: "L18-P3", title: "ReplaceAll Recursively", description: "Order the lines for recursive string replacement.", correctOrder: ["type ReplaceAll<S extends string, From extends string, To extends string> =", "  S extends `${infer H}${From}${infer T}`", "    ? ReplaceAll<`${H}${To}${T}`, From, To>", "    : S;"], distractors: ["    ? `${H}${To}${T}`", "    ? ReplaceAll<S, From, To>"], hint: "After replacing: apply ReplaceAll to the NEW result (not to S). Without recursion only the first occurrence is replaced.", concept: "recursive-replace", difficulty: 3 },
];