/**
 * Lesson 18 — Tracing Exercises: Template Literal Types
 */
import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  { id: "18-union-expansion", title: "Union Expansion in Template Literals", description: "Trace how unions expand into a cartesian product.", code: ["type Prefix = 'get' | 'set';", "type Name = 'Name' | 'Age';", "type Methods = `${Prefix}${Name}`;"], steps: [{ lineIndex: 2, question: "How many combinations are produced?", expectedAnswer: "2 x 2 = 4", variables: { "Prefix": "2 members", "Name": "2 members", "Combinations": "4" }, explanation: "Cartesian product: every Prefix combined with every Name." }, { lineIndex: 2, question: "What are the concrete results?", expectedAnswer: "'getName' | 'getAge' | 'setName' | 'setAge'", variables: { "Methods": "'getName' | 'getAge' | 'setName' | 'setAge'" }, explanation: "All 4 combinations are joined into a union." }], concept: "cartesian-product", difficulty: 1 },
  { id: "18-split-recursion", title: "Recursive Split Step by Step", description: "Trace how Split recursively splits a string.", code: ["type Split<S extends string, D extends string> =", "  S extends `${infer H}${D}${infer T}` ? [H, ...Split<T, D>] : [S];", "", "type Result = Split<'a.b.c', '.'>;"], steps: [{ lineIndex: 3, question: "Step 1: Split<'a.b.c', '.'>", expectedAnswer: "H='a', T='b.c' -> ['a', ...Split<'b.c', '.'>]", variables: { "H": "'a'", "T": "'b.c'" }, explanation: "First dot found. H='a', T='b.c'. Recurse." }, { lineIndex: 3, question: "Step 2: Split<'b.c', '.'>", expectedAnswer: "H='b', T='c' -> ['b', ...Split<'c', '.'>]", variables: { "H": "'b'", "T": "'c'" }, explanation: "Second dot found. H='b', T='c'. One more recursion." }, { lineIndex: 3, question: "Step 3: Split<'c', '.'>", expectedAnswer: "No dot remaining -> ['c'] (else branch)", variables: { "S": "'c'", "Result": "['c']" }, explanation: "'c' contains no dot. Else branch: [S] = ['c']." }, { lineIndex: 3, question: "Final result?", expectedAnswer: "['a', 'b', 'c']", variables: { "Result": "['a', 'b', 'c']" }, explanation: "['a', ...['b', ...['c']]] = ['a', 'b', 'c']." }], concept: "recursive-split-trace", difficulty: 3 },
  { id: "18-capitalize-chain", title: "String Utility Chain", description: "Trace how multiple string utilities apply in sequence.", code: ["type A = Capitalize<'hello'>;", "type B = Uppercase<'hello'>;", "type C = `on${Capitalize<'mouseMove'>}`;", "type D = Uncapitalize<'Hello'>;", "type E = `${Lowercase<'GET'>} ${Capitalize<'users'>}`;"], steps: [{ lineIndex: 0, question: "What is A?", expectedAnswer: "'Hello'", variables: { "A": "'Hello'" }, explanation: "Capitalize: only the first letter is uppercased." }, { lineIndex: 1, question: "What is B?", expectedAnswer: "'HELLO'", variables: { "B": "'HELLO'" }, explanation: "Uppercase: ALL letters are uppercased." }, { lineIndex: 2, question: "What is C?", expectedAnswer: "'onMouseMove'", variables: { "C": "'onMouseMove'" }, explanation: "Capitalize<'mouseMove'> = 'MouseMove'. on + MouseMove = 'onMouseMove'." }, { lineIndex: 4, question: "What is E?", expectedAnswer: "'get Users'", variables: { "E": "'get Users'" }, explanation: "Lowercase<'GET'> = 'get'. Capitalize<'users'> = 'Users'. 'get Users'." }], concept: "string-utility-chain", difficulty: 2 },
  { id: "18-route-params", title: "Route Parameter Extraction", description: "Trace how route parameters are recursively extracted.", code: ["type ExtractParams<T extends string> =", "  T extends `${string}:${infer P}/${infer Rest}` ? P | ExtractParams<Rest> :", "  T extends `${string}:${infer P}` ? P : never;", "", "type Params = ExtractParams<'/users/:userId/posts/:postId'>;"], steps: [{ lineIndex: 4, question: "Step 1: Does the first case match?", expectedAnswer: "Yes: P='userId', Rest='posts/:postId'", variables: { "P": "'userId'", "Rest": "'posts/:postId'" }, explanation: "':userId/' is found. P='userId', Rest='posts/:postId'." }, { lineIndex: 4, question: "Step 2: ExtractParams<'posts/:postId'>", expectedAnswer: "First case does not match (no /). Second case: P='postId'", variables: { "P": "'postId'" }, explanation: "No further / after :postId. Second case applies." }, { lineIndex: 4, question: "Final result?", expectedAnswer: "'userId' | 'postId'", variables: { "Params": "'userId' | 'postId'" }, explanation: "'userId' | ExtractParams<'posts/:postId'> = 'userId' | 'postId'." }], concept: "route-param-trace", difficulty: 3 },
];