/**
 * Lesson 12 — Parson's Problems: Discriminated Unions
 */

import type { ParsonsProblem } from "../tools/parsons-engine.ts";

export const parsonsProblems: ParsonsProblem[] = [
  {
    id: "L12-P1",
    title: "Discriminated Union with Exhaustive Check",
    description: "Arrange the lines to form a Shape union with area function and assertNever.",
    correctOrder: [
      'type Shape =',
      '  | { kind: "circle"; radius: number }',
      '  | { kind: "rect"; width: number; height: number };',
      '',
      'function assertNever(value: never): never {',
      '  throw new Error(`Unhandled: ${value}`);',
      '}',
      '',
      'function area(shape: Shape): number {',
      '  switch (shape.kind) {',
      '    case "circle": return Math.PI * shape.radius ** 2;',
      '    case "rect": return shape.width * shape.height;',
      '    default: return assertNever(shape);',
      '  }',
      '}',
    ],
    distractors: [
      'function assertNever(value: unknown): never {',
      '    default: return assertNever(shape.kind);',
    ],
    hint: "assertNever takes 'never' (not unknown) and receives the object (not the discriminant).",
    concept: "exhaustive-check",
    difficulty: 2,
  },

  {
    id: "L12-P2",
    title: "Option<T> with Constructors",
    description: "Arrange the lines to form a complete Option<T> type with some/none/unwrapOr.",
    correctOrder: [
      'type Option<T> =',
      '  | { tag: "some"; value: T }',
      '  | { tag: "none" };',
      '',
      'function some<T>(value: T): Option<T> {',
      '  return { tag: "some", value };',
      '}',
      '',
      'function none<T>(): Option<T> {',
      '  return { tag: "none" };',
      '}',
      '',
      'function unwrapOr<T>(opt: Option<T>, fallback: T): T {',
      '  if (opt.tag === "some") return opt.value;',
      '  return fallback;',
      '}',
    ],
    distractors: [
      '  if (opt.tag === "none") return opt.value;',
      'function some<T>(value: T): T {',
    ],
    hint: "some returns Option<T> (not T). unwrapOr returns opt.value for 'some' (not for 'none').",
    concept: "option-adt",
    difficulty: 3,
  },

  {
    id: "L12-P3",
    title: "AsyncState<T> with render Function",
    description: "Arrange the lines to form a complete AsyncState type with render function.",
    correctOrder: [
      'type AsyncState<T> =',
      '  | { status: "idle" }',
      '  | { status: "loading" }',
      '  | { status: "error"; error: string }',
      '  | { status: "success"; data: T };',
      '',
      'function render<T>(state: AsyncState<T>): string {',
      '  switch (state.status) {',
      '    case "idle": return "Ready";',
      '    case "loading": return "Loading...";',
      '    case "error": return `Error: ${state.error}`;',
      '    case "success": return `OK: ${JSON.stringify(state.data)}`;',
      '  }',
      '}',
    ],
    distractors: [
      '  | { status: "error"; message: string }',
      '    case "error": return `Error: ${state.message}`;',
    ],
    hint: "The error variant has the property 'error' (not 'message'). Stay consistent!",
    concept: "async-state",
    difficulty: 2,
  },

  {
    id: "L12-P4",
    title: "Redux-style Reducer with Action Union",
    description: "Arrange the lines to form a Counter reducer with type-safe actions.",
    correctOrder: [
      'type CounterAction =',
      '  | { type: "INCREMENT" }',
      '  | { type: "DECREMENT" }',
      '  | { type: "SET"; payload: { value: number } };',
      '',
      'function reducer(count: number, action: CounterAction): number {',
      '  switch (action.type) {',
      '    case "INCREMENT": return count + 1;',
      '    case "DECREMENT": return count - 1;',
      '    case "SET": return action.payload.value;',
      '  }',
      '}',
    ],
    distractors: [
      '  | { type: "SET"; value: number };',
      '    case "SET": return action.value;',
    ],
    hint: "Redux convention: data lives in payload.value (not directly in action.value). The action has { type, payload }.",
    concept: "action-types-reducer",
    difficulty: 3,
  },
];