/**
 * Lesson 12 — Tracing Exercises: Discriminated Unions
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  {
    id: "12-narrowing-flow",
    title: "Narrowing via Discriminator",
    description: "Trace how TypeScript narrows the type through switch/case.",
    code: [
      'type Shape = { kind: "circle"; radius: number } | { kind: "rect"; w: number; h: number };',
      '',
      'function area(shape: Shape): number {',
      '  switch (shape.kind) {',
      '    case "circle":',
      '      return Math.PI * shape.radius ** 2;',
      '    case "rect":',
      '      return shape.w * shape.h;',
      '  }',
      '}',
      '',
      'console.log(area({ kind: "circle", radius: 5 }));',
      'console.log(area({ kind: "rect", w: 10, h: 3 }));',
    ],
    steps: [
      {
        lineIndex: 4,
        question: "What type does shape have in the 'circle' case?",
        expectedAnswer: '{ kind: "circle"; radius: number }',
        variables: { "shape.kind": '"circle"', "shape.radius": "5" },
        explanation: "TypeScript narrows shape to the Circle variant because kind === 'circle' was checked.",
      },
      {
        lineIndex: 5,
        question: "What does Math.PI * 5 ** 2 return?",
        expectedAnswer: "~78.54 (Math.PI * 25)",
        variables: { "shape.radius": "5", "Result": "78.5398..." },
        explanation: "** is the exponentiation operator. 5 ** 2 = 25. Math.PI * 25 = ~78.54.",
      },
      {
        lineIndex: 7,
        question: "What type does shape have in the 'rect' case?",
        expectedAnswer: '{ kind: "rect"; w: number; h: number }',
        variables: { "shape.kind": '"rect"', "shape.w": "10", "shape.h": "3" },
        explanation: "After the circle case, only rect remains. TypeScript narrows automatically.",
      },
    ],
    concept: "discriminator-narrowing",
    difficulty: 1,
  },

  {
    id: "12-exhaustive-never",
    title: "Exhaustive Check with never",
    description: "Trace how assertNever works.",
    code: [
      'type Light = { color: "red" } | { color: "yellow" } | { color: "green" };',
      '',
      'function assertNever(value: never): never {',
      '  throw new Error(`Unhandled: ${JSON.stringify(value)}`);',
      '}',
      '',
      'function action(light: Light): string {',
      '  switch (light.color) {',
      '    case "red": return "Stop";',
      '    case "yellow": return "Caution";',
      '    case "green": return "Go";',
      '    default: return assertNever(light);',
      '  }',
      '}',
    ],
    steps: [
      {
        lineIndex: 8,
        question: "What type does light have after case 'red'?",
        expectedAnswer: '{ color: "yellow" } | { color: "green" } — red was eliminated',
        variables: {},
        explanation: "TypeScript narrows the remaining type after each case.",
      },
      {
        lineIndex: 10,
        question: "What type does light have after case 'green'?",
        expectedAnswer: "never — all variants were eliminated",
        variables: {},
        explanation: "After red, yellow, and green nothing remains. The type is never.",
      },
      {
        lineIndex: 11,
        question: "Why does assertNever(light) compile without error?",
        expectedAnswer: "Because light has the type never — never is assignable to never",
        variables: { "light": "(Type: never)" },
        explanation: "All cases handled = never in the default. assertNever accepts never = no error.",
      },
    ],
    concept: "exhaustive-check-never",
    difficulty: 2,
  },

  {
    id: "12-option-flow",
    title: "Option<T> — Data Flow",
    description: "Trace how values flow through Option<T>.",
    code: [
      'type Option<T> = { tag: "some"; value: T } | { tag: "none" };',
      '',
      'function some<T>(value: T): Option<T> { return { tag: "some", value }; }',
      'function none<T>(): Option<T> { return { tag: "none" }; }',
      '',
      'function safeDivide(a: number, b: number): Option<number> {',
      '  if (b === 0) return none();',
      '  return some(a / b);',
      '}',
      '',
      'const r1 = safeDivide(10, 3);',
      'const r2 = safeDivide(10, 0);',
      '',
      'console.log(r1);',
      'console.log(r2);',
    ],
    steps: [
      {
        lineIndex: 10,
        question: "What is r1?",
        expectedAnswer: '{ tag: "some", value: 3.3333... }',
        variables: { "r1.tag": '"some"', "r1.value": "3.3333..." },
        explanation: "b is 3 (not 0), so safeDivide returns some(10/3).",
      },
      {
        lineIndex: 11,
        question: "What is r2?",
        expectedAnswer: '{ tag: "none" }',
        variables: { "r2.tag": '"none"' },
        explanation: "b is 0, so safeDivide returns none(). No error, no crash.",
      },
      {
        lineIndex: 13,
        question: "How do you safely access r1.value?",
        expectedAnswer: 'if (r1.tag === "some") { r1.value }',
        variables: {},
        explanation: "You must check the discriminator 'tag' before accessing value. TypeScript enforces this.",
      },
    ],
    concept: "option-data-flow",
    difficulty: 2,
  },

  {
    id: "12-async-state-transitions",
    title: "AsyncState — State Transitions",
    description: "Trace the state transitions of a loading process.",
    code: [
      'type AsyncState<T> =',
      '  | { status: "idle" }',
      '  | { status: "loading" }',
      '  | { status: "error"; error: string }',
      '  | { status: "success"; data: T };',
      '',
      'let state: AsyncState<string[]> = { status: "idle" };',
      'console.log(state.status);',
      '',
      'state = { status: "loading" };',
      'console.log(state.status);',
      '',
      'state = { status: "error", error: "Timeout" };',
      'console.log(state.status, (state as any).error);',
      '',
      'state = { status: "success", data: ["Alice", "Bob"] };',
      'console.log(state.status, (state as any).data);',
    ],
    steps: [
      {
        lineIndex: 7,
        question: "What does console.log output?",
        expectedAnswer: '"idle"',
        variables: { "state.status": '"idle"' },
        explanation: "Initial state is idle — no data loaded yet.",
      },
      {
        lineIndex: 10,
        question: "What properties does state have now?",
        expectedAnswer: 'Only { status: "loading" } — no data, no error',
        variables: { "state.status": '"loading"' },
        explanation: "Loading has only status. data and error don't exist — impossible states prevented!",
      },
      {
        lineIndex: 13,
        question: "What does console.log output?",
        expectedAnswer: '"error" "Timeout"',
        variables: { "state.status": '"error"', "state.error": '"Timeout"' },
        explanation: "The error state has status and error. No data — that would be nonsensical for an error.",
      },
      {
        lineIndex: 16,
        question: "What does console.log output?",
        expectedAnswer: '"success" ["Alice", "Bob"]',
        variables: { "state.status": '"success"', "state.data": '["Alice", "Bob"]' },
        explanation: "Success has status and data. No error — that would be nonsensical on success.",
      },
    ],
    concept: "async-state-transitions",
    difficulty: 2,
  },
];