/**
 * Lektion 18 — Completion Problems: Template Literal Types
 */
export interface CompletionProblem { id: string; title: string; description: string; template: string; solution: string; blanks: { placeholder: string; answer: string; hint: string }[]; concept: string; }

export const completionProblems: CompletionProblem[] = [
  { id: "18-cp-getter", title: "Getter-Name generieren", description: "Vervollstaendige den Template Literal Type.", template: "type GetterName<T extends string> = `______${______<T>}`;", solution: "type GetterName<T extends string> = `get${Capitalize<T>}`;", blanks: [{ placeholder: "______", answer: "get", hint: "Welcher Prefix steht vor dem Property-Namen?" }, { placeholder: "______", answer: "Capitalize", hint: "Welche Utility macht den ersten Buchstaben gross?" }], concept: "Template Literal + Capitalize" },
  { id: "18-cp-extract", title: "Prefix extrahieren", description: "Vervollstaendige die String-Extraktion.", template: "type ExtractPrefix<T extends string> = T extends `${______ P}_${string}` ? P : never;", solution: "type ExtractPrefix<T extends string> = T extends `${infer P}_${string}` ? P : never;", blanks: [{ placeholder: "______", answer: "infer", hint: "Welches Keyword deklariert eine Typ-Variable im Pattern?" }], concept: "infer in Template Literal" },
  { id: "18-cp-split", title: "Split-Typ", description: "Vervollstaendige den rekursiven Split-Typ.", template: "type Split<S extends string, D extends string> =\n  S extends `${infer H}${D}${infer T}` ? [H, ...______<T, D>] : [S];", solution: "type Split<S extends string, D extends string> =\n  S extends `${infer H}${D}${infer T}` ? [H, ...Split<T, D>] : [S];", blanks: [{ placeholder: "______", answer: "Split", hint: "Welcher Typ ruft sich rekursiv selbst auf?" }], concept: "Rekursiver Split" },
  { id: "18-cp-eventmap", title: "EventMap mit Template Literals", description: "Vervollstaendige den Event-Map-Typ.", template: "type EventMap<T> = {\n  [K in keyof T & string as `${K}______`]: {\n    previousValue: T[K]; newValue: T[K];\n  };\n};", solution: "type EventMap<T> = {\n  [K in keyof T & string as `${K}Changed`]: {\n    previousValue: T[K]; newValue: T[K];\n  };\n};", blanks: [{ placeholder: "______", answer: "Changed", hint: "Welches Suffix wird an den Property-Namen angehaengt?" }], concept: "Key Remapping + Template Literal" },
  { id: "18-cp-csslen", title: "CSS Length Type", description: "Vervollstaendige den CSS-Laengen-Typ.", template: "type CssLength = `${______}${______ | ______ | 'rem'}`;", solution: "type CssLength = `${number}${'px' | 'em' | 'rem'}`;", blanks: [{ placeholder: "______", answer: "number", hint: "Welcher Typ repraesentiert den numerischen Wert?" }, { placeholder: "______", answer: "'px'", hint: "Welche CSS-Einheit fuer Pixel?" }, { placeholder: "______", answer: "'em'", hint: "Welche CSS-Einheit relativ zur Schriftgroesse?" }], concept: "CSS Length Pattern" },
  { id: "18-cp-route", title: "Route-Parameter extrahieren", description: "Vervollstaendige die Parameter-Extraktion.", template: "type ExtractParams<T extends string> =\n  T extends `${string}:${______ Param}/${infer Rest}` ? Param | ExtractParams<Rest> :\n  T extends `${string}:${infer Param}` ? Param : ______;", solution: "type ExtractParams<T extends string> =\n  T extends `${string}:${infer Param}/${infer Rest}` ? Param | ExtractParams<Rest> :\n  T extends `${string}:${infer Param}` ? Param : never;", blanks: [{ placeholder: "______", answer: "infer", hint: "Welches Keyword extrahiert den Parameter-Namen?" }, { placeholder: "______", answer: "never", hint: "Was gibt man zurueck wenn kein Parameter gefunden wird?" }], concept: "Route Parameter Extraction" },
];
