/**
 * Lektion 18 — Debugging Challenges: Template Literal Types
 */
import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  { id: "L18-D1", title: "Capitalize statt Uppercase", buggyCode: "type ScreamingCase<T extends string> = Capitalize<T>;\ntype A = ScreamingCase<'hello'>; // 'Hello' statt 'HELLO'!", bugType: "logic-error", bugLine: 1, options: ["Capitalize macht nur den ersten Buchstaben gross — Uppercase macht alles gross", "Capitalize ist fehlerhaft", "Template Literals funktionieren nicht", "string-Typ ist falsch"], correctOption: 0, hints: ["Was ist der Unterschied zwischen Capitalize und Uppercase?", "Capitalize: nur erster Buchstabe. Uppercase: alle Buchstaben."], fixedCode: "type ScreamingCase<T extends string> = Uppercase<T>;", explanation: "Capitalize<'hello'> = 'Hello'. Uppercase<'hello'> = 'HELLO'. Fuer SCREAMING_CASE braucht man Uppercase.", concept: "capitalize-vs-uppercase", difficulty: 1 },
  { id: "L18-D2", title: "Fehlende string-Intersection bei keyof", buggyCode: "type EventNames<T> = {\n  [K in keyof T as `${K}Changed`]: T[K]; // Error!\n};", errorMessage: "Type 'K' is not assignable to type 'string | number | bigint | boolean | null | undefined'", bugType: "type-error", bugLine: 2, options: ["K kann symbol sein — Template Literals brauchen string. Intersection: string & K", "keyof gibt immer string", "as-Clause ist falsch", "Changed muss escaped werden"], correctOption: 0, hints: ["keyof T kann auch number und symbol enthalten.", "string & K filtert auf string-Keys."], fixedCode: "type EventNames<T> = {\n  [K in keyof T & string as `${K}Changed`]: T[K];\n};", explanation: "keyof T gibt string | number | symbol. Template Literals akzeptieren nur string. `keyof T & string` oder `string & K` filtert.", concept: "keyof-string-intersection", difficulty: 2 },
  { id: "L18-D3", title: "Replace ersetzt nur erstes Vorkommen", buggyCode: "type Replace<S extends string, From extends string, To extends string> =\n  S extends `${infer H}${From}${infer T}` ? `${H}${To}${T}` : S;\n\ntype A = Replace<'a.b.c', '.', '/'>;  // 'a/b.c' (nicht 'a/b/c'!)", bugType: "logic-error", bugLine: 2, options: ["Ohne Rekursion wird nur das ERSTE Vorkommen ersetzt", "infer ist falsch", "Template Literal kann nicht replacen", "From muss escaped werden"], correctOption: 0, hints: ["Nach dem ersten Replace — wird der Rest nochmal geprueft?", "Rekursion: ReplaceAll ruft sich selbst auf nach jedem Replace."], fixedCode: "type ReplaceAll<S extends string, From extends string, To extends string> =\n  S extends `${infer H}${From}${infer T}` ? ReplaceAll<`${H}${To}${T}`, From, To> : S;", explanation: "Replace ohne Rekursion ersetzt nur das erste Vorkommen. ReplaceAll ruft sich nach jedem Ersetzen selbst auf bis kein Match mehr da ist.", concept: "replace-vs-replaceall", difficulty: 2 },
  { id: "L18-D4", title: "Union-Explosion bei Template Literals", buggyCode: "type Char = 'a'|'b'|'c'|'d'|'e'|'f'|'g'|'h'|'i'|'j'|'k'|'l'|'m'|'n'|'o'|'p'|'q'|'r'|'s'|'t'|'u'|'v'|'w'|'x'|'y'|'z';\ntype ThreeChar = `${Char}${Char}${Char}`;  // 26^3 = 17576 Kombinationen!", bugType: "logic-error", bugLine: 2, options: ["Kartesisches Produkt erzeugt zu viele Kombinationen — TypeScript hat Union-Limits", "Char ist falsch definiert", "Template Literals koennen nur 2 Unions", "TypeScript-Bug"], correctOption: 0, hints: ["Wie viele Kombinationen sind 26 * 26 * 26?", "TypeScript hat ein Union-Limit (~100.000). 17576 ist noch knapp OK, aber bei 4 Chars waeren es 450.000+."], fixedCode: "// Statt konkreter Unions: Pattern verwenden\ntype ThreeChar = `${string}`;  // Oder spezifischere Constraints", explanation: "Kartesisches Produkt von Unions kann exponentiell wachsen. TypeScript hat Limits. Fuer grosse Alphabete: string-Pattern statt konkreter Union verwenden.", concept: "union-explosion", difficulty: 3 },
  { id: "L18-D5", title: "infer am falschen Ende", buggyCode: "// Ziel: Dateiendung extrahieren\ntype Extension<T extends string> = T extends `${infer Name}.${infer Ext}` ? Ext : never;\ntype A = Extension<'app.component.ts'>; // 'component.ts' statt 'ts'!", bugType: "logic-error", bugLine: 2, options: ["Erstes infer matcht minimal, letztes maximal — Name = 'app', Ext = 'component.ts'", "infer funktioniert nicht mit Punkten", "Template Literal ist falsch", "never ist falsch"], correctOption: 0, hints: ["Was matcht infer Name? Was matcht infer Ext?", "Name matcht bis zum ERSTEN Punkt. Ext matcht den gesamten Rest."], fixedCode: "// Loesung: Rekursiv den letzten Punkt finden\ntype Extension<T extends string> =\n  T extends `${string}.${infer Rest}`\n    ? Rest extends `${string}.${infer Deeper}`\n      ? Extension<Rest>\n      : Rest\n    : never;\n\n// Oder einfacher: von hinten matchen", explanation: "Bei 'app.component.ts': infer Name = 'app' (kuerzester Match), infer Ext = 'component.ts' (Rest). Fuer die letzte Extension braucht man Rekursion.", concept: "infer-matching-order", difficulty: 3 },
];
