/**
 * Lektion 18 — Fehlkonzeption-Exercises: Template Literal Types
 */
export interface Misconception { id: string; title: string; code: string; commonBelief: string; reality: string; concept: string; difficulty: number; }

export const misconceptions: Misconception[] = [
  { id: "18-runtime-validation", title: "Template Literal Types validieren zur Laufzeit", code: `type Email = \`\${string}@\${string}.\${string}\`;\nconst email: Email = "not-an-email" as Email; // Kein Runtime-Fehler!`, commonBelief: "Template Literal Types prufen String-Formate zur Laufzeit.", reality: "Template Literal Types existieren nur zur Compile-Zeit. Sie werden beim Compilieren entfernt. Fuer Runtime-Validierung braucht man weiterhin Regex oder Validator-Libraries.", concept: "Type-Level vs Runtime", difficulty: 1 },
  { id: "18-capitalize-all", title: "Capitalize macht ALLES gross", code: `type A = Capitalize<"hello world">; // "Hello world" (nicht "Hello World"!)`, commonBelief: "Capitalize macht alle Woerter gross (Title Case).", reality: "Capitalize macht nur den ALLERERSTEN Buchstaben gross. Fuer Title Case muesste man rekursiv jeden Wort-Anfang capitalisieren — ein deutlich komplexerer Typ.", concept: "Capitalize vs Title Case", difficulty: 2 },
  { id: "18-number-template", title: "Template Literal mit number ergibt number", code: `type CssLength = \`\${number}px\`;\n// Typ ist STRING, nicht number!\nconst a: CssLength = "100px"; // string, nicht 100`, commonBelief: "Template Literals mit number ergeben numerische Typen.", reality: "Template Literal Types erzeugen IMMER String-Typen. ${number}px ist ein String wie '100px', nicht die Zahl 100. Fuer numerische Berechnungen braucht man andere Patterns.", concept: "Template Literals = Strings", difficulty: 2 },
  { id: "18-unlimited-combinations", title: "Unbegrenzte Union-Expansion", code: `type Char = 'a' | 'b' | ... | 'z'; // 26 Zeichen\ntype TwoChars = \`\${Char}\${Char}\`; // 26 * 26 = 676 Kombinationen\ntype ThreeChars = \`\${Char}\${Char}\${Char}\`; // 26^3 = 17576 — ZU VIEL!`, commonBelief: "Template Literal Types koennen beliebig grosse Unions erzeugen.", reality: "TypeScript hat ein Limit fuer Union-Groesse (~100.000). Bei zu vielen Kombinationen gibt es den Fehler 'Expression produces a union type that is too complex'. Grosse kartesische Produkte vermeiden!", concept: "Union-Groessen-Limit", difficulty: 3 },
  { id: "18-infer-greedy", title: "infer matcht immer das Kuerzeste", code: `type GetRest<T extends string> = T extends \`\${infer First}.\${infer Rest}\` ? Rest : never;\ntype A = GetRest<"a.b.c">; // "b.c" (nicht nur "b"!)`, commonBelief: "infer matcht immer den kuerzest-moeglichen String.", reality: "infer im ersten Platzhalter matcht das Kuerzeste, aber infer im LETZTEN Platzhalter matcht das Laengste. Bei a.b.c: First = 'a', Rest = 'b.c'. Das ist wie non-greedy vs greedy bei Regex.", concept: "infer Matching-Strategie", difficulty: 3 },
  { id: "18-template-literal-exact", title: "Template Literals sind exakte Matches", code: `type HasDot = \`\${string}.\${string}\`;\nconst a: HasDot = "a.b.c.d"; // OK! Obwohl mehrere Punkte`, commonBelief: "Template Literal Types matchen nur den exakten Pattern.", reality: "Template Literals mit ${string} sind sehr permissiv — string matcht ALLES, auch leere Strings und Strings mit weiteren Sonderzeichen. 'a.b.c.d' matcht '${string}.${string}' weil der zweite ${string} auch 'b.c.d' matchen kann.", concept: "Permissive Patterns", difficulty: 3 },
  { id: "18-recursive-limit", title: "Rekursive String-Typen sind unbegrenzt", code: `type Repeat<S extends string, N extends number> = ...\n// Bei N > ~45 gibt es einen Rekursions-Fehler`, commonBelief: "Rekursive Template Literal Types koennen beliebig tief gehen.", reality: "TypeScript hat ein Rekursions-Limit (~50 Ebenen). Komplexe rekursive String-Manipulationen koennen schnell an dieses Limit stossen. Fuer Produktionscode: einfach halten!", concept: "Rekursions-Limit", difficulty: 3 },
  { id: "18-uncapitalize-vs-lowercase", title: "Uncapitalize und Lowercase sind gleich", code: `type A = Uncapitalize<"HELLO">; // "hELLO" (nicht "hello"!)\ntype B = Lowercase<"HELLO">;     // "hello"`, commonBelief: "Uncapitalize und Lowercase machen dasselbe.", reality: "Uncapitalize aendert nur den ERSTEN Buchstaben zu Kleinschreibung. Lowercase aendert ALLE. 'HELLO' -> Uncapitalize: 'hELLO', Lowercase: 'hello'.", concept: "Uncapitalize vs Lowercase", difficulty: 2 },
];
