/**
 * Lektion 18 — Pre-Test-Fragen: Template Literal Types
 */
export interface PretestQuestion { sectionIndex: number; question: string; options: string[]; correct: number; briefExplanation: string; }

export const pretestQuestions: PretestQuestion[] = [
  { sectionIndex: 1, question: "Was erzeugt `\\`${A}${B}\\`` mit Unions?", options: ["A | B", "Kartesisches Produkt aller Kombinationen", "A & B", "Ich weiss es nicht"], correct: 1, briefExplanation: "Unions werden zu allen moeglichen Kombinationen expandiert." },
  { sectionIndex: 1, question: "Was ist `type T = \\`Hello, ${string}!\\``?", options: ["Ein exakter String", "Ein Pattern das alle Strings mit Hello-Prefix matcht", "Ein Fehler", "Ich weiss es nicht"], correct: 1, briefExplanation: "string als Platzhalter akzeptiert beliebige Strings an der Position." },
  { sectionIndex: 1, question: "Existieren Template Literal Types zur Laufzeit?", options: ["Ja", "Nein — nur zur Compile-Zeit", "Teilweise", "Ich weiss es nicht"], correct: 1, briefExplanation: "Wie alle TS-Typen werden sie beim Compilieren entfernt." },
  { sectionIndex: 2, question: "Was ist Capitalize<'hello'>?", options: ["'HELLO'", "'Hello'", "'hello'", "Ich weiss es nicht"], correct: 1, briefExplanation: "Capitalize macht nur den ersten Buchstaben gross." },
  { sectionIndex: 2, question: "Was ist der Unterschied zwischen Uppercase und Capitalize?", options: ["Kein Unterschied", "Uppercase: ALLES gross. Capitalize: nur erster Buchstabe", "Capitalize: alles gross", "Ich weiss es nicht"], correct: 1, briefExplanation: "Uppercase = alle Buchstaben. Capitalize = nur der erste." },
  { sectionIndex: 2, question: "Sind die String-Utilities mit Conditional Types nachbaubar?", options: ["Ja", "Nein — sie sind intrinsisch im Compiler", "Nur Capitalize", "Ich weiss es nicht"], correct: 1, briefExplanation: "Uppercase, Lowercase, Capitalize, Uncapitalize sind intrinsisch." },
  { sectionIndex: 3, question: "Kann infer in Template Literals verwendet werden?", options: ["Nein", "Ja — fuer String-Parsing auf Type-Level", "Nur fuer Zahlen", "Ich weiss es nicht"], correct: 1, briefExplanation: "infer in Template Literals extrahiert Teile eines Strings." },
  { sectionIndex: 3, question: "Was macht Split<'a.b.c', '.'>?", options: ["'a.b.c'", "['a', 'b', 'c']", "Fehler", "Ich weiss es nicht"], correct: 1, briefExplanation: "Rekursives Pattern Matching splittet den String in ein Tuple." },
  { sectionIndex: 3, question: "Kann man Replace auf Type-Level bauen?", options: ["Nein", "Ja — mit infer und Template Literal Rekursion", "Nur fuer einzelne Zeichen", "Ich weiss es nicht"], correct: 1, briefExplanation: "S extends \\`${infer H}${From}${infer T}\\` ermoeglicht Replace." },
  { sectionIndex: 4, question: "Wie generiert man Event-Namen aus Properties?", options: ["Manuell", "Template Literal im Key Remapping: \\`${K}Changed\\`", "Runtime-Code", "Ich weiss es nicht"], correct: 1, briefExplanation: "Key Remapping + Template Literal = automatische Event-Namen." },
  { sectionIndex: 4, question: "Was ist \\`on${Capitalize<K>}\\`?", options: ["Ein Event-Handler-Name", "React-artiger Event-Prop-Name: onClick, onScroll", "Ein Fehler", "Ich weiss es nicht"], correct: 1, briefExplanation: "Das Standard-Pattern fuer Event-Props in React und aehnlichen Frameworks." },
  { sectionIndex: 4, question: "Wie verknuepft man Event-Name und Payload typsicher?", options: ["Strings", "Interface das Event-Namen auf Payload-Typen mappt + Generics", "Runtime-Checks", "Ich weiss es nicht"], correct: 1, briefExplanation: "Events-Interface + K extends keyof Events = typsichere Verknuepfung." },
  { sectionIndex: 5, question: "Wie erzwingt man CSS-Einheiten auf Type-Level?", options: ["Regex", "\\`${number}${'px'|'em'|'rem'}\\` als Typ", "Validator-Funktion", "Ich weiss es nicht"], correct: 1, briefExplanation: "Template Literal mit number + Einheiten-Union erzwingt korrektes Format." },
  { sectionIndex: 5, question: "Kann man Route-Parameter auf Type-Level extrahieren?", options: ["Nein", "Ja — mit rekursivem infer auf :param-Patterns", "Nur zur Laufzeit", "Ich weiss es nicht"], correct: 1, briefExplanation: "Rekursives infer-Pattern findet :param-Segmente im Pfad-String." },
  { sectionIndex: 5, question: "Welches Framework nutzt Template Literal Types am staerksten?", options: ["jQuery", "Moderne Frameworks: React (Props), Express (Routes), Prisma (Schema)", "Kein Framework", "Ich weiss es nicht"], correct: 1, briefExplanation: "Template Literal Types sind in modernen Frameworks allgegenwaertig." },
];
