/**
 * Lektion 18 — Tracing-Exercises: Template Literal Types
 */
import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  { id: "18-union-expansion", title: "Union-Expansion in Template Literals", description: "Verfolge wie Unions zum kartesischen Produkt expandiert werden.", code: ["type Prefix = 'get' | 'set';", "type Name = 'Name' | 'Age';", "type Methods = `${Prefix}${Name}`;"], steps: [{ lineIndex: 2, question: "Wie viele Kombinationen entstehen?", expectedAnswer: "2 x 2 = 4", variables: { "Prefix": "2 Member", "Name": "2 Member", "Kombinationen": "4" }, explanation: "Kartesisches Produkt: jeder Prefix mit jedem Name." }, { lineIndex: 2, question: "Was sind die konkreten Ergebnisse?", expectedAnswer: "'getName' | 'getAge' | 'setName' | 'setAge'", variables: { "Methods": "'getName' | 'getAge' | 'setName' | 'setAge'" }, explanation: "Alle 4 Kombinationen werden zum Union zusammengefuegt." }], concept: "cartesian-product", difficulty: 1 },
  { id: "18-split-recursion", title: "Rekursiver Split Schritt fuer Schritt", description: "Verfolge wie Split einen String rekursiv aufteilt.", code: ["type Split<S extends string, D extends string> =", "  S extends `${infer H}${D}${infer T}` ? [H, ...Split<T, D>] : [S];", "", "type Result = Split<'a.b.c', '.'>;"], steps: [{ lineIndex: 3, question: "Schritt 1: Split<'a.b.c', '.'>", expectedAnswer: "H='a', T='b.c' -> ['a', ...Split<'b.c', '.'>]", variables: { "H": "'a'", "T": "'b.c'" }, explanation: "Erster Punkt gefunden. H='a', T='b.c'. Rekursion." }, { lineIndex: 3, question: "Schritt 2: Split<'b.c', '.'>", expectedAnswer: "H='b', T='c' -> ['b', ...Split<'c', '.'>]", variables: { "H": "'b'", "T": "'c'" }, explanation: "Zweiter Punkt gefunden. H='b', T='c'. Noch eine Rekursion." }, { lineIndex: 3, question: "Schritt 3: Split<'c', '.'>", expectedAnswer: "Kein Punkt mehr -> ['c'] (Else-Branch)", variables: { "S": "'c'", "Result": "['c']" }, explanation: "'c' enthaelt keinen Punkt. Else-Branch: [S] = ['c']." }, { lineIndex: 3, question: "Endergebnis?", expectedAnswer: "['a', 'b', 'c']", variables: { "Result": "['a', 'b', 'c']" }, explanation: "['a', ...['b', ...['c']]] = ['a', 'b', 'c']." }], concept: "recursive-split-trace", difficulty: 3 },
  { id: "18-capitalize-chain", title: "String-Utility-Kette", description: "Verfolge wie mehrere String-Utilities nacheinander wirken.", code: ["type A = Capitalize<'hello'>;", "type B = Uppercase<'hello'>;", "type C = `on${Capitalize<'mouseMove'>}`;", "type D = Uncapitalize<'Hello'>;", "type E = `${Lowercase<'GET'>} ${Capitalize<'users'>}`;"], steps: [{ lineIndex: 0, question: "Was ist A?", expectedAnswer: "'Hello'", variables: { "A": "'Hello'" }, explanation: "Capitalize: nur erster Buchstabe gross." }, { lineIndex: 1, question: "Was ist B?", expectedAnswer: "'HELLO'", variables: { "B": "'HELLO'" }, explanation: "Uppercase: ALLE Buchstaben gross." }, { lineIndex: 2, question: "Was ist C?", expectedAnswer: "'onMouseMove'", variables: { "C": "'onMouseMove'" }, explanation: "Capitalize<'mouseMove'> = 'MouseMove'. on + MouseMove = 'onMouseMove'." }, { lineIndex: 4, question: "Was ist E?", expectedAnswer: "'get Users'", variables: { "E": "'get Users'" }, explanation: "Lowercase<'GET'> = 'get'. Capitalize<'users'> = 'Users'. 'get Users'." }], concept: "string-utility-chain", difficulty: 2 },
  { id: "18-route-params", title: "Route-Parameter Extraktion", description: "Verfolge wie Route-Parameter rekursiv extrahiert werden.", code: ["type ExtractParams<T extends string> =", "  T extends `${string}:${infer P}/${infer Rest}` ? P | ExtractParams<Rest> :", "  T extends `${string}:${infer P}` ? P : never;", "", "type Params = ExtractParams<'/users/:userId/posts/:postId'>;"], steps: [{ lineIndex: 4, question: "Schritt 1: Matcht der erste Case?", expectedAnswer: "Ja: P='userId', Rest='posts/:postId'", variables: { "P": "'userId'", "Rest": "'posts/:postId'" }, explanation: "':userId/' wird gefunden. P='userId', Rest='posts/:postId'." }, { lineIndex: 4, question: "Schritt 2: ExtractParams<'posts/:postId'>", expectedAnswer: "Erster Case matcht nicht (kein /). Zweiter Case: P='postId'", variables: { "P": "'postId'" }, explanation: "Kein weiterer / nach :postId. Zweiter Case greift." }, { lineIndex: 4, question: "Endergebnis?", expectedAnswer: "'userId' | 'postId'", variables: { "Params": "'userId' | 'postId'" }, explanation: "'userId' | ExtractParams<'posts/:postId'> = 'userId' | 'postId'." }], concept: "route-param-trace", difficulty: 3 },
];
