/**
 * Lektion 18 — Transfer Tasks: Template Literal Types
 */
import type { TransferTask } from "../tools/transfer-engine.ts";

export const transferTasks: TransferTask[] = [
  { id: "18-type-safe-router", title: "Typsicherer Router mit Template Literal Types", prerequisiteLessons: [17, 18], scenario: "Dein Express-aehnlicher Router akzeptiert beliebige Strings als Pfade. Tippfehler in Route-Parametern werden erst zur Laufzeit entdeckt. Der params-Parameter ist Record<string, string> — keine Typ-Pruefung.", task: "Erstelle einen typsicheren Router:\n\n1. ExtractParams<Path> extrahiert :param-Segmente aus dem Pfad\n2. Router.get(path, handler) inferiert den Params-Typ aus dem Pfad\n3. Handler bekommt typisierte params: Record<ExtractParams<Path>, string>\n4. Demonstriere mit /users/:id, /posts/:postId/comments/:commentId", starterCode: "// TODO: ExtractParams<Path>, Router, typsichere Handler", solutionCode: "type ExtractParams<T extends string> =\n  T extends `${string}:${infer P}/${infer Rest}` ? P | ExtractParams<Rest> :\n  T extends `${string}:${infer P}` ? P : never;\n\ntype RouteHandler<Path extends string> = (\n  params: Record<ExtractParams<Path>, string>,\n  query: Record<string, string>\n) => void;\n\nclass Router {\n  get<P extends string>(path: P, handler: RouteHandler<P>): void {\n    console.log(`Registered GET ${path}`);\n  }\n}\n\nconst router = new Router();\nrouter.get('/users/:id', (params) => {\n  console.log(params.id); // typsicher!\n});\nrouter.get('/posts/:postId/comments/:commentId', (params) => {\n  console.log(params.postId, params.commentId); // typsicher!\n});", conceptsBridged: ["Template Literal Types fuer String-Parsing", "infer fuer Parameter-Extraktion", "Generische Funktionen mit String-Constraints", "Record<ExtractedKeys, string> fuer typsicheren Zugriff"], estimatedMinutes: 20, difficulty: 3 },
  { id: "18-i18n-system", title: "Typsicheres i18n-System", prerequisiteLessons: [16, 17, 18], scenario: "Dein Projekt hat 500+ Uebersetzungsschluessel. t('some.key') akzeptiert jeden String — Tippfehler werden nie entdeckt. Fehlende Uebersetzungen sind erst zur Laufzeit sichtbar.", task: "Erstelle ein typsicheres i18n-System:\n\n1. TranslationKeys<T> generiert Dot-Notation-Pfade aus einem verschachtelten Objekt\n2. t(key) akzeptiert nur gueltige Keys\n3. Interpolation mit {{name}}-Syntax: t('greeting', { name: 'Max' })\n4. Demonstriere mit einem deutschen/englischen Translations-Objekt", starterCode: "// TODO: TranslationKeys, t()-Funktion, Interpolation", solutionCode: "type DotPaths<T, Prefix extends string = ''> = T extends object\n  ? { [K in keyof T & string]: T[K] extends object\n      ? DotPaths<T[K], `${Prefix}${K}.`>\n      : `${Prefix}${K}` }[keyof T & string]\n  : never;\n\nconst translations = {\n  nav: { home: 'Startseite', about: 'Ueber uns' },\n  greeting: 'Hallo {{name}}!',\n  error: { notFound: 'Seite nicht gefunden', forbidden: 'Zugriff verweigert' },\n} as const;\n\ntype TranslationKey = DotPaths<typeof translations>;\n// 'nav.home' | 'nav.about' | 'greeting' | 'error.notFound' | 'error.forbidden'\n\nfunction t(key: TranslationKey, params?: Record<string, string>): string {\n  return key; // Placeholder\n}", conceptsBridged: ["Rekursive Dot-Notation-Pfade", "as const fuer Literal-Typen", "Template Literal Types fuer Key-Generierung", "Verschachtelte Objekt-Typen traversieren"], estimatedMinutes: 25, difficulty: 4 },
];
