/**
 * Lektion 23 — Debugging Challenges: Recursive Types
 *
 * 5 Challenges zu rekursiven Typen, Deep-Operationen, Paths und Performance.
 */

import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  // ─── Challenge 1: Fehlende Abbruchbedingung ──────────────────────────────
  {
    id: "L23-D1",
    title: "Zirkulaere Referenz statt Rekursion",
    buggyCode: [
      "// Versuch einen 'nullable' Typ zu definieren:",
      "type Nullable = Nullable | null;",
      "",
      "const value: Nullable = null;",
      "const other: Nullable = 'hello';",
    ].join("\n"),
    errorMessage: "Type alias 'Nullable' circularly references itself.",
    bugType: "type-error",
    bugLine: 2,
    options: [
      "null kann nicht in einer Union stehen",
      "Direkte Zirkularitaet in Type-Aliases ist verboten — Rekursion braucht ein Property oder Conditional",
      "TypeScript unterstuetzt keine rekursiven Typen",
      "Der Typ muesste 'recursive' markiert werden",
    ],
    correctOption: 1,
    hints: [
      "Vergleiche: type X = X | null vs type X = { value: X | null }",
      "Rekursion funktioniert nur in bestimmten Kontexten: Properties, Conditional Types, Mapped Types.",
      "type Nullable<T> = T | null ist kein rekursiver Typ — es ist ein Union-Alias.",
    ],
    fixedCode: [
      "// Option A: Einfacher Union-Alias (nicht rekursiv):",
      "type Nullable<T> = T | null;",
      "",
      "const value: Nullable<string> = null;",
      "const other: Nullable<string> = 'hello';",
    ].join("\n"),
  },

  // ─── Challenge 2: DeepPartial ohne Array-Handling ─────────────────────────
  {
    id: "L23-D2",
    title: "DeepPartial zerstoert Arrays",
    buggyCode: [
      "type DeepPartial<T> = {",
      "  [K in keyof T]?: T[K] extends object",
      "    ? DeepPartial<T[K]>",
      "    : T[K];",
      "};",
      "",
      "type Config = {",
      "  tags: string[];",
      "  nested: { items: number[] };",
      "};",
      "",
      "// Erwartet: tags?: string[]; nested?: { items?: number[] }",
      "// Bekommt: tags?: { length?: number; push?: ... } ???",
      "type PartialConfig = DeepPartial<Config>;",
    ].join("\n"),
    errorMessage: undefined,
    bugType: "logic-error",
    bugLine: 2,
    options: [
      "object schliesst Arrays nicht ein",
      "Arrays sind Objekte (typeof [] === 'object'), deshalb werden sie rekursiv aufgeloest statt als Arrays erhalten",
      "DeepPartial funktioniert nur fuer flache Objekte",
      "Der Mapped Type iteriert nicht ueber Array-Elemente",
    ],
    correctOption: 1,
    hints: [
      "Was ergibt typeof []? → 'object'. Also matcht extends object auch Arrays.",
      "Die Loesung: Arrays VOR dem object-Check abfangen.",
      "Nutze T[K] extends (infer U)[] ? DeepPartial<U>[] : ... um Arrays zu erkennen.",
    ],
    fixedCode: [
      "type DeepPartial<T> = {",
      "  [K in keyof T]?: T[K] extends (infer U)[]",
      "    ? DeepPartial<U>[]",
      "    : T[K] extends object",
      "      ? DeepPartial<T[K]>",
      "      : T[K];",
      "};",
      "",
      "type Config = {",
      "  tags: string[];",
      "  nested: { items: number[] };",
      "};",
      "",
      "// Jetzt korrekt: tags?: string[]; nested?: { items?: number[] }",
      "type PartialConfig = DeepPartial<Config>;",
    ].join("\n"),
  },

  // ─── Challenge 3: Paths erfasst Array-Properties ─────────────────────────
  {
    id: "L23-D3",
    title: "Paths listet Array-Methoden als Pfade auf",
    buggyCode: [
      "type Paths<T> = T extends object",
      "  ? { [K in keyof T & string]: K | `${K}.${Paths<T[K]>}` }[keyof T & string]",
      "  : never;",
      "",
      "type Data = {",
      "  users: { name: string }[];",
      "};",
      "",
      "type AllPaths = Paths<Data>;",
      "// Erwartet: 'users' | 'users.name'",
      "// Bekommt: 'users' | 'users.length' | 'users.push' | 'users.pop' | ...",
    ].join("\n"),
    errorMessage: undefined,
    bugType: "logic-error",
    bugLine: 2,
    options: [
      "keyof T & string filtert nicht korrekt",
      "Template Literal Types funktionieren nicht mit Arrays",
      "Arrays sind Objekte — keyof string[] gibt alle Array-Methoden zurueck, nicht den Element-Typ",
      "Paths braucht ein Tiefenlimit",
    ],
    correctOption: 2,
    hints: [
      "Was gibt keyof string[] zurueck? → 'length' | 'push' | 'pop' | ...",
      "Arrays muessen separat behandelt werden — mit (infer U)[] den Element-Typ extrahieren.",
      "Fuer Array-Pfade koennte man `${number}` als Platzhalter verwenden.",
    ],
    fixedCode: [
      "type Paths<T> = T extends object",
      "  ? T extends (infer U)[]",
      "    ? Paths<U>",
      "    : { [K in keyof T & string]: K | `${K}.${Paths<T[K]>}` }[keyof T & string]",
      "  : never;",
      "",
      "type Data = {",
      "  users: { name: string }[];",
      "};",
      "",
      "type AllPaths = Paths<Data>;",
      "// Jetzt: 'users' | 'users.name' (Element-Pfade)",
    ].join("\n"),
  },

  // ─── Challenge 4: Fehlende Tail-Position ──────────────────────────────────
  {
    id: "L23-D4",
    title: "Rekursion bricht bei 50 ab trotz 'einfachem' Typ",
    buggyCode: [
      "type BuildTuple<N extends number, Acc extends unknown[] = []> =",
      "  Acc['length'] extends N",
      "    ? Acc",
      "    : [BuildTuple<N, [...Acc, unknown]>][0];",
      "",
      "// Funktioniert:",
      "type Ten = BuildTuple<10>;",
      "",
      "// Bricht ab:",
      "type Hundred = BuildTuple<100>;",
      "// Error: Type instantiation is excessively deep",
    ].join("\n"),
    errorMessage: "Type instantiation is excessively deep and possibly infinite.",
    bugType: "type-error",
    bugLine: 4,
    options: [
      "BuildTuple kann nur bis 10 zaehlen",
      "Acc braucht eine andere Initialisierung",
      "Der [0]-Zugriff verhindert Tail Recursion Optimization — der rekursive Aufruf ist nicht in Tail-Position",
      "TypeScript 5.7 unterstuetzt keine Tuple-Rekursion",
    ],
    correctOption: 2,
    hints: [
      "Vergleiche: Direkt BuildTuple<N, [...Acc, unknown]> vs [BuildTuple<...>][0]",
      "Tail Recursion Optimization greift nur wenn der rekursive Aufruf das LETZTE ist.",
      "Entferne den Wrapper [..][0] — der rekursive Aufruf muss direkt stehen.",
    ],
    fixedCode: [
      "type BuildTuple<N extends number, Acc extends unknown[] = []> =",
      "  Acc['length'] extends N",
      "    ? Acc",
      "    : BuildTuple<N, [...Acc, unknown]>;",
      "    // ^ Direkt in Tail-Position → Tail Recursion Optimization greift",
      "",
      "type Ten = BuildTuple<10>;     // OK",
      "type Hundred = BuildTuple<100>; // Jetzt auch OK!",
    ].join("\n"),
  },

  // ─── Challenge 5: PathValue vergisst Rekursion ───────────────────────────
  {
    id: "L23-D5",
    title: "PathValue gibt immer never zurueck",
    buggyCode: [
      "type PathValue<T, P extends string> =",
      "  P extends `${infer Head}.${infer Tail}`",
      "    ? Head extends keyof T",
      "      ? T[Head]",
      "      : never",
      "    : P extends keyof T",
      "      ? T[P]",
      "      : never;",
      "",
      "type User = { address: { street: string } };",
      "type Test = PathValue<User, 'address.street'>;",
      "// Erwartet: string",
      "// Bekommt: { street: string } — FALSCH!",
    ].join("\n"),
    errorMessage: undefined,
    bugType: "logic-error",
    bugLine: 4,
    options: [
      "infer funktioniert nicht mit Punkt-getrennten Strings",
      "Head extends keyof T ist falsch",
      "Zeile 4 gibt T[Head] zurueck statt rekursiv PathValue<T[Head], Tail> aufzurufen",
      "P extends keyof T in Zeile 6 ist falsch",
    ],
    correctOption: 2,
    hints: [
      "Was ist T[Head] bei 'address.street'? → { street: string }. Aber wir wollen string.",
      "Bei einem Punkt-getrennten Pfad muss man TIEFER gehen: PathValue<T[Head], Tail>.",
      "T[Head] ist das Zwischen-Objekt, nicht der Endwert. Die Rekursion fehlt.",
    ],
    fixedCode: [
      "type PathValue<T, P extends string> =",
      "  P extends `${infer Head}.${infer Tail}`",
      "    ? Head extends keyof T",
      "      ? PathValue<T[Head], Tail>",
      "      // ^ REKURSION: Gehe tiefer mit dem Rest-Pfad",
      "      : never",
      "    : P extends keyof T",
      "      ? T[P]",
      "      : never;",
      "",
      "type User = { address: { street: string } };",
      "type Test = PathValue<User, 'address.street'>;",
      "// Jetzt korrekt: string",
    ].join("\n"),
  },
];
