/**
 * Lektion 10 — Tracing-Exercises: Review Challenge
 *
 * 4 integrierte Tracing-Uebungen die Konzepte aus allen Lektionen kombinieren.
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  {
    id: "10-full-pipeline",
    title: "Vollstaendige Typ-Pipeline: unknown -> Type Guard -> typsicher",
    description: "Verfolge wie unbekannte Daten durch Type Guards typsicher werden.",
    code: [
      "interface Product { name: string; price: number; }",
      "",
      "function isProduct(data: unknown): data is Product {",
      "  return typeof data === 'object' && data !== null && 'name' in data && 'price' in data;",
      "}",
      "",
      "const raw: unknown = JSON.parse('{\"name\": \"Laptop\", \"price\": 999}');",
      "// raw hat Typ: unknown",
      "",
      "if (isProduct(raw)) {",
      "  console.log(`${raw.name}: ${raw.price} EUR`);",
      "  // raw hat Typ: Product",
      "}",
    ],
    steps: [
      {
        lineIndex: 6,
        question: "Welchen Typ hat raw nach JSON.parse? (L02)",
        expectedAnswer: "unknown — JSON.parse gibt any zurueck, aber wir annotieren unknown",
        variables: { "raw": "(Typ: unknown)" },
        explanation: "JSON.parse gibt technisch any zurueck. Mit unknown-Annotation erzwingen wir Pruefung.",
      },
      {
        lineIndex: 9,
        question: "Welchen Typ hat raw INNERHALB des if-Blocks? (L06)",
        expectedAnswer: "Product — der Type Guard hat den Typ verengt",
        variables: { "raw": "(Typ: Product)" },
        explanation: "isProduct gibt 'data is Product' zurueck. Bei true verengt TypeScript auf Product.",
      },
      {
        lineIndex: 10,
        question: "Was wird ausgegeben?",
        expectedAnswer: "'Laptop: 999 EUR'",
        variables: {},
        explanation: "raw.name und raw.price sind jetzt typsicher zugreifbar.",
      },
    ],
    concept: "unknown -> Type Guard -> typsicher (L02+L06)",
    difficulty: 2,
  },

  {
    id: "10-widening-chain",
    title: "Widening-Kette: const, let, as const, satisfies",
    description: "Verfolge wie verschiedene Deklarationen den Typ beeinflussen.",
    code: [
      "const a = 'hello';",
      "let b = 'hello';",
      "const c = 'hello' as const;",
      "let d = 'hello' as const;",
      "",
      "const obj1 = { method: 'GET' };",
      "const obj2 = { method: 'GET' } as const;",
      "",
      "type Method = 'GET' | 'POST';",
      "const obj3 = { method: 'GET' } satisfies { method: Method };",
    ],
    steps: [
      {
        lineIndex: 0,
        question: "Welchen Typ hat a? (L03/L09)",
        expectedAnswer: "'hello' (Literal Type — const mit Primitive)",
        variables: { "a": "(Typ: 'hello')" },
        explanation: "const mit Primitive inferiert den Literal-Typ.",
      },
      {
        lineIndex: 1,
        question: "Welchen Typ hat b?",
        expectedAnswer: "string (Widening — let kann geaendert werden)",
        variables: { "a": "'hello'", "b": "(Typ: string)" },
        explanation: "let widened zu string weil der Wert spaeter geaendert werden koennte.",
      },
      {
        lineIndex: 3,
        question: "Welchen Typ hat d?",
        expectedAnswer: "'hello' (as const verhindert Widening auch bei let)",
        variables: { "d": "(Typ: 'hello')" },
        explanation: "as const erzwingt den Literal-Typ — auch bei let.",
      },
      {
        lineIndex: 5,
        question: "Welchen Typ hat obj1.method?",
        expectedAnswer: "string (Property Widening bei Objekten)",
        variables: { "obj1.method": "(Typ: string)" },
        explanation: "Objekt-Properties werden geweitert — auch bei const. Das Objekt ist const, seine Properties nicht.",
      },
      {
        lineIndex: 6,
        question: "Welchen Typ hat obj2.method?",
        expectedAnswer: "'GET' (as const behaelt Literal-Typ)",
        variables: { "obj2.method": "(Typ: 'GET')" },
        explanation: "as const macht alles readonly UND behaelt Literal-Typen.",
      },
    ],
    concept: "widening-chain (L03+L09)",
    difficulty: 3,
  },

  {
    id: "10-discriminated-union-flow",
    title: "Discriminated Union Narrowing-Fluss",
    description: "Verfolge wie sich der Typ durch einen switch-Ausdruck veraendert.",
    code: [
      "type Action =",
      "  | { type: 'add'; item: string }",
      "  | { type: 'remove'; index: number }",
      "  | { type: 'clear' };",
      "",
      "function reducer(items: string[], action: Action): string[] {",
      "  switch (action.type) {",
      "    case 'add': return [...items, action.item];",
      "    case 'remove': return items.filter((_, i) => i !== action.index);",
      "    case 'clear': return [];",
      "    default: const _: never = action; return _;",
      "  }",
      "}",
      "",
      "let state = ['A', 'B', 'C'];",
      "state = reducer(state, { type: 'add', item: 'D' });",
      "state = reducer(state, { type: 'remove', index: 1 });",
    ],
    steps: [
      {
        lineIndex: 7,
        question: "Welchen Typ hat action im case 'add'? Welche Properties sind zugreifbar?",
        expectedAnswer: "{ type: 'add'; item: string } — action.item ist zugreifbar",
        variables: { "action": "(Typ: { type: 'add'; item: string })" },
        explanation: "switch verengt auf das Mitglied mit type: 'add'. action.item ist jetzt sicher.",
      },
      {
        lineIndex: 15,
        question: "Was ist state nach reducer(state, { type: 'add', item: 'D' })?",
        expectedAnswer: "['A', 'B', 'C', 'D']",
        variables: { "state": "['A', 'B', 'C', 'D']" },
        explanation: "case 'add' fuegt item 'D' ans Ende hinzu.",
      },
      {
        lineIndex: 16,
        question: "Was ist state nach reducer(state, { type: 'remove', index: 1 })?",
        expectedAnswer: "['A', 'C', 'D'] — Index 1 ('B') wurde entfernt",
        variables: { "state": "['A', 'C', 'D']" },
        explanation: "case 'remove' filtert den Index 1 heraus. 'B' wird entfernt.",
      },
    ],
    concept: "discriminated-union-reducer (L07)",
    difficulty: 3,
  },

  {
    id: "10-intersection-extends-flow",
    title: "Interface extends vs Intersection — Typ-Aufbau",
    description: "Verfolge wie extends und & Typen zusammenbauen.",
    code: [
      "interface Base { id: string; createdAt: Date; }",
      "interface User extends Base { name: string; email: string; }",
      "type AdminMixin = { permissions: string[]; isSuperAdmin: boolean; };",
      "type Admin = User & AdminMixin;",
      "",
      "const admin: Admin = {",
      "  id: '1', createdAt: new Date(),",
      "  name: 'Max', email: 'max@admin.de',",
      "  permissions: ['read', 'write', 'delete'],",
      "  isSuperAdmin: true,",
      "};",
    ],
    steps: [
      {
        lineIndex: 0,
        question: "Welche Properties hat Base?",
        expectedAnswer: "id: string, createdAt: Date",
        variables: { "Base": "{ id: string; createdAt: Date }" },
        explanation: "Base definiert die Basis-Properties.",
      },
      {
        lineIndex: 1,
        question: "Welche Properties hat User? (L08: extends)",
        expectedAnswer: "id, createdAt (geerbt) + name, email (eigen) = 4 Properties",
        variables: { "User": "{ id: string; createdAt: Date; name: string; email: string }" },
        explanation: "extends erbt alle Properties von Base und fuegt name + email hinzu.",
      },
      {
        lineIndex: 3,
        question: "Welche Properties hat Admin? (L07: &)",
        expectedAnswer: "Alle 4 von User + permissions + isSuperAdmin = 6 Properties",
        variables: { "Admin": "User & AdminMixin — alle 6 Properties" },
        explanation: "Intersection kombiniert alle Properties aus User und AdminMixin.",
      },
    ],
    concept: "extends-intersection-combined (L07+L08)",
    difficulty: 2,
  },
];
