// misconceptions.ts — L25: Type-safe Error Handling
export const misconceptions = [
  { id: 1, concept: "result-vs-throw", misconception: "Result<T,E> completely replaces throw — you should never throw again.", correction: "throw remains correct for: bugs/invariant violations, initialization errors (missing env vars), and as a boundary wrapper for external systems. Result is for EXPECTED errors.", example: "throw new Error('DB_URL missing') // Correct — app cannot start\nreturn err({ type: 'USER_NOT_FOUND' }) // Correct — expected case" },
  { id: 2, concept: "ok-boolean-widening", misconception: "{ ok: true, value: user } automatically creates a Discriminated Union.", correction: "TypeScript infers `ok: boolean` (not `ok: true`) — too broad for narrowing. Use either `ok: true as const` or helper function `ok()`.", example: "const r = { ok: true, value: 42 }; // ok: boolean — NO narrowing!\nconst r2 = { ok: true as const, value: 42 }; // ok: true — Narrowing ✅" },
  { id: 3, concept: "option-is-result", misconception: "Option<T> and Result<T, E> are the same — just different names.", correction: "Option = 'maybe a value' (null = normal state). Result = 'operation that can fail' (error = error with details). findUser → Option. createUser → Result.", example: "findUser('id'): User | null // Option — null = normal\ncreateUser(data): Result<User, ValidationError> // Result — Err = error" },
  { id: 4, concept: "assertnever-runtime-only", misconception: "assertNever is only for runtime safety — no compile-time effect.", correction: "assertNever is primarily for compile-time exhaustiveness. The `never` parameter enforces that all union variants have been handled — at compile time. At runtime, assertNever should NEVER be called (if code is correct).", example: "switch(err.type) { case 'X': ... default: return assertNever(err) }\n// If 'Y' is added to ApiError → COMPILE-ERROR in the default line" },
  { id: 5, concept: "map-vs-flatmap", misconception: "mapResult and flatMapResult are identical — just different names.", correction: "map: fn returns U → Result<U, E>. flatMap: fn returns Result<U, E> → Result<U, E> (not Result<Result<U,E>,E>). If fn can fail itself → flatMap.", example: "mapResult(r, v => v.length) // fn returns number — Map ✅\nflatMapResult(r, v => parseEmail(v)) // fn returns Result — FlatMap ✅" },
  { id: 6, concept: "strictnullchecks-optional", misconception: "strictNullChecks is optional and only needed for large projects.", correction: "strictNullChecks is the most important TypeScript setting. It makes null/undefined into real types that must be handled. Without it, every string variable is implicitly also null/undefined — no protection against null reference exceptions.", example: "// Without strictNullChecks:\nconst name: string = null; // No error! Crash later.\n// With strictNullChecks:\nconst name: string | null = null; // Explicit, safe" },
  { id: 7, concept: "satisfies-vs-annotation", misconception: "satisfies Record<K,V> and `: Record<K,V>` are identical.", correction: "satisfies: checks completeness AND retains specific types (literal types). Annotation `: Record<K,V>`: checks completeness BUT loses specific types (all values become V).", example: "const x = { A: 'hello' } satisfies Record<Status, string>;\n// x.A has type 'hello' (literal!)\nconst y: Record<Status, string> = { A: 'hello' };\n// y.A has type 'string' (wider)" },
  { id: 8, concept: "catch-variable-type", misconception: "In try/catch the error always has type Error — I can use error.message directly.", correction: "With strict: true, error has type `unknown`. You must check `instanceof Error` before accessing .message. Not every throw throws an Error object — throw 'string' is valid JS.", example: "try { ... } catch (error) {\n  error.message // ❌ COMPILE-ERROR: error is 'unknown'\n  if (error instanceof Error) {\n    error.message // ✅ Narrowing to Error\n  }\n}" }
];