/**
 * Lektion 19 — Completion Problems: Modules & Declarations
 */
export interface CompletionProblem { id: string; title: string; description: string; template: string; solution: string; blanks: { placeholder: string; answer: string; hint: string }[]; concept: string; }

export const completionProblems: CompletionProblem[] = [
  { id: "19-cp-type-import", title: "Type-Only Import", description: "Vervollstaendige den Type-Only Import.", template: `import ______ { User, Config } from './types';`, solution: `import type { User, Config } from './types';`, blanks: [{ placeholder: "______", answer: "type", hint: "Welches Keyword macht den Import type-only?" }], concept: "Type-Only Import" },
  { id: "19-cp-declare-module", title: "Module Declaration", description: "Vervollstaendige die Declaration fuer eine externe Library.", template: `______ module 'my-lib' {\n  export function init(config: Config): void;\n  export ______ Config { debug: boolean; }\n}`, solution: `declare module 'my-lib' {\n  export function init(config: Config): void;\n  export interface Config { debug: boolean; }\n}`, blanks: [{ placeholder: "______", answer: "declare", hint: "Welches Keyword leitet eine Deklaration ein?" }, { placeholder: "______", answer: "interface", hint: "Welches Keyword definiert einen Objekt-Typ?" }], concept: "declare module" },
  { id: "19-cp-global-aug", title: "Global Augmentation", description: "Vervollstaendige die globale Erweiterung.", template: `declare ______ {\n  interface Window {\n    __APP_VERSION__: string;\n  }\n}\n\n______ {};`, solution: `declare global {\n  interface Window {\n    __APP_VERSION__: string;\n  }\n}\n\nexport {};`, blanks: [{ placeholder: "______", answer: "global", hint: "Welches Keyword erweitert den globalen Scope?" }, { placeholder: "______", answer: "export", hint: "Welches Keyword macht die Datei zum Modul?" }], concept: "Global Augmentation" },
  { id: "19-cp-barrel", title: "Barrel File", description: "Vervollstaendige die Re-Exports.", template: `// index.ts\n______ { UserService } from './user-service';\n______ { ProductService } from './product-service';\nexport ______ { User, Product } from './types';`, solution: `// index.ts\nexport { UserService } from './user-service';\nexport { ProductService } from './product-service';\nexport type { User, Product } from './types';`, blanks: [{ placeholder: "______", answer: "export", hint: "Welches Keyword re-exportiert aus einem anderen Modul?" }, { placeholder: "______", answer: "export", hint: "Gleich wie oben — Re-Export." }, { placeholder: "______", answer: "type", hint: "Welches Keyword markiert den Export als type-only?" }], concept: "Barrel File / Re-Exports" },
  { id: "19-cp-css-module", title: "CSS Module Declaration", description: "Vervollstaendige die Wildcard Declaration.", template: `declare module '______.module.css' {\n  const classes: Record<string, ______>;\n  export ______ classes;\n}`, solution: `declare module '*.module.css' {\n  const classes: Record<string, string>;\n  export default classes;\n}`, blanks: [{ placeholder: "______", answer: "*", hint: "Welches Zeichen steht fuer 'beliebiger Dateiname'?" }, { placeholder: "______", answer: "string", hint: "Welchen Typ haben CSS-Klassennamen?" }, { placeholder: "______", answer: "default", hint: "Welches Export-Keyword fuer den Haupt-Export?" }], concept: "Wildcard Declaration" },
  { id: "19-cp-env", title: "Typsichere Environment Variables", description: "Vervollstaendige die ProcessEnv-Erweiterung.", template: `declare global {\n  namespace ______ {\n    interface ______ {\n      NODE_ENV: 'development' | 'production';\n      DATABASE_URL: string;\n    }\n  }\n}\nexport {};`, solution: `declare global {\n  namespace NodeJS {\n    interface ProcessEnv {\n      NODE_ENV: 'development' | 'production';\n      DATABASE_URL: string;\n    }\n  }\n}\nexport {};`, blanks: [{ placeholder: "______", answer: "NodeJS", hint: "In welchem Namespace liegt ProcessEnv?" }, { placeholder: "______", answer: "ProcessEnv", hint: "Wie heisst das Interface fuer Umgebungsvariablen?" }], concept: "ProcessEnv Augmentation" },
];
