/**
 * Lektion 19 — Debugging Challenges: Modules & Declarations
 */
import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  { id: "L19-D1", title: "Augmentation ohne export", buggyCode: "// env.d.ts\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv { API_KEY: string; }\n  }\n}\n// Kein export! Augmentation funktioniert nicht.", bugType: "logic-error", bugLine: 1, options: ["Datei ist kein Modul — declare global braucht export {} am Ende", "declare global ist falsch", "namespace NodeJS existiert nicht", "ProcessEnv ist readonly"], correctOption: 0, hints: ["Ist diese Datei ein Modul oder ein Script?", "Ohne import/export wird sie als Script behandelt."], fixedCode: "// env.d.ts\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv { API_KEY: string; }\n  }\n}\nexport {};", explanation: "declare global funktioniert nur in Modulen. Ohne export {} ist die Datei ein Script und die Augmentation wird ignoriert.", concept: "module-vs-script", difficulty: 2 },
  { id: "L19-D2", title: "Implementierung in .d.ts", buggyCode: "// math.d.ts\nexport function add(a: number, b: number): number {\n  return a + b; // Error!\n}", bugType: "type-error", bugLine: 2, options: [".d.ts Dateien duerfen keine Implementierung enthalten — nur Deklarationen", "Die Funktion ist falsch", "export ist nicht erlaubt in .d.ts", "number ist falsch"], correctOption: 0, hints: ["Was darf in einer .d.ts Datei stehen?", "Nur Typ-Deklarationen, keine Funktionskoerper."], fixedCode: "// math.d.ts\nexport declare function add(a: number, b: number): number;", explanation: ".d.ts Dateien enthalten nur Deklarationen. Funktionskoerper und andere Implementierungsdetails sind nicht erlaubt.", concept: "dts-no-implementation", difficulty: 1 },
  { id: "L19-D3", title: "Default Import ohne esModuleInterop", buggyCode: "// tsconfig: esModuleInterop: false\nimport lodash from 'lodash';\n// Error: Module has no default export", bugType: "type-error", bugLine: 2, options: ["CJS-Module haben keinen Default-Export — esModuleInterop: true noetig", "lodash ist nicht installiert", "import-Syntax ist falsch", "lodash hat keine Typen"], correctOption: 0, hints: ["Wie exportiert lodash? module.exports = { ... }", "Ohne esModuleInterop gibt es keinen Default-Export fuer CJS."], fixedCode: "// Option 1: esModuleInterop: true in tsconfig.json\nimport lodash from 'lodash';\n\n// Option 2: Namespace Import\nimport * as lodash from 'lodash';", explanation: "CJS module.exports ist kein ES Module Default Export. esModuleInterop fuegt Helfer hinzu die den CJS-Export als Default-Export behandeln.", concept: "esmoduleinterop", difficulty: 2 },
  { id: "L19-D4", title: "Fehlende @types", buggyCode: "import express from 'express';\n// Error: Could not find a declaration file for module 'express'\n// Try: npm i @types/express", bugType: "type-error", bugLine: 1, options: ["express hat keine eingebauten Typen — @types/express installieren", "express ist nicht installiert", "import-Syntax ist falsch", "TypeScript kann kein JavaScript importieren"], correctOption: 0, hints: ["Hat express eingebaute .d.ts Dateien?", "npm install @types/express installiert Community-Typen."], fixedCode: "// Terminal: npm install @types/express\nimport express from 'express';\n// Jetzt mit vollen Typen!", explanation: "Viele Libraries (besonders aeltere) haben keine eingebauten Typen. @types-Pakete von DefinitelyTyped schliessen diese Luecke.", concept: "types-packages", difficulty: 1 },
  { id: "L19-D5", title: "Zirkulaerer Import durch Barrel File", buggyCode: "// types/index.ts (Barrel)\nexport * from './user';\nexport * from './product';\n\n// user.ts\nimport { Product } from './index'; // Zirkulaer!\n\n// product.ts\nimport { User } from './index'; // Zirkulaer!", bugType: "logic-error", bugLine: 6, options: ["Barrel File erzeugt zirkulaere Imports — direkte Imports verwenden", "export * ist falsch", "Die Typen sind falsch", "TypeScript unterstuetzt keine Re-Exports"], correctOption: 0, hints: ["Was passiert wenn user.ts aus index.ts importiert und index.ts aus user.ts?", "Zirkulaere Imports: A importiert B das A importiert."], fixedCode: "// user.ts — direkt importieren statt ueber Barrel\nimport { Product } from './product';\n\n// product.ts\nimport { User } from './user';", explanation: "Barrel Files koennen zirkulaere Abhaengigkeiten erzeugen wenn Module sich gegenseitig ueber den Barrel importieren. Loesung: direkte Imports zwischen Modulen.", concept: "circular-barrel-imports", difficulty: 3 },
];
