/**
 * Lektion 19 — Fehlkonzeption-Exercises: Modules & Declarations
 */
export interface Misconception { id: string; title: string; code: string; commonBelief: string; reality: string; concept: string; difficulty: number; }

export const misconceptions: Misconception[] = [
  { id: "19-declare-creates-code", title: "declare erzeugt JavaScript-Code", code: `declare const API_URL: string;\n// "Jetzt existiert API_URL im JavaScript"`, commonBelief: "declare erstellt Variablen im generierten JavaScript.", reality: "declare erzeugt KEINEN Code. Es informiert TypeScript nur ueber Werte die woanders existieren (z.B. durch ein Script-Tag oder eine globale Variable). Beim Compilieren wird declare komplett entfernt.", concept: "declare = nur Typ-Information", difficulty: 1 },
  { id: "19-dts-is-typescript", title: ".d.ts Dateien enthalten TypeScript-Code", code: `// math.d.ts\nexport function add(a: number, b: number): number {\n  return a + b; // Error in .d.ts!\n}`, commonBelief: ".d.ts Dateien sind normale TypeScript-Dateien.", reality: ".d.ts Dateien enthalten NUR Typ-Deklarationen — keine Implementierung. Funktionskoerper, Variablen-Initialisierungen und andere Implementierungsdetails sind nicht erlaubt. Sie beschreiben die Form, nicht die Logik.", concept: ".d.ts = nur Deklarationen", difficulty: 1 },
  { id: "19-default-export-best", title: "Default Exports sind besser als Named Exports", code: `// Default Export\nexport default class UserService { ... }\n// Import: import MyService from './user-service'; // Jeder Name moeglich!`, commonBelief: "Default Exports sind die bevorzugte Export-Art.", reality: "Named Exports sind in den meisten Faellen besser: Der Name ist konsistent, IDE-Autocompletion funktioniert besser, Refactoring ist sicherer. Default Exports erlauben beliebige Namen beim Import — das fuehrt zu Inkonsistenzen.", concept: "Named vs Default Exports", difficulty: 2 },
  { id: "19-barrel-always-good", title: "Barrel Files sind immer eine gute Idee", code: `// index.ts (Barrel)\nexport * from './huge-module-a';\nexport * from './huge-module-b';\nexport * from './huge-module-c';\n// Importiert ALLES, auch wenn nur 1 Funktion gebraucht wird`, commonBelief: "Barrel Files verbessern immer die Code-Organisation.", reality: "Barrel Files koennen Tree-Shaking beeintraechtigen und zu groesseren Bundles fuehren. Der Bundler muss alle Exports analysieren, auch wenn nur ein kleiner Teil importiert wird. Bei Performance-kritischen Projekten: direkte Imports bevorzugen.", concept: "Barrel Files und Tree-Shaking", difficulty: 3 },
  { id: "19-augmentation-without-module", title: "Augmentation funktioniert ohne export", code: `// env.d.ts (KEIN export/import!)\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv { API_KEY: string; }\n  }\n}\n// Funktioniert nicht! Die Datei ist kein Modul.`, commonBelief: "declare global funktioniert in jeder Datei.", reality: "declare global funktioniert NUR in Modulen (Dateien mit import oder export). Ohne export {} wird die Datei als Script behandelt und die Augmentation wird ignoriert. Die Loesung: `export {}` am Ende.", concept: "Module vs Script Context", difficulty: 3 },
  { id: "19-types-override", title: "@types ueberschreibt eingebaute Typen", code: `npm install @types/react\n// "Jetzt hat React NEUE Typen"`, commonBelief: "@types ersetzt die Typen einer Library komplett.", reality: "@types ERGAENZT fehlende Typen. Wenn eine Library bereits eingebaute Typen hat (.d.ts im Paket), werden @types normalerweise nicht benoetigt und koennen sogar Konflikte verursachen. Erst @types pruefen ob die Library nicht schon Typen mitbringt.", concept: "@types vs eingebaute Typen", difficulty: 2 },
  { id: "19-namespace-vs-module", title: "Namespaces und Module sind dasselbe", code: `namespace MyLib { export function doSomething() {} }\n// vs\nexport function doSomething() {}`, commonBelief: "Namespaces sind die TypeScript-Art Module zu schreiben.", reality: "Namespaces sind ein aelteres TypeScript-Feature. In modernem Code sollte man ES Modules (import/export) verwenden. Namespaces sind nur noch fuer spezielle Faelle relevant: globale Augmentation (declare namespace) und Legacy-Code.", concept: "Namespaces vs ES Modules", difficulty: 2 },
  { id: "19-import-type-optional", title: "import type ist optional und unnoetig", code: `import { User } from './types'; // Normal\nimport type { User } from './types'; // Type-Only\n// "Beide machen das Gleiche"`, commonBelief: "import type ist nur syntaktischer Zucker ohne Effekt.", reality: "import type hat echte Auswirkungen: 1) Es wird beim Compilieren komplett entfernt (kein JS-Import). 2) Es verhindert ungewollte Side-Effects. 3) Es ist mit isolatedModules kompatibel. 4) Es dokumentiert die Absicht. Bei Libraries mit Side-Effects kann der Unterschied wichtig sein.", concept: "import type Semantik", difficulty: 3 },
];
