/**
 * Lektion 19 — Pre-Test-Fragen: Modules & Declarations
 */
export interface PretestQuestion { sectionIndex: number; question: string; options: string[]; correct: number; briefExplanation: string; }

export const pretestQuestions: PretestQuestion[] = [
  { sectionIndex: 1, question: "Was ist der Vorteil von Named Exports gegenueber Default Exports?", options: ["Performance", "Konsistenter Name, refactoring-sicher", "Mehr Features", "Ich weiss es nicht"], correct: 1, briefExplanation: "Named Exports haben einen festen Namen der beim Refactoring konsistent bleibt." },
  { sectionIndex: 1, question: "Was macht `import type`?", options: ["Importiert Klassen", "Importiert NUR Typen — wird beim Compilieren entfernt", "Importiert alles", "Ich weiss es nicht"], correct: 1, briefExplanation: "Type-Only Imports werden komplett entfernt und erzeugen keinen JS-Code." },
  { sectionIndex: 1, question: "Was ist ein Barrel File?", options: ["Eine ZIP-Datei", "Eine index.ts die Exports buendelt", "Ein Config-File", "Ich weiss es nicht"], correct: 1, briefExplanation: "Barrel Files re-exportieren Module eines Verzeichnisses fuer einfacheren Import." },
  { sectionIndex: 2, question: "Was macht esModuleInterop?", options: ["Deaktiviert Module", "Ermoeglicht Default-Imports aus CJS-Modulen", "Schnellerer Build", "Ich weiss es nicht"], correct: 1, briefExplanation: "esModuleInterop macht CJS module.exports als Default-Import nutzbar." },
  { sectionIndex: 2, question: "Was ist der Unterschied zwischen CJS und ESM?", options: ["Kein Unterschied", "CJS: require/module.exports, ESM: import/export", "CJS ist neuer", "Ich weiss es nicht"], correct: 1, briefExplanation: "CJS ist das aeltere Node.js-Format, ESM ist der moderne Standard." },
  { sectionIndex: 2, question: "Was macht moduleResolution: 'bundler'?", options: ["Bundelt Code", "Nutzt package.json exports, optimiert fuer Vite/Webpack", "Deaktiviert Resolution", "Ich weiss es nicht"], correct: 1, briefExplanation: "bundler ist die moderne Resolution-Strategie fuer Bundler-basierte Projekte." },
  { sectionIndex: 3, question: "Was ist eine .d.ts Datei?", options: ["JavaScript", "Declaration File — nur Typen, keine Implementierung", "Config", "Ich weiss es nicht"], correct: 1, briefExplanation: ".d.ts beschreibt die Typen eines Moduls ohne ausfuehrbaren Code." },
  { sectionIndex: 3, question: "Was macht declare?", options: ["Deklariert Variablen", "Sagt TypeScript: dieser Wert existiert woanders", "Erstellt Klassen", "Ich weiss es nicht"], correct: 1, briefExplanation: "declare informiert TypeScript ueber externe Werte ohne Code zu erzeugen." },
  { sectionIndex: 3, question: "Was ist @types/lodash?", options: ["Lodash selbst", "Community-gepflegte Typen fuer Lodash von DefinitelyTyped", "Ein Fork", "Ich weiss es nicht"], correct: 1, briefExplanation: "@types Pakete enthalten Typ-Definitionen fuer untypisierte Libraries." },
  { sectionIndex: 4, question: "Was ist Module Augmentation?", options: ["Module loeschen", "Bestehende Module um neue Typen erweitern", "Module erstellen", "Ich weiss es nicht"], correct: 1, briefExplanation: "Module Augmentation nutzt Interface Merging um bestehende Typen zu erweitern." },
  { sectionIndex: 4, question: "Warum braucht eine Augmentation-Datei export {}?", options: ["Best Practice", "Damit die Datei als Modul behandelt wird", "Performance", "Ich weiss es nicht"], correct: 1, briefExplanation: "Ohne export/import ist die Datei ein Script und Augmentation funktioniert nicht." },
  { sectionIndex: 4, question: "Was ist Interface Merging?", options: ["Vererbung", "Automatisches Zusammenfuegen von Interfaces mit gleichem Namen", "Design Pattern", "Ich weiss es nicht"], correct: 1, briefExplanation: "TypeScript merged Interfaces mit gleichem Namen automatisch — auch ueber Dateigrenzen." },
  { sectionIndex: 5, question: "Was ist declare module '*.css'?", options: ["CSS-Import", "Wildcard Declaration fuer alle .css Imports", "CSS-in-JS", "Ich weiss es nicht"], correct: 1, briefExplanation: "Wildcard Declarations definieren Typen fuer alle Imports eines Patterns." },
  { sectionIndex: 5, question: "Wann sollte man Barrel Files vermeiden?", options: ["Nie", "Wenn Tree-Shaking wichtig ist", "Immer", "Ich weiss es nicht"], correct: 1, briefExplanation: "Barrel Files koennen Tree-Shaking erschweren weil sie alles importieren." },
  { sectionIndex: 5, question: "Was ist die beste Praxis fuer Typ-Organisation?", options: ["Alles in einer Datei", "Typen pro Feature in eigenen Dateien, gemeinsame in types/", "Keine Typen", "Ich weiss es nicht"], correct: 1, briefExplanation: "Feature-basierte Organisation mit gemeinsamen Typen in einem types-Verzeichnis." },
];
