/**
 * Lektion 19 — Tracing-Exercises: Modules & Declarations
 */
import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  { id: "19-module-resolution", title: "Module Resolution Schritt fuer Schritt", description: "Verfolge wie TypeScript ein Modul aufloest.", code: ["import { UserService } from './services';", "", "// TypeScript sucht:", "// 1. ./services.ts", "// 2. ./services.tsx", "// 3. ./services/index.ts", "// 4. ./services/index.tsx"], steps: [{ lineIndex: 0, question: "Was sucht TypeScript zuerst?", expectedAnswer: "./services.ts (direkte Datei mit .ts Extension)", variables: { "Schritt 1": "./services.ts" }, explanation: "TypeScript versucht zuerst die direkte Datei mit .ts Extension." }, { lineIndex: 0, question: "Was wenn ./services.ts nicht existiert?", expectedAnswer: "./services/index.ts (Verzeichnis mit index.ts)", variables: { "Schritt 3": "./services/index.ts" }, explanation: "Wenn die direkte Datei nicht gefunden wird, sucht TypeScript nach index.ts im Verzeichnis." }], concept: "module-resolution-order", difficulty: 1 },
  { id: "19-interface-merging", title: "Interface Merging ueber Dateien", description: "Verfolge wie Interface Merging funktioniert.", code: ["// file-a.ts", "interface Config { name: string; }", "", "// file-b.ts (Augmentation)", "interface Config { version: string; debug: boolean; }", "", "// Ergebnis:", "const cfg: Config = { name: 'App', version: '1.0', debug: true };"], steps: [{ lineIndex: 1, question: "Was hat Config nach file-a.ts?", expectedAnswer: "{ name: string; }", variables: { "Config": "{ name: string; }" }, explanation: "Erste Declaration: Config hat nur name." }, { lineIndex: 4, question: "Was hat Config nach file-b.ts?", expectedAnswer: "{ name: string; version: string; debug: boolean; }", variables: { "Config": "{ name: string; version: string; debug: boolean; }" }, explanation: "Interface Merging: Beide Declarations werden zusammengefuegt." }, { lineIndex: 7, question: "Welche Properties muss cfg haben?", expectedAnswer: "Alle drei: name, version, debug", variables: { "cfg": "{ name: 'App', version: '1.0', debug: true }" }, explanation: "Das gemergte Interface erfordert alle Properties aus beiden Declarations." }], concept: "interface-merging-trace", difficulty: 2 },
  { id: "19-type-import-erasure", title: "Type Import Erasure", description: "Verfolge was beim Compilieren passiert.", code: ["import { UserService } from './services';", "import type { User } from './types';", "", "const service = new UserService();", "const user: User = service.getUser('1');"], steps: [{ lineIndex: 0, question: "Bleibt dieser Import im JavaScript?", expectedAnswer: "Ja — UserService wird als Wert verwendet (new UserService())", variables: { "Import": "bleibt im JS" }, explanation: "UserService wird als Wert genutzt (Konstruktor-Aufruf). Der Import bleibt." }, { lineIndex: 1, question: "Bleibt dieser Import im JavaScript?", expectedAnswer: "Nein — import type wird beim Compilieren komplett entfernt", variables: { "Import": "wird entfernt" }, explanation: "import type Imports werden IMMER entfernt. User wird nur als Typ-Annotation genutzt." }, { lineIndex: 4, question: "Was bleibt im generierten JavaScript?", expectedAnswer: "const user = service.getUser('1'); (ohne Typ-Annotation)", variables: { "JS Output": "const user = service.getUser('1');" }, explanation: "Typ-Annotationen werden entfernt. Nur der Wert-Code bleibt." }], concept: "type-erasure", difficulty: 2 },
  { id: "19-augmentation-flow", title: "Augmentation Reihenfolge", description: "Verfolge wie Augmentation die Typen erweitert.", code: ["// express hat: interface Request { body: any; }", "", "// Unsere Augmentation:", "declare module 'express' {", "  interface Request {", "    user?: { id: string; role: string };", "    requestId: string;", "  }", "}", "", "// Ergebnis: Request hat body + user + requestId"], steps: [{ lineIndex: 0, question: "Was hat Request vor der Augmentation?", expectedAnswer: "body: any (und andere Express-Standard-Properties)", variables: { "Request": "{ body: any; params: ...; query: ...; ... }" }, explanation: "Express definiert Request mit Standard-Properties." }, { lineIndex: 3, question: "Was passiert in der Augmentation?", expectedAnswer: "Interface Merging: user und requestId werden zu Request hinzugefuegt", variables: { "Augmentation": "{ user?: ...; requestId: string; }" }, explanation: "Die neuen Properties werden durch Interface Merging ergaenzt." }, { lineIndex: 10, question: "Was hat Request nach der Augmentation?", expectedAnswer: "body + user + requestId (alle zusammen)", variables: { "Request": "{ body: any; user?: { id: string; role: string }; requestId: string; ... }" }, explanation: "Das Ergebnis ist die Vereinigung aller Properties aus Original und Augmentation." }], concept: "augmentation-merging", difficulty: 2 },
];
