/**
 * Lektion 19 — Transfer Tasks: Modules & Declarations
 */
import type { TransferTask } from "../tools/transfer-engine.ts";

export const transferTasks: TransferTask[] = [
  { id: "19-type-library", title: "Eigene Type Library erstellen", prerequisiteLessons: [16, 17, 18, 19], scenario: "Dein Team hat in 5 Projekten die gleichen Utility Types: DeepPartial, StrictOmit, RequiredBy. Jedes Projekt hat seine eigene Kopie — bei Aenderungen muessen alle synchron gehalten werden.", task: "Erstelle eine typsichere Utility-Type-Library:\n\n1. Erstelle eine Modul-Struktur mit index.ts (Barrel), types/ Verzeichnis\n2. Exportiere 5-10 Utility Types mit Named Exports\n3. Schreibe eine .d.ts fuer die kompilierte Version\n4. Erstelle ein package.json mit types-Feld\n5. Dokumentiere jeden Typ mit JSDoc", starterCode: "// TODO: Modul-Struktur, Utility Types, .d.ts, package.json", solutionCode: "// types/object.ts\nexport type DeepPartial<T> = {\n  [K in keyof T]?: T[K] extends object ? T[K] extends Function ? T[K] : DeepPartial<T[K]> : T[K];\n};\nexport type StrictOmit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;\nexport type PartialBy<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;\n\n// types/string.ts\nexport type Split<S extends string, D extends string> = S extends `${infer H}${D}${infer T}` ? [H, ...Split<T, D>] : [S];\n\n// index.ts (Barrel)\nexport type { DeepPartial, StrictOmit, PartialBy } from './types/object';\nexport type { Split } from './types/string';", conceptsBridged: ["Barrel File Organisation", "Type-Only Exports", "Modul-Struktur fuer Libraries", ".d.ts Generierung"], estimatedMinutes: 20, difficulty: 3 },
  { id: "19-framework-augmentation", title: "Framework-Augmentation fuer Express/Next.js", prerequisiteLessons: [19], scenario: "Dein Express-Backend hat 30 Middleware-Funktionen die req.user, req.session, req.logger etc. setzen. Ohne Augmentation sind diese Properties alle 'any' oder brauchen Casts.", task: "Erstelle ein vollstaendiges Augmentation-System:\n\n1. Erweitere Express Request um user, session, logger\n2. Erweitere ProcessEnv um alle Umgebungsvariablen\n3. Erstelle Declarations fuer 2 untypisierte Libraries\n4. Organisiere alles in einem types/ Verzeichnis", starterCode: "// TODO: Express Augmentation, ProcessEnv, Library Declarations", solutionCode: "// types/express.d.ts\nimport 'express';\ndeclare module 'express' {\n  interface Request {\n    user?: { id: string; role: 'admin' | 'user'; email: string };\n    session: { token: string; expiresAt: Date };\n    logger: { info: (msg: string) => void; error: (msg: string) => void };\n  }\n}\n\n// types/env.d.ts\ndeclare global {\n  namespace NodeJS {\n    interface ProcessEnv {\n      NODE_ENV: 'development' | 'production' | 'test';\n      PORT: string;\n      DATABASE_URL: string;\n      JWT_SECRET: string;\n    }\n  }\n}\nexport {};\n\n// types/untyped-lib.d.ts\ndeclare module 'my-metrics' {\n  export function track(event: string, data?: Record<string, unknown>): void;\n  export function init(apiKey: string): void;\n}", conceptsBridged: ["Module Augmentation fuer Express", "Global Augmentation fuer ProcessEnv", "declare module fuer untypisierte Libraries", "Typ-Organisation in types/ Verzeichnis"], estimatedMinutes: 20, difficulty: 3 },
];
