/**
 * Lektion 14 — Parson's Problems: Generic Patterns
 */

import type { ParsonsProblem } from "../tools/parsons-engine.ts";

export const parsonsProblems: ParsonsProblem[] = [
  {
    id: "L14-P1",
    title: "Generic Stack mit Iterator",
    description: "Ordne die Zeilen zu einer typsicheren Stack-Klasse mit Iterator-Support.",
    correctOrder: [
      "class Stack<T> {",
      "  private items: T[] = [];",
      "",
      "  push(item: T): void {",
      "    this.items.push(item);",
      "  }",
      "",
      "  pop(): T | undefined {",
      "    return this.items.pop();",
      "  }",
      "",
      "  *[Symbol.iterator](): Iterator<T> {",
      "    for (let i = this.items.length - 1; i >= 0; i--) {",
      "      yield this.items[i];",
      "    }",
      "  }",
      "}",
    ],
    distractors: [
      "  pop(): T {",
      "  *[Symbol.iterator](): Iterator<unknown> {",
    ],
    hint: "pop() gibt T | undefined zurueck (nicht T) und der Iterator gibt T zurueck (nicht unknown).",
    concept: "generic-stack-iterator",
    difficulty: 3,
  },

  {
    id: "L14-P2",
    title: "pipe() mit Overloads",
    description: "Ordne die Zeilen zu einer typsicheren pipe-Funktion mit Overloads.",
    correctOrder: [
      "function pipe<A, B>(v: A, f1: (a: A) => B): B;",
      "function pipe<A, B, C>(",
      "  v: A, f1: (a: A) => B, f2: (b: B) => C",
      "): C;",
      "function pipe(value: unknown, ...fns: Function[]): unknown {",
      "  return fns.reduce((v, fn) => fn(v), value);",
      "}",
    ],
    distractors: [
      "function pipe<T>(v: T, ...fns: ((v: T) => T)[]): T;",
      "  return fns.reduceRight((v, fn) => fn(v), value);",
    ],
    hint: "pipe braucht separate Typparameter (A, B, C) pro Schritt — nicht einen einzigen T. pipe verwendet reduce (nicht reduceRight — das waere compose).",
    concept: "pipe-overloads",
    difficulty: 4,
  },

  {
    id: "L14-P3",
    title: "TypedEventEmitter",
    description: "Ordne die Zeilen zu einem typsicheren Event Emitter.",
    correctOrder: [
      "class TypedEmitter<Events extends Record<string, unknown>> {",
      "  private listeners = new Map<string, Set<Function>>();",
      "",
      "  on<K extends keyof Events & string>(",
      "    event: K,",
      "    handler: (data: Events[K]) => void",
      "  ): void {",
      "    if (!this.listeners.has(event)) {",
      "      this.listeners.set(event, new Set());",
      "    }",
      "    this.listeners.get(event)!.add(handler);",
      "  }",
      "",
      "  emit<K extends keyof Events & string>(event: K, data: Events[K]): void {",
      "    this.listeners.get(event)?.forEach(h => h(data));",
      "  }",
      "}",
    ],
    distractors: [
      "  on(event: string, handler: Function): void {",
      "  emit(event: string, data: unknown): void {",
    ],
    hint: "Die generische Version verwendet K extends keyof Events (nicht plain string) und Events[K] (nicht unknown) fuer typsichere Event-Payloads.",
    concept: "typed-event-emitter",
    difficulty: 4,
  },

  {
    id: "L14-P4",
    title: "DI Container mit Token<T>",
    description: "Ordne die Zeilen zu einem typsicheren DI Container mit Phantom Types.",
    correctOrder: [
      "class Token<T> {",
      "  constructor(public readonly name: string) {}",
      "}",
      "",
      "class Container {",
      "  private bindings = new Map<Token<unknown>, () => unknown>();",
      "",
      "  bind<T>(token: Token<T>, factory: () => T): void {",
      "    this.bindings.set(token, factory);",
      "  }",
      "",
      "  resolve<T>(token: Token<T>): T {",
      "    const factory = this.bindings.get(token);",
      "    if (!factory) throw new Error(`No binding: ${token.name}`);",
      "    return factory() as T;",
      "  }",
      "}",
    ],
    distractors: [
      "  bind(key: string, factory: () => unknown): void {",
      "  resolve(key: string): unknown {",
    ],
    hint: "Token<T> ist der typsichere Schluessel — nicht ein plain string. bind/resolve verwenden Token<T> statt string fuer automatische Typ-Inferenz.",
    concept: "di-container-phantom-types",
    difficulty: 4,
  },
];
