/**
 * Lektion 14 — Tracing-Exercises: Generic Patterns
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  {
    id: "14-builder-type-growth",
    title: "Builder Typ-Wachstum durch Intersection",
    description: "Verfolge wie der Builder-Typ bei jedem set()-Aufruf waechst.",
    code: [
      "class Builder<T extends Record<string, unknown> = {}> {",
      "  constructor(private data: T = {} as T) {}",
      "  set<K extends string, V>(key: K, value: V): Builder<T & Record<K, V>> {",
      "    return new Builder({ ...this.data, [key]: value } as T & Record<K, V>);",
      "  }",
      "  build(): T { return { ...this.data }; }",
      "}",
      "",
      "const b1 = new Builder();",
      "const b2 = b1.set('name', 'Max');",
      "const b3 = b2.set('age', 30);",
      "const result = b3.build();",
    ],
    steps: [
      {
        lineIndex: 8,
        question: "Welchen Typ hat b1?",
        expectedAnswer: "Builder<{}>",
        variables: { "T": "{}", "b1": "Builder<{}>" },
        explanation: "Ohne Typargument nutzt der Builder den Default {} — ein leeres Objekt.",
      },
      {
        lineIndex: 9,
        question: "Welchen Typ hat b2 nach set('name', 'Max')?",
        expectedAnswer: "Builder<{} & Record<'name', string>> = Builder<{ name: string }>",
        variables: { "K": "'name'", "V": "string", "T": "{} & Record<'name', string>" },
        explanation: "set() gibt Builder<T & Record<K, V>> zurueck. Die Intersection erweitert den Typ um das Feld 'name'.",
      },
      {
        lineIndex: 10,
        question: "Welchen Typ hat b3 nach set('age', 30)?",
        expectedAnswer: "Builder<{ name: string } & Record<'age', number>> = Builder<{ name: string; age: number }>",
        variables: { "K": "'age'", "V": "number", "T": "{ name: string } & Record<'age', number>" },
        explanation: "Erneute Intersection: Der bestehende Typ wird um 'age: number' erweitert.",
      },
      {
        lineIndex: 11,
        question: "Welchen Typ hat result nach build()?",
        expectedAnswer: "{ name: string; age: number }",
        variables: { "result": "{ name: 'Max', age: 30 } (Typ: { name: string; age: number })" },
        explanation: "build() gibt T zurueck — alle aufgesammelten Intersections sind jetzt ein einziger Objekttyp.",
      },
    ],
    concept: "builder-type-growth",
    difficulty: 3,
  },

  {
    id: "14-pipe-type-chain",
    title: "pipe() Typ-Kette durch Overloads",
    description: "Verfolge wie pipe() bei jedem Schritt den Typ transformiert.",
    code: [
      "function pipe<A, B>(v: A, f1: (a: A) => B): B;",
      "function pipe<A, B, C>(v: A, f1: (a: A) => B, f2: (b: B) => C): C;",
      "function pipe(value: unknown, ...fns: Function[]): unknown {",
      "  return fns.reduce((v, fn) => fn(v), value);",
      "}",
      "",
      "const result = pipe(",
      "  'hello world',",
      "  (s) => s.split(' '),",
      "  (arr) => arr.length,",
      ");",
    ],
    steps: [
      {
        lineIndex: 7,
        question: "Was ist A (der Eingangstyp)?",
        expectedAnswer: "A = string",
        variables: { "A": "string", "value": "'hello world'" },
        explanation: "TypeScript inferiert A = string aus dem ersten Argument 'hello world'.",
      },
      {
        lineIndex: 8,
        question: "Was ist B nach dem ersten Funktionsschritt?",
        expectedAnswer: "B = string[]",
        variables: { "A": "string", "B": "string[]", "f1": "(s: string) => string[]" },
        explanation: "s.split(' ') gibt string[] zurueck, also ist B = string[].",
      },
      {
        lineIndex: 9,
        question: "Was ist C nach dem zweiten Schritt? Welcher Overload greift?",
        expectedAnswer: "C = number, Overload: pipe<string, string[], number>",
        variables: { "B": "string[]", "C": "number", "f2": "(arr: string[]) => number" },
        explanation: "arr.length gibt number zurueck. Der zweite Overload pipe<A,B,C> greift weil 2 Funktionen uebergeben wurden.",
      },
      {
        lineIndex: 6,
        question: "Welchen Typ hat result?",
        expectedAnswer: "number (Wert: 2)",
        variables: { "result": "2 (Typ: number)" },
        explanation: "pipe gibt C = number zurueck. 'hello world'.split(' ') = ['hello','world'], .length = 2.",
      },
    ],
    concept: "pipe-type-chain",
    difficulty: 3,
  },

  {
    id: "14-conditional-type-resolution",
    title: "Conditional Type Aufloesungsreihenfolge",
    description: "Verfolge wie TypeScript Conditional Types Schritt fuer Schritt aufloest.",
    code: [
      "type Format<T> =",
      "  T extends string ? 'text' :",
      "  T extends number ? 'numeric' :",
      "  T extends boolean ? 'flag' :",
      "  'unknown';",
      "",
      "type A = Format<string>;",
      "type B = Format<42>;",
      "type C = Format<true>;",
      "type D = Format<string | number>;",
      "type E = Format<never>;",
    ],
    steps: [
      {
        lineIndex: 6,
        question: "Was ist Format<string>?",
        expectedAnswer: "'text'",
        variables: { "T": "string", "A": "'text'" },
        explanation: "string extends string ist true — erster Branch greift: 'text'.",
      },
      {
        lineIndex: 7,
        question: "Was ist Format<42>?",
        expectedAnswer: "'numeric'",
        variables: { "T": "42", "B": "'numeric'" },
        explanation: "42 extends string ist false, 42 extends number ist true — zweiter Branch: 'numeric'.",
      },
      {
        lineIndex: 9,
        question: "Was ist Format<string | number>? (Achtung: Distributive!)",
        expectedAnswer: "'text' | 'numeric'",
        variables: { "T": "string | number", "D": "'text' | 'numeric'" },
        explanation: "Conditional Types VERTEILEN ueber Unions: Format<string> | Format<number> = 'text' | 'numeric'.",
      },
      {
        lineIndex: 10,
        question: "Was ist Format<never>?",
        expectedAnswer: "never",
        variables: { "T": "never", "E": "never" },
        explanation: "never ist der leere Union. Distribution ueber leeren Union = never. Das ist eine wichtige Sonderregel!",
      },
    ],
    concept: "conditional-type-distribution",
    difficulty: 4,
  },

  {
    id: "14-repository-type-flow",
    title: "Repository Pattern — Typ-Fluss bei CRUD",
    description: "Verfolge wie Omit und Partial den Typ bei verschiedenen CRUD-Operationen veraendern.",
    code: [
      "interface User { id: string; name: string; email: string; role: 'admin' | 'user'; }",
      "",
      "interface Repository<T extends { id: string }> {",
      "  create(data: Omit<T, 'id'>): T;",
      "  update(id: string, data: Partial<Omit<T, 'id'>>): T;",
      "  findById(id: string): T | undefined;",
      "}",
      "",
      "declare const repo: Repository<User>;",
      "const newUser = repo.create({ name: 'Max', email: 'max@test.de', role: 'user' });",
      "const updated = repo.update('1', { email: 'new@test.de' });",
      "const found = repo.findById('1');",
    ],
    steps: [
      {
        lineIndex: 9,
        question: "Welchen Typ hat der Parameter von create() bei Repository<User>?",
        expectedAnswer: "Omit<User, 'id'> = { name: string; email: string; role: 'admin' | 'user' }",
        variables: { "T": "User", "Omit<T, 'id'>": "{ name: string; email: string; role: 'admin' | 'user' }" },
        explanation: "Omit entfernt 'id' aus User. Der Aufrufer MUSS name, email und role angeben, KANN aber keine id setzen.",
      },
      {
        lineIndex: 10,
        question: "Welchen Typ hat der data-Parameter von update()?",
        expectedAnswer: "Partial<Omit<User, 'id'>> = { name?: string; email?: string; role?: 'admin' | 'user' }",
        variables: { "Partial<Omit<T, 'id'>>": "{ name?: string; email?: string; role?: 'admin' | 'user' }" },
        explanation: "Erst Omit (id entfernen), dann Partial (alle optional). Man kann einzelne Felder updaten.",
      },
      {
        lineIndex: 10,
        question: "Welchen Typ hat updated?",
        expectedAnswer: "User (vollstaendiges User-Objekt)",
        variables: { "updated": "Typ: User — update gibt das vollstaendige Objekt zurueck" },
        explanation: "update() gibt T = User zurueck — das vollstaendige Objekt mit allen Feldern, nicht nur die geaenderten.",
      },
      {
        lineIndex: 11,
        question: "Welchen Typ hat found?",
        expectedAnswer: "User | undefined",
        variables: { "found": "Typ: User | undefined — der User koennte nicht existieren" },
        explanation: "findById kann fehlschlagen (kein User mit dieser ID). undefined signalisiert diesen Fall.",
      },
    ],
    concept: "repository-crud-types",
    difficulty: 2,
  },
];
