/**
 * Lesson 23 — Debugging Challenges: Recursive Types
 *
 * 5 challenges on recursive types, deep operations, paths, and performance.
 */

import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  // ─── Challenge 1: Missing Base Case ──────────────────────────────
  {
    id: "L23-D1",
    title: "Circular Reference Instead of Recursion",
    buggyCode: [
      "// Attempt to define a 'nullable' type:",
      "type Nullable = Nullable | null;",
      "",
      "const value: Nullable = null;",
      "const other: Nullable = 'hello';",
    ].join("\n"),
    errorMessage: "Type alias 'Nullable' circularly references itself.",
    bugType: "type-error",
    bugLine: 2,
    options: [
      "null cannot appear in a union",
      "Direct circularity in type aliases is forbidden — recursion needs a property or conditional",
      "TypeScript does not support recursive types",
      "The type would need to be marked 'recursive'",
    ],
    correctOption: 1,
    hints: [
      "Compare: type X = X | null vs type X = { value: X | null }",
      "Recursion only works in certain contexts: properties, conditional types, mapped types.",
      "type Nullable<T> = T | null is not a recursive type — it is a union alias.",
    ],
    fixedCode: [
      "// Option A: Simple union alias (not recursive):",
      "type Nullable<T> = T | null;",
      "",
      "const value: Nullable<string> = null;",
      "const other: Nullable<string> = 'hello';",
    ].join("\n"),
  },

  // ─── Challenge 2: DeepPartial without Array Handling ─────────────────────────
  {
    id: "L23-D2",
    title: "DeepPartial Destroys Arrays",
    buggyCode: [
      "type DeepPartial<T> = {",
      "  [K in keyof T]?: T[K] extends object",
      "    ? DeepPartial<T[K]>",
      "    : T[K];",
      "};",
      "",
      "type Config = {",
      "  tags: string[];",
      "  nested: { items: number[] };",
      "};",
      "",
      "// Expected: tags?: string[]; nested?: { items?: number[] }",
      "// Gets: tags?: { length?: number; push?: ... } ???",
      "type PartialConfig = DeepPartial<Config>;",
    ].join("\n"),
    errorMessage: undefined,
    bugType: "logic-error",
    bugLine: 2,
    options: [
      "object does not include arrays",
      "Arrays are objects (typeof [] === 'object'), so they are recursively resolved instead of preserved as arrays",
      "DeepPartial only works for flat objects",
      "The mapped type does not iterate over array elements",
    ],
    correctOption: 1,
    hints: [
      "What does typeof [] return? → 'object'. So extends object also matches arrays.",
      "The solution: catch arrays BEFORE the object check.",
      "Use T[K] extends (infer U)[] ? DeepPartial<U>[] : ... to recognize arrays.",
    ],
    fixedCode: [
      "type DeepPartial<T> = {",
      "  [K in keyof T]?: T[K] extends (infer U)[]",
      "    ? DeepPartial<U>[]",
      "    : T[K] extends object",
      "      ? DeepPartial<T[K]>",
      "      : T[K];",
      "};",
      "",
      "type Config = {",
      "  tags: string[];",
      "  nested: { items: number[] };",
      "};",
      "",
      "// Now correct: tags?: string[]; nested?: { items?: number[] }",
      "type PartialConfig = DeepPartial<Config>;",
    ].join("\n"),
  },

  // ─── Challenge 3: Paths Captures Array Properties ─────────────────────────
  {
    id: "L23-D3",
    title: "Paths Lists Array Methods as Paths",
    buggyCode: [
      "type Paths<T> = T extends object",
      "  ? { [K in keyof T & string]: K | `${K}.${Paths<T[K]>}` }[keyof T & string]",
      "  : never;",
      "",
      "type Data = {",
      "  users: { name: string }[];",
      "};",
      "",
      "type AllPaths = Paths<Data>;",
      "// Expected: 'users' | 'users.name'",
      "// Gets: 'users' | 'users.length' | 'users.push' | 'users.pop' | ...",
    ].join("\n"),
    errorMessage: undefined,
    bugType: "logic-error",
    bugLine: 2,
    options: [
      "keyof T & string does not filter correctly",
      "Template literal types do not work with arrays",
      "Arrays are objects — keyof string[] returns all array methods, not the element type",
      "Paths needs a depth limit",
    ],
    correctOption: 2,
    hints: [
      "What does keyof string[] return? → 'length' | 'push' | 'pop' | ...",
      "Arrays must be handled separately — extract the element type with (infer U)[].",
      "For array paths, one could use `${number}` as a placeholder.",
    ],
    fixedCode: [
      "type Paths<T> = T extends object",
      "  ? T extends (infer U)[]",
      "    ? Paths<U>",
      "    : { [K in keyof T & string]: K | `${K}.${Paths<T[K]>}` }[keyof T & string]",
      "  : never;",
      "",
      "type Data = {",
      "  users: { name: string }[];",
      "};",
      "",
      "type AllPaths = Paths<Data>;",
      "// Now: 'users' | 'users.name' (element paths)",
    ].join("\n"),
  },

  // ─── Challenge 4: Missing Tail Position ──────────────────────────────────
  {
    id: "L23-D4",
    title: "Recursion Fails at 50 Despite 'Simple' Type",
    buggyCode: [
      "type BuildTuple<N extends number, Acc extends unknown[] = []> =",
      "  Acc['length'] extends N",
      "    ? Acc",
      "    : [BuildTuple<N, [...Acc, unknown]>][0];",
      "",
      "// Works:",
      "type Ten = BuildTuple<10>;",
      "",
      "// Fails:",
      "type Hundred = BuildTuple<100>;",
      "// Error: Type instantiation is excessively deep",
    ].join("\n"),
    errorMessage: "Type instantiation is excessively deep and possibly infinite.",
    bugType: "type-error",
    bugLine: 4,
    options: [
      "BuildTuple can only count up to 10",
      "Acc needs a different initialization",
      "The [0] access prevents tail recursion optimization — the recursive call is not in tail position",
      "TypeScript 5.7 does not support tuple recursion",
    ],
    correctOption: 2,
    hints: [
      "Compare: Direct BuildTuple<N, [...Acc, unknown]> vs [BuildTuple<...>][0]",
      "Tail recursion optimization only applies when the recursive call is the LAST thing.",
      "Remove the wrapper [..][0] — the recursive call must be direct.",
    ],
    fixedCode: [
      "type BuildTuple<N extends number, Acc extends unknown[] = []> =",
      "  Acc['length'] extends N",
      "    ? Acc",
      "    : BuildTuple<N, [...Acc, unknown]>;",
      "    // ^ Directly in tail position → tail recursion optimization applies",
      "",
      "type Ten = BuildTuple<10>;     // OK",
      "type Hundred = BuildTuple<100>; // Now OK too!",
    ].join("\n"),
  },

  // ─── Challenge 5: PathValue Forgets Recursion ───────────────────────────
  {
    id: "L23-D5",
    title: "PathValue Always Returns never",
    buggyCode: [
      "type PathValue<T, P extends string> =",
      "  P extends `${infer Head}.${infer Tail}`",
      "    ? Head extends keyof T",
      "      ? T[Head]",
      "      : never",
      "    : P extends keyof T",
      "      ? T[P]",
      "      : never;",
      "",
      "type User = { address: { street: string } };",
      "type Test = PathValue<User, 'address.street'>;",
      "// Expected: string",
      "// Gets: { street: string } — WRONG!",
    ].join("\n"),
    errorMessage: undefined,
    bugType: "logic-error",
    bugLine: 4,
    options: [
      "infer does not work with dot-separated strings",
      "Head extends keyof T is wrong",
      "Line 4 returns T[Head] instead of recursively calling PathValue<T[Head], Tail>",
      "P extends keyof T in line 6 is wrong",
    ],
    correctOption: 2,
    hints: [
      "What is T[Head] for 'address.street'? → { street: string }. But we want string.",
      "For a dot-separated path, one must go DEEPER: PathValue<T[Head], Tail>.",
      "T[Head] is the intermediate object, not the final value. The recursion is missing.",
    ],
    fixedCode: [
      "type PathValue<T, P extends string> =",
      "  P extends `${infer Head}.${infer Tail}`",
      "    ? Head extends keyof T",
      "      ? PathValue<T[Head], Tail>",
      "      // ^ RECURSION: Go deeper with the remaining path",
      "      : never",
      "    : P extends keyof T",
      "      ? T[P]",
      "      : never;",
      "",
      "type User = { address: { street: string } };",
      "type Test = PathValue<User, 'address.street'>;",
      "// Now correct: string",
    ].join("\n"),
  },
];