/**
 * Lektion 17 — Completion Problems: Conditional Types
 */

export interface CompletionProblem { id: string; title: string; description: string; template: string; solution: string; blanks: { placeholder: string; answer: string; hint: string }[]; concept: string; }

export const completionProblems: CompletionProblem[] = [
  { id: "17-cp-isstring", title: "IsString<T>", description: "Complete the Conditional Type.", template: `type IsString<T> = T ______ string ? ______ : ______;`, solution: `type IsString<T> = T extends string ? true : false;`, blanks: [{ placeholder: "______", answer: "extends", hint: "Which keyword checks the subtype relationship?" }, { placeholder: "______", answer: "true", hint: "What is returned when T is a string?" }, { placeholder: "______", answer: "false", hint: "What is returned when T is NOT a string?" }], concept: "Conditional Type Basic Syntax" },
  { id: "17-cp-unpack", title: "UnpackPromise<T>", description: "Complete the Promise extraction.", template: `type UnpackPromise<T> = T extends ______<______ U> ? U : T;`, solution: `type UnpackPromise<T> = T extends Promise<infer U> ? U : T;`, blanks: [{ placeholder: "______", answer: "Promise", hint: "Which type should be unpacked?" }, { placeholder: "______", answer: "infer", hint: "Which keyword declares a type variable?" }], concept: "infer with Promise" },
  { id: "17-cp-returntype", title: "MyReturnType<T>", description: "Complete the Return Type extraction.", template: `type MyReturnType<T> = T extends (...args: ______[]) => ______ R ? R : ______;`, solution: `type MyReturnType<T> = T extends (...args: any[]) => infer R ? R : never;`, blanks: [{ placeholder: "______", answer: "any", hint: "Which type accepts all parameters?" }, { placeholder: "______", answer: "infer", hint: "Which keyword extracts the return type?" }, { placeholder: "______", answer: "never", hint: "What do you return when T is not a function?" }], concept: "ReturnType Pattern" },
  { id: "17-cp-flatten", title: "Flatten<T>", description: "Complete the recursive Flatten type.", template: `type Flatten<T> = T extends (infer U)[] ? ______<U> : T;`, solution: `type Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;`, blanks: [{ placeholder: "______", answer: "Flatten", hint: "Which type calls itself (recursion)?" }], concept: "Recursive Conditional Type" },
  { id: "17-cp-isnever", title: "IsNever<T>", description: "Complete the never detection.", template: `type IsNever<T> = ______<T> extends ______<never> ? true : false;`, solution: `type IsNever<T> = [T] extends [never] ? true : false;`, blanks: [{ placeholder: "______", answer: "[T]", hint: "How do you prevent distribution? Wrap T in a..." }, { placeholder: "______", answer: "[never]", hint: "What is checked against? Also wrapped in a tuple." }], concept: "never Detection" },
  { id: "17-cp-exclude", title: "MyExclude<T, U>", description: "Complete Exclude (removes U members from T).", template: `type MyExclude<T, U> = T extends U ? ______ : ______;`, solution: `type MyExclude<T, U> = T extends U ? never : T;`, blanks: [{ placeholder: "______", answer: "never", hint: "What removes a member from the union?" }, { placeholder: "______", answer: "T", hint: "What keeps a member in the union?" }], concept: "Distributive Exclude" },
];