/**
 * Lesson 17 — Debugging Challenges: Conditional Types
 */

import type { DebuggingChallenge } from "../tools/debugging-engine.ts";

export const debuggingChallenges: DebuggingChallenge[] = [
  { id: "L17-D1", title: "Conditional Type Not Narrowable in Function", buggyCode: "function process<T extends string | number>(v: T): T extends string ? string : number {\n  if (typeof v === 'string') return v.toUpperCase(); // Error!\n  return 0; // Error!\n}", bugType: "type-error", bugLine: 2, options: ["TypeScript cannot narrow Conditional Types through if/else", "typeof is wrong", "The Conditional Type is wrong", "extends string | number is wrong"], correctOption: 0, hints: ["Can TypeScript resolve the Conditional Type T extends string ? ... through Control Flow?", "No — this is a known limitation. Casts or Overloads are needed."], fixedCode: "function process<T extends string | number>(v: T): T extends string ? string : number {\n  if (typeof v === 'string') return v.toUpperCase() as any;\n  return 0 as any;\n}\n// Alternative: Use Function Overloads", explanation: "TypeScript cannot narrow Conditional Types through runtime checks. as any or Overloads are the workarounds.", concept: "conditional-narrowing-limitation", difficulty: 3 },
  { id: "L17-D2", title: "Distribution Surprises with never", buggyCode: "type IsString<T> = T extends string ? 'yes' : 'no';\n\ntype A = IsString<never>;\n// Expected: 'no'\n// Result: never!", bugType: "logic-error", bugLine: 3, options: ["never is the empty union — distribution over nothing yields never", "extends string is wrong for never", "IsString needs a default", "never is a bug in TypeScript"], correctOption: 0, hints: ["What is never considered as a union?", "The empty union. Distribution over 0 members = 0 results = never."], fixedCode: "type IsString<T> = [T] extends [never]\n  ? 'never'\n  : T extends string ? 'yes' : 'no';", explanation: "never = empty union. Distributive Conditionals evaluate for each member — with 0 members the result is never. With [T] extends [never] you can catch never specifically.", concept: "never-distribution", difficulty: 4 },
  { id: "L17-D3", title: "Flatten Without Recursion", buggyCode: "type Flatten<T> = T extends (infer U)[] ? U : T;\n\ntype A = Flatten<string[][]>;\n// Expected: string\n// Result: string[] (only one level!)", bugType: "logic-error", bugLine: 1, options: ["Without recursion only one array level is unwrapped", "infer U is wrong", "(infer U)[] does not match", "Flatten needs a second parameter"], correctOption: 0, hints: ["What happens when U itself is an array?", "Without recursion string[][] stops at string[]. Flatten<U> would unwrap further."], fixedCode: "type Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;", explanation: "Without recursion (Flatten<U>) only the outermost array level is unwrapped. Recursion is essential for deep unwrapping.", concept: "recursive-flatten", difficulty: 2 },
  { id: "L17-D4", title: "infer Outside of extends", buggyCode: "type GetInner<T> = infer U; // Error!\n\n// Or:\ntype GetInner2<T> = T extends string\n  ? infer U // Error! infer in true-branch\n  : never;", bugType: "type-error", bugLine: 1, options: ["infer may only appear within the extends pattern, not elsewhere", "infer needs a default", "T must be a Generic", "infer only works with functions"], correctOption: 0, hints: ["Where exactly may infer appear?", "Only in the extends part: T extends Pattern<infer U>. Not in the true/false branch."], fixedCode: "type GetInner<T> = T extends Array<infer U> ? U : never;", explanation: "infer declares a type variable that is filled through pattern matching in the extends part. It may ONLY appear there.", concept: "infer-placement", difficulty: 2 },
  { id: "L17-D5", title: "Distributive Conditional with Direct Union", buggyCode: "// Expectation: distributive\ntype Result = string | number extends string ? 'yes' : 'no';\n// Result: 'no' (NOT 'yes' | 'no'!)\n\n// Distribution only happens with type parameters!", bugType: "logic-error", bugLine: 2, options: ["Distribution only happens with naked type parameters, not with direct union types", "extends string is wrong", "string | number would need to be in parentheses", "TypeScript bug"], correctOption: 0, hints: ["Is string | number being passed through a type parameter here?", "No — it's directly in extends. Distribution requires a naked type parameter T."], fixedCode: "type DistResult<T> = T extends string ? 'yes' : 'no';\ntype Result = DistResult<string | number>;\n// 'yes' | 'no' — now distributive!", explanation: "Distribution ONLY happens when T is a naked type parameter. Direct union types in extends are checked as a whole. string | number extends string is false.", concept: "naked-type-parameter", difficulty: 3 },
];