/**
 * Lesson 17 — Misconception Exercises: Conditional Types
 */

export interface Misconception { id: string; title: string; code: string; commonBelief: string; reality: string; concept: string; difficulty: number; }

export const misconceptions: Misconception[] = [
  { id: "17-runtime-conditional", title: "Conditional Types Generate Runtime Code", code: `type Result<T> = T extends string ? string : number;\n// "Now TypeScript checks at runtime whether T is a string"`, commonBelief: "Conditional Types perform runtime checks.", reality: "Conditional Types exist ONLY at compile time. They are completely removed during compilation and generate no JavaScript code.", concept: "Type-Level vs Runtime", difficulty: 1 },
  { id: "17-narrowing-conditional", title: "if/else Narrows Conditional Types", code: `function process<T>(v: T): T extends string ? string : number {\n  if (typeof v === 'string') return v.toUpperCase(); // Error!\n  return 0; // Error!\n}`, commonBelief: "TypeScript narrows the Conditional Type through Control Flow.", reality: "TypeScript CANNOT narrow Conditional Types through if/else. This is a known limitation. Solution: Overloads or casts.", concept: "Control Flow vs Conditional Types", difficulty: 3 },
  { id: "17-infer-everywhere", title: "infer Works Everywhere", code: `type Bad = infer T; // Error!\ntype AlsoBad<T> = T extends string ? infer U : never; // Error!`, commonBelief: "infer can be used at any position in the type system.", reality: "infer may ONLY appear inside the extends clause of a Conditional Type. Nowhere else. It declares a variable that is filled through pattern matching.", concept: "infer Restrictions", difficulty: 2 },
  { id: "17-never-is-false", title: "never in Distribution Means false", code: `type IsString<T> = T extends string ? true : false;\ntype A = IsString<never>; // Expected: false\n// Reality: never`, commonBelief: "never extends string yields false.", reality: "never is the empty union. Distributive Conditional Types evaluate for each union member — with 0 members, the result is never, not true or false.", concept: "never + Distribution", difficulty: 4 },
  { id: "17-distribution-always", title: "Conditional Types Always Distribute", code: `type A<T> = T extends any ? T[] : never;\ntype B = A<string | number>; // string[] | number[] (distributive)\n\n// But:\ntype C = string | number extends any ? (string | number)[] : never;\n// (string | number)[] — NOT distributive!`, commonBelief: "All Conditional Types distribute over unions.", reality: "Distribution happens ONLY when T is a naked type parameter. Direct union types (not through type parameters) do NOT distribute. That is the difference.", concept: "Naked Type Parameters", difficulty: 3 },
  { id: "17-single-flatten", title: "Flatten Unwraps Only One Level", code: `type Flatten<T> = T extends (infer U)[] ? U : T;\n// Flatten<string[][]> = string[] (not string!)`, commonBelief: "Flatten unwraps arrays arbitrarily deep.", reality: "Without recursion, Flatten unwraps only ONE level: string[][] -> string[]. For deep unwrapping you need: T extends (infer U)[] ? Flatten<U> : T — the recursion is crucial!", concept: "Recursion vs Single Unwrap", difficulty: 2 },
  { id: "17-infer-position", title: "infer Position Doesn't Matter", code: `type A<T> = T extends (infer U)[] ? U : never; // Element type\ntype B<T> = T extends Array<infer U> ? U : never; // Also element type\n// A and B do the same thing — but infer at a different position extracts something different!`, commonBelief: "It doesn't matter where infer is placed — it always extracts the same thing.", reality: "infer extracts EXACTLY the type at the position where it appears. infer in the return position extracts the return type, infer in the parameter position extracts the parameter type. The position determines what is extracted.", concept: "infer Positioning", difficulty: 2 },
  { id: "17-extends-equality", title: "extends Means Equality", code: `type Test = 'hello' extends string ? true : false; // true\n// But: string extends 'hello' ? true : false → false!`, commonBelief: "T extends U checks whether T and U are equal.", reality: "extends checks subtype relationship, not equality. 'hello' extends string is true (literal is a subtype). But string extends 'hello' is false (string is NOT a subtype of a literal). extends is asymmetric!", concept: "extends = Subtype, Not Equality", difficulty: 3 },
];