/**
 * Lesson 17 — Tracing Exercises: Conditional Types
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  { id: "17-distribution-step", title: "Distribution Step by Step", description: "Trace how a distributive conditional type distributes over a union.", code: ["type ToArray<T> = T extends any ? T[] : never;", "", "type Result = ToArray<string | number | boolean>;"], steps: [{ lineIndex: 2, question: "Step 1: What happens for string?", expectedAnswer: "string extends any = true -> string[]", variables: { "T": "string", "Result": "string[]" }, explanation: "First union member: string. string extends any is true -> string[]." }, { lineIndex: 2, question: "Step 2: What happens for number?", expectedAnswer: "number extends any = true -> number[]", variables: { "T": "number", "Result": "number[]" }, explanation: "Second union member: number. number extends any is true -> number[]." }, { lineIndex: 2, question: "Step 3: What happens for boolean?", expectedAnswer: "boolean extends any = true -> boolean[]", variables: { "T": "boolean", "Result": "boolean[]" }, explanation: "Third union member: boolean -> boolean[]." }, { lineIndex: 2, question: "What is the final result?", expectedAnswer: "string[] | number[] | boolean[]", variables: { "Result": "string[] | number[] | boolean[]" }, explanation: "All individual results are merged into a union." }], concept: "distribution-step-by-step", difficulty: 2 },
  { id: "17-infer-extraction", title: "infer Extracts Types from Patterns", description: "Trace how infer extracts different parts of a function.", code: ["type FnParts<T> =", "  T extends (a: infer A, b: infer B) => infer R", "  ? { first: A; second: B; ret: R }", "  : never;", "", "type Parts = FnParts<(name: string, age: number) => boolean>;"], steps: [{ lineIndex: 5, question: "Does the pattern match?", expectedAnswer: "Yes — (name: string, age: number) => boolean matches (a: infer A, b: infer B) => infer R", variables: { "Match": "true" }, explanation: "The function has 2 parameters and a return type — fits the pattern." }, { lineIndex: 5, question: "What is A?", expectedAnswer: "string (first parameter)", variables: { "A": "string" }, explanation: "infer A is at the position of the first parameter -> A = string." }, { lineIndex: 5, question: "What are B and R?", expectedAnswer: "B = number, R = boolean", variables: { "B": "number", "R": "boolean" }, explanation: "B = second parameter (number), R = return type (boolean)." }, { lineIndex: 5, question: "What is Parts?", expectedAnswer: "{ first: string; second: number; ret: boolean }", variables: { "Parts": "{ first: string; second: number; ret: boolean }" }, explanation: "All infer variables are substituted into the result object." }], concept: "infer-multi-extraction", difficulty: 3 },
  { id: "17-recursive-flatten", title: "Recursive Flatten Step by Step", description: "Trace how Flatten recursively unpacks a nested array.", code: ["type Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;", "", "type Result = Flatten<number[][][]>;"], steps: [{ lineIndex: 2, question: "Step 1: Flatten<number[][][]>", expectedAnswer: "number[][][] extends (infer U)[]? Yes, U = number[][]. -> Flatten<number[][]>", variables: { "T": "number[][][]", "U": "number[][]" }, explanation: "Outermost array is unpacked. U = number[][]." }, { lineIndex: 2, question: "Step 2: Flatten<number[][]>", expectedAnswer: "number[][] extends (infer U)[]? Yes, U = number[]. -> Flatten<number[]>", variables: { "T": "number[][]", "U": "number[]" }, explanation: "Next level is unpacked. U = number[]." }, { lineIndex: 2, question: "Step 3: Flatten<number[]>", expectedAnswer: "number[] extends (infer U)[]? Yes, U = number. -> Flatten<number>", variables: { "T": "number[]", "U": "number" }, explanation: "Last array level is unpacked. U = number." }, { lineIndex: 2, question: "Step 4: Flatten<number>", expectedAnswer: "number extends (infer U)[]? No -> T = number. Done!", variables: { "T": "number", "Result": "number" }, explanation: "number is not an array. Else branch: T = number. Recursion terminates." }], concept: "recursive-flatten-trace", difficulty: 3 },
  { id: "17-never-distribution", title: "never in Distribution", description: "Trace what happens when never meets a distributive conditional.", code: ["type IsString<T> = T extends string ? 'yes' : 'no';", "", "type A = IsString<string>;", "type B = IsString<number>;", "type C = IsString<string | number>;", "type D = IsString<never>;"], steps: [{ lineIndex: 2, question: "IsString<string>?", expectedAnswer: "'yes'", variables: { "A": "'yes'" }, explanation: "string extends string is true -> 'yes'." }, { lineIndex: 4, question: "IsString<string | number>?", expectedAnswer: "'yes' | 'no' (distributive)", variables: { "C": "'yes' | 'no'" }, explanation: "Distribution: IsString<string> | IsString<number> = 'yes' | 'no'." }, { lineIndex: 5, question: "IsString<never>?", expectedAnswer: "never (NOT 'no'!)", variables: { "D": "never" }, explanation: "never = empty union. Distribution over 0 members = 0 results = never." }], concept: "never-is-empty-union", difficulty: 4 },
];