/**
 * Lesson 17 — Transfer Tasks: Conditional Types
 */

import type { TransferTask } from "../tools/transfer-engine.ts";

export const transferTasks: TransferTask[] = [
  { id: "17-smart-api-client", title: "Smart API Client with Conditional Return Types", prerequisiteLessons: [16, 17], scenario: "Your API client always returns `unknown` and requires manual casts. For each endpoint you actually know exactly which type comes back — but the client doesn't use this knowledge.", task: "Create a type-safe API client:\n\n1. Define an EndpointMap interface that maps paths to response types\n2. Use Conditional Types to determine the return type based on the path\n3. Use infer to extract path parameters (e.g. /users/:id)\n4. Demonstrate with GET /users, GET /users/:id, POST /users", starterCode: "// TODO: EndpointMap, ApiClient with Conditional Return Types", solutionCode: "interface EndpointMap {\n  '/users': User[];\n  '/users/:id': User;\n  '/products': Product[];\n}\n\ntype ResponseFor<Path extends string> =\n  Path extends keyof EndpointMap ? EndpointMap[Path] : unknown;\n\nasync function apiGet<P extends string>(path: P): Promise<ResponseFor<P>> {\n  const res = await fetch(path);\n  return res.json();\n}\n\n// const users = await apiGet('/users'); // User[]\n// const user = await apiGet('/users/:id'); // User", conceptsBridged: ["Conditional Types for response inference", "infer for path parameters", "Mapped Interface as endpoint registry"], estimatedMinutes: 20, difficulty: 3 },
  { id: "17-type-safe-builder", title: "Type-safe Query Builder with Conditional Types", prerequisiteLessons: [14, 17], scenario: "You are building a SQL query builder. Currently every method returns `any`. WHERE conditions accept wrong columns, SELECT returns the wrong fields.", task: "Create a type-safe query builder:\n\n1. select<K extends keyof T>(...keys: K[]) should constrain the result type to Pick<T, K>\n2. where<K extends keyof T>(key: K, op: '=' | '>' | '<', value: T[K]) should be type-safe\n3. Use Conditional Types for the result type based on the selected fields\n4. Demonstrate with a User type", starterCode: "// TODO: QueryBuilder<T, Selected> with Conditional Types", solutionCode: "class QueryBuilder<T, Selected extends keyof T = keyof T> {\n  private _where: string[] = [];\n  private _select: Selected[] = [];\n\n  select<K extends keyof T>(...keys: K[]): QueryBuilder<T, K> {\n    return new QueryBuilder<T, K>();\n  }\n\n  where<K extends keyof T>(key: K, op: '=' | '>' | '<', value: T[K]): this {\n    return this;\n  }\n\n  execute(): Pick<T, Selected>[] {\n    return [] as Pick<T, Selected>[];\n  }\n}\n\ninterface User { id: number; name: string; email: string; age: number; }\nconst result = new QueryBuilder<User>()\n  .select('name', 'email')\n  .where('age', '>', 18)\n  .execute();\n// result: Pick<User, 'name' | 'email'>[] = { name: string; email: string }[]", conceptsBridged: ["Builder Pattern with type transformation", "Conditional Types for result type narrowing", "Generic Constraints with keyof"], estimatedMinutes: 25, difficulty: 4 },
];