/**
 * Lektion 12 — Parson's Problems: Discriminated Unions
 */

import type { ParsonsProblem } from "../tools/parsons-engine.ts";

export const parsonsProblems: ParsonsProblem[] = [
  {
    id: "L12-P1",
    title: "Discriminated Union mit Exhaustive Check",
    description: "Ordne die Zeilen zu einer Shape-Union mit area-Funktion und assertNever.",
    correctOrder: [
      'type Shape =',
      '  | { kind: "circle"; radius: number }',
      '  | { kind: "rect"; width: number; height: number };',
      '',
      'function assertNever(value: never): never {',
      '  throw new Error(`Unbehandelt: ${value}`);',
      '}',
      '',
      'function area(shape: Shape): number {',
      '  switch (shape.kind) {',
      '    case "circle": return Math.PI * shape.radius ** 2;',
      '    case "rect": return shape.width * shape.height;',
      '    default: return assertNever(shape);',
      '  }',
      '}',
    ],
    distractors: [
      'function assertNever(value: unknown): never {',
      '    default: return assertNever(shape.kind);',
    ],
    hint: "assertNever nimmt 'never' (nicht unknown) und bekommt das Objekt (nicht den Diskriminator).",
    concept: "exhaustive-check",
    difficulty: 2,
  },

  {
    id: "L12-P2",
    title: "Option<T> mit Konstruktoren",
    description: "Ordne die Zeilen zu einem vollstaendigen Option<T> Typ mit some/none/unwrapOr.",
    correctOrder: [
      'type Option<T> =',
      '  | { tag: "some"; value: T }',
      '  | { tag: "none" };',
      '',
      'function some<T>(value: T): Option<T> {',
      '  return { tag: "some", value };',
      '}',
      '',
      'function none<T>(): Option<T> {',
      '  return { tag: "none" };',
      '}',
      '',
      'function unwrapOr<T>(opt: Option<T>, fallback: T): T {',
      '  if (opt.tag === "some") return opt.value;',
      '  return fallback;',
      '}',
    ],
    distractors: [
      '  if (opt.tag === "none") return opt.value;',
      'function some<T>(value: T): T {',
    ],
    hint: "some gibt Option<T> zurueck (nicht T). unwrapOr gibt opt.value bei 'some' zurueck (nicht bei 'none').",
    concept: "option-adt",
    difficulty: 3,
  },

  {
    id: "L12-P3",
    title: "AsyncState<T> mit render-Funktion",
    description: "Ordne die Zeilen zu einem vollstaendigen AsyncState-Typ mit render-Funktion.",
    correctOrder: [
      'type AsyncState<T> =',
      '  | { status: "idle" }',
      '  | { status: "loading" }',
      '  | { status: "error"; error: string }',
      '  | { status: "success"; data: T };',
      '',
      'function render<T>(state: AsyncState<T>): string {',
      '  switch (state.status) {',
      '    case "idle": return "Bereit";',
      '    case "loading": return "Lade...";',
      '    case "error": return `Fehler: ${state.error}`;',
      '    case "success": return `OK: ${JSON.stringify(state.data)}`;',
      '  }',
      '}',
    ],
    distractors: [
      '  | { status: "error"; message: string }',
      '    case "error": return `Fehler: ${state.message}`;',
    ],
    hint: "Die error-Variante hat die Property 'error' (nicht 'message'). Konsistent bleiben!",
    concept: "async-state",
    difficulty: 2,
  },

  {
    id: "L12-P4",
    title: "Redux-style Reducer mit Action Union",
    description: "Ordne die Zeilen zu einem Counter-Reducer mit typsicheren Actions.",
    correctOrder: [
      'type CounterAction =',
      '  | { type: "INCREMENT" }',
      '  | { type: "DECREMENT" }',
      '  | { type: "SET"; payload: { value: number } };',
      '',
      'function reducer(count: number, action: CounterAction): number {',
      '  switch (action.type) {',
      '    case "INCREMENT": return count + 1;',
      '    case "DECREMENT": return count - 1;',
      '    case "SET": return action.payload.value;',
      '  }',
      '}',
    ],
    distractors: [
      '  | { type: "SET"; value: number };',
      '    case "SET": return action.value;',
    ],
    hint: "Redux-Konvention: Daten liegen in payload.value (nicht direkt in action.value). Die Action hat { type, payload }.",
    concept: "action-types-reducer",
    difficulty: 3,
  },
];
