/**
 * Lektion 12 — Tracing-Exercises: Discriminated Unions
 */

import type { TracingExercise } from "../tools/tracing-engine.ts";

export const tracingExercises: TracingExercise[] = [
  {
    id: "12-narrowing-flow",
    title: "Narrowing durch Diskriminator",
    description: "Verfolge wie TypeScript den Typ durch switch/case verengt.",
    code: [
      'type Shape = { kind: "circle"; radius: number } | { kind: "rect"; w: number; h: number };',
      '',
      'function area(shape: Shape): number {',
      '  switch (shape.kind) {',
      '    case "circle":',
      '      return Math.PI * shape.radius ** 2;',
      '    case "rect":',
      '      return shape.w * shape.h;',
      '  }',
      '}',
      '',
      'console.log(area({ kind: "circle", radius: 5 }));',
      'console.log(area({ kind: "rect", w: 10, h: 3 }));',
    ],
    steps: [
      {
        lineIndex: 4,
        question: "Welchen Typ hat shape im case 'circle'?",
        expectedAnswer: '{ kind: "circle"; radius: number }',
        variables: { "shape.kind": '"circle"', "shape.radius": "5" },
        explanation: "TypeScript narrowt shape zur Circle-Variante weil kind === 'circle' geprueft wurde.",
      },
      {
        lineIndex: 5,
        question: "Was gibt Math.PI * 5 ** 2 zurueck?",
        expectedAnswer: "~78.54 (Math.PI * 25)",
        variables: { "shape.radius": "5", "Ergebnis": "78.5398..." },
        explanation: "** ist der Potenz-Operator. 5 ** 2 = 25. Math.PI * 25 = ~78.54.",
      },
      {
        lineIndex: 7,
        question: "Welchen Typ hat shape im case 'rect'?",
        expectedAnswer: '{ kind: "rect"; w: number; h: number }',
        variables: { "shape.kind": '"rect"', "shape.w": "10", "shape.h": "3" },
        explanation: "Nach dem circle-case bleibt nur rect uebrig. TypeScript narrowt automatisch.",
      },
    ],
    concept: "discriminator-narrowing",
    difficulty: 1,
  },

  {
    id: "12-exhaustive-never",
    title: "Exhaustive Check mit never",
    description: "Verfolge wie assertNever funktioniert.",
    code: [
      'type Light = { color: "red" } | { color: "yellow" } | { color: "green" };',
      '',
      'function assertNever(value: never): never {',
      '  throw new Error(`Unbehandelt: ${JSON.stringify(value)}`);',
      '}',
      '',
      'function action(light: Light): string {',
      '  switch (light.color) {',
      '    case "red": return "Stop";',
      '    case "yellow": return "Caution";',
      '    case "green": return "Go";',
      '    default: return assertNever(light);',
      '  }',
      '}',
    ],
    steps: [
      {
        lineIndex: 8,
        question: "Welchen Typ hat light nach case 'red'?",
        expectedAnswer: '{ color: "yellow" } | { color: "green" } — red wurde eliminiert',
        variables: {},
        explanation: "TypeScript schraenkt nach jedem case den verbleibenden Typ ein.",
      },
      {
        lineIndex: 10,
        question: "Welchen Typ hat light nach case 'green'?",
        expectedAnswer: "never — alle Varianten wurden eliminiert",
        variables: {},
        explanation: "Nach red, yellow und green bleibt nichts uebrig. Der Typ ist never.",
      },
      {
        lineIndex: 11,
        question: "Warum kompiliert assertNever(light) ohne Error?",
        expectedAnswer: "Weil light den Typ never hat — never ist an never zuweisbar",
        variables: { "light": "(Typ: never)" },
        explanation: "Alle Faelle behandelt = never im default. assertNever akzeptiert never = kein Error.",
      },
    ],
    concept: "exhaustive-check-never",
    difficulty: 2,
  },

  {
    id: "12-option-flow",
    title: "Option<T> — Datenfluss",
    description: "Verfolge wie Werte durch Option<T> fliessen.",
    code: [
      'type Option<T> = { tag: "some"; value: T } | { tag: "none" };',
      '',
      'function some<T>(value: T): Option<T> { return { tag: "some", value }; }',
      'function none<T>(): Option<T> { return { tag: "none" }; }',
      '',
      'function safeDivide(a: number, b: number): Option<number> {',
      '  if (b === 0) return none();',
      '  return some(a / b);',
      '}',
      '',
      'const r1 = safeDivide(10, 3);',
      'const r2 = safeDivide(10, 0);',
      '',
      'console.log(r1);',
      'console.log(r2);',
    ],
    steps: [
      {
        lineIndex: 10,
        question: "Was ist r1?",
        expectedAnswer: '{ tag: "some", value: 3.3333... }',
        variables: { "r1.tag": '"some"', "r1.value": "3.3333..." },
        explanation: "b ist 3 (nicht 0), also gibt safeDivide some(10/3) zurueck.",
      },
      {
        lineIndex: 11,
        question: "Was ist r2?",
        expectedAnswer: '{ tag: "none" }',
        variables: { "r2.tag": '"none"' },
        explanation: "b ist 0, also gibt safeDivide none() zurueck. Kein Error, kein Crash.",
      },
      {
        lineIndex: 13,
        question: "Wie greift man sicher auf r1.value zu?",
        expectedAnswer: 'if (r1.tag === "some") { r1.value }',
        variables: {},
        explanation: "Man muss den Diskriminator 'tag' pruefen bevor man auf value zugreift. Das erzwingt TypeScript.",
      },
    ],
    concept: "option-data-flow",
    difficulty: 2,
  },

  {
    id: "12-async-state-transitions",
    title: "AsyncState — Zustandsuebergaenge",
    description: "Verfolge die Zustandsuebergaenge eines Ladeprozesses.",
    code: [
      'type AsyncState<T> =',
      '  | { status: "idle" }',
      '  | { status: "loading" }',
      '  | { status: "error"; error: string }',
      '  | { status: "success"; data: T };',
      '',
      'let state: AsyncState<string[]> = { status: "idle" };',
      'console.log(state.status);',
      '',
      'state = { status: "loading" };',
      'console.log(state.status);',
      '',
      'state = { status: "error", error: "Timeout" };',
      'console.log(state.status, (state as any).error);',
      '',
      'state = { status: "success", data: ["Alice", "Bob"] };',
      'console.log(state.status, (state as any).data);',
    ],
    steps: [
      {
        lineIndex: 7,
        question: "Was gibt console.log aus?",
        expectedAnswer: '"idle"',
        variables: { "state.status": '"idle"' },
        explanation: "Anfangszustand ist idle — noch keine Daten geladen.",
      },
      {
        lineIndex: 10,
        question: "Welche Properties hat state jetzt?",
        expectedAnswer: 'Nur { status: "loading" } — keine data, kein error',
        variables: { "state.status": '"loading"' },
        explanation: "Loading hat nur status. data und error existieren nicht — unmoegliche Zustaende verhindert!",
      },
      {
        lineIndex: 13,
        question: "Was gibt console.log aus?",
        expectedAnswer: '"error" "Timeout"',
        variables: { "state.status": '"error"', "state.error": '"Timeout"' },
        explanation: "Error-Zustand hat status und error. Keine data — das waere unsinnig bei einem Fehler.",
      },
      {
        lineIndex: 16,
        question: "Was gibt console.log aus?",
        expectedAnswer: '"success" ["Alice", "Bob"]',
        variables: { "state.status": '"success"', "state.data": '["Alice", "Bob"]' },
        explanation: "Success hat status und data. Kein error — das waere unsinnig bei Erfolg.",
      },
    ],
    concept: "async-state-transitions",
    difficulty: 2,
  },
];
